### ISSUE TITLE
[Bug] Custom Field Types Throw A Warning

### ISSUE THREAD

**Issue by cdowdy** [bolt/bolt#6782] opened 2017-06-29 14:04 UTC
An extension providing a custom field type following [Providing New Field Types](https://docs.bolt.cm/3.2/extensions/advanced/fieldtypes) docs example will throw an alert with the warning:  

>In the ContentType for 'yourContentType', the field 'yourField' has 'type: yourType', which is not a proper field type. Please edit contenttypes.yml, and correct this.  

Details
-------

 - Relevant Bolt Version: [ 3.2.14+ ]
 - Install type: [ Zip Install & Composer install ]
 - PHP version: [ 7.0 ]
 - Used web server: [ Apache [2.4.18] | Nginx [1.10.2] ]
 - For UX/UI issues: [ browser name and version ]

Reproduction
------------

 1. **Bug summary**:  
  Custom field types throw a warning about not being a proper field type
 2. **Specifics**:
    * URL:  any backend page while logged in will have the alert
    * Bolt 3.2.14
    * Composer and Zip Installs
    * Browsers: Chrome/Firefox/Edge all of em :)
    * Error Message:  
      * >In the ContentType for 'yourContentType', the field 'yourField' has 'type: yourType', which is not a proper field type. Please edit contenttypes.yml, and correct this.  
      * ![bolt-custom-field-error](https://user-images.githubusercontent.com/5969974/27691299-99859cb6-5cb1-11e7-877a-fcf39d31a30c.png)

 3. **Steps to reproduce**:
    *   install bolt, create lorem ipsum records, install locally @rossriley 's URL field extension (https://github.com/rossriley/bolt-url-field)  
    * create or edit a contentType with the URL field and type  
    ```yaml  
    testField:
    name: TestFields
    singular_name: testField
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        web: # our field using custom type
            type: url # the custom type from Ross' example
            label: Enter a web address
    relations:
        pages:
          multiple: false
          order: title
          label: Select a page
    taxonomy: [ categories, tags ]
    record_template: entry.twig
    listing_template: listing.twig
    listing_records: 10
    default_status: publish
    sort: -datepublish
    recordsperpage: 10
    ```
 4. **Expected result**: 
    * No warning to be thrown since everything functions "normally"
 5. **Actual result**: 
    * a warning flashbag is thrown

**Comment by mrenigma** [comment] 2017-07-13 13:41
Just came across this issue myself on an older site using Bolt 3.2.6.

It doesn't affect repeaters but that may be because repeaters aren't checked in the `checkConfig` method?

I noticed that the relationlist field extension isn't affected and this uses the old way using `registerFields()`. So I assume it's because `Bolt\Config` is using the deprecated `Storage\Field\Manager`? Although I have no clue how to fix it 😄

**Comment by rossriley** [comment] 2017-07-15 07:54
Yes, that's right, the Config version works because the checks and the validator are in the same class, the problem is just one of load order, whereby in an attempt to decouple the field configuration from the fields themselves we've run into a condition where the config file is parsed before the additional fields in an extension are available.

We'll get a quick fix up soon, hopefully get it sorted today, the long term fix will be better as the Configuration system is being refactored at the moment for 3.4 and will be a bit more sophisticated than a massive array.

**Comment by rossriley** [comment] 2017-07-15 12:32
@gawainlynch scored a double bonus with this one, fixed with https://github.com/bolt/bolt/commit/280e45479233d8d0b26b94db2f29ce112aa248b0#diff-bb7d0af11f037a6468884c4e9371c46aL213

**Closed by rossriley** 2017-07-15 12:32 UTC

**Comment by GawainLynch** [comment] 2017-07-15 12:33
For historians, the PR was #6802

@rossriley you made my day with finding this one out, I must say! Thank mate :+1:
