### ISSUE TITLE
[BUG] Unable to generate a URL for the named route "preview" since 2.2.17

### ISSUE THREAD

**Issue by rompcik** [bolt/bolt#4870] opened 2016-02-19 21:28 UTC
Since 2.2.17 Bolt refuses editing some of my multi-language contenttypes.
Reverting to 2.2.16 everything works, but with 2.2.17 and 2.218 I get the following error trying to edit or create a multilingual contenttype:

> An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "preview" as such route does not exist.") in "editcontent/_buttons.twig" at line 36.

contenttype:
```yaml
en-pages:
    name: Pages
    singular_name: Page
    fields: &pagefields
        title:
            type: text
            class: large
            group: content
            required: true
        slug:
            type: slug
            uses: title
        subtitle:
            type: text
        sorting:
            type: integer
            label: Display order
        background-image:
            type: image
            group: media
            label: Background Image (1920 x 1080)
        teaser-image:
            type: image
            label: Teaser Image (840 x 175)
        seo-keywords:
            type: text
            group: seo
            label: SEO Keywords (Use comma to separate)
        seo-description:
            type: textarea
            label: SEO Description
    relations:
        de-pages: &langrelations
            multiple: false
            label: Select a page
            order: id
    sort: sorting
    icon_many: "fa:file-text-o"
    icon_one: "fa:file-text"
    record_template: page.twig
    show_in_menu: English
de-pages:
    name: Seiten
    singular_name: Seite
    fields: *pagefields
    relations:
        en-pages: *langrelations
    sort: sorting
    icon_many: "fa:file-text-o"
    icon_one: "fa:file-text"
    record_template: page.twig
    show_in_menu: Deutsch

**Comment by SahAssar** [comment] 2016-02-22 21:42
What does your routing.yml look like?

**Comment by rompcik** [comment] 2016-02-22 22:02
My routing.yml looks like this (and works with 2.2.16!):

```yaml
# ------------------------------------------------------------------------------
# [en,de] Automatic Selection of Language for Frontpage
# ------------------------------------------------------------------------------
homepage:
    path:               /
    defaults:           { _controller: 'Hotel\Controller::i18nFront' }

# ------------------------------------------------------------------------------
# [en] English
# ------------------------------------------------------------------------------

en-home:
    path:               /en
    defaults:           { _controller: 'Bolt\Controllers\Frontend::record', 'contenttypeslug': 'en-pages', 'slug': 'home' }


en-offers:
    path:               /en/offer/{slug}
    defaults:           { _controller: 'Bolt\Controllers\Frontend::record', 'contenttypeslug': 'en-offers' }
    contenttype:        en-offers

en-pages:
    path:               /en/{slug}
    defaults:           { _controller: 'Bolt\Controllers\Frontend::record', 'contenttypeslug': 'en-pages' }
    contenttype:        en-pages

# ------------------------------------------------------------------------------
# [de] Deutsch
# ------------------------------------------------------------------------------

de-home:
    path:               /de
    defaults:           { _controller: 'Bolt\Controllers\Frontend::record', 'contenttypeslug': 'de-pages', 'slug': 'home' }

de-offers:
    path:               /de/angebot/{slug}
    defaults:           { _controller: 'Bolt\Controllers\Frontend::record', 'contenttypeslug': 'de-offers' }
    contenttype:        de-offers

de-pages:
    path:               /de/{slug}
    defaults:           { _controller: 'Bolt\Controllers\Frontend::record', 'contenttypeslug': 'de-pages' }
    contenttype:        de-pages
    
unknown:
    path:               /{slug}
    defaults:           {  _controller: 'Bolt\Controllers\Frontend::record', _before: 'Hotel\Controller::i18nBefore', 'contenttypeslug': 'Bolt\Controllers\Routing::getAnyContentTypeRequirement' }
```

**Comment by bobdenotter** [comment] 2016-02-22 22:13
@rompcik 

You've removed the preview route, correct? https://github.com/bolt/bolt/blob/release/2.2/app/config/routing.yml.dist#L25

It needs to be present.

**Comment by bobdenotter** [comment] 2016-02-22 22:17
@rompcik I didn't really mean to close it, my apologies.. If replacing the route doesn't help, feel free to re-open the issue.

**Comment by rompcik** [comment] 2016-02-22 22:56
I haven't removed anything. I just did NOT ADD the preview route, which seems necessary for 2.2.17 and up. Thats a big difference.

**Comment by SahAssar** [comment] 2016-02-22 22:58
@rompcik But is that your **full** routing.yml then? If not, could you post that?

**Comment by rompcik** [comment] 2016-02-22 23:21
@SahAssar: Bug is closed. It was the missing preview-route. Site started with bolt 2.0.x and has been continuously updated to new version. Always worked without preview-route. Seems since 2.2.17 something has changed... But reverting my changes I can say I did remove the route right at the start. No problem til 2.2.17, everything worked fine.

Thx again for fast support.

**Comment by SahAssar** [comment] 2016-02-22 23:28
@rompcik I'm just trying to understand the bug since if it broke something between 2.2.X versions we probably need to have a look at it, I'll have a look tomorrow.

**Comment by SahAssar** [comment] 2016-02-23 19:54
I can't reproduce this as working in 2.2.16 without the preview route, so it seems to me like it has required the preview route all along. Perhaps it was cached and a certain update triggered a cache clear? Anyway, I'm closing this, please reopen if someone comes along and this is an issue! :)

**Closed by SahAssar** 2016-02-23 19:54 UTC
Labels: Bug verification needed
