### ISSUE TITLE
Error pages system

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#3939] opened 2015-08-08 09:12 UTC
It would be lovely to have ability to setup error pages independently from database, storage, conttenttypes etc. Just some settings in config.yml that allowing to point error page templates.

**Comment by GawainLynch** [comment] 2015-08-08 09:14
This is for 404 pages I take it?

**Comment by Boorj** [comment] 2015-08-08 13:49
Yes. Not only for 404, maybe for 500, when there's a server error and database could be unreachable.
Just for reference:
(http://symfony.com/doc/current/cookbook/controller/error_pages.html)

**Comment by GawainLynch** [comment] 2015-08-08 13:51
Yeah… 404s are easy…

The 500s are harder… but it really depends on where in the stack they occur. The work we did on the controllers might make this a lot easier, and I know @CarsonF just **loves** the state of the error handling :stuck_out_tongue:

**Comment by Boorj** [comment] 2015-08-08 13:57
Suppose users won't desire to generate also .html file (for a case if twig breaks), so there should be a cure for that case also.

**Comment by GawainLynch** [comment] 2015-08-08 14:01
Yeah, part of the problem (not objecting, just saying) is that to end up in an error state you have to use an error handler and they don't have error handling… so you can lose access to some errors if they happen to be related to Twig (for example).

**Comment by Boorj** [comment] 2015-08-08 17:15
User can configure server that will be cooperating with bolt, so it will handle errors outside Bolt.

### +
Symfony added "preview error page" in 2.6, as i remember. I suppose it's a lovely feature, since we can't do this properly in Bolt)

### +
Suggestion. Maybe you can make *html generator* that will generate a pack of html error pages from one template. So you press the button, it generates everything with proper links (Page not found. here's the link to homepage or search..). While user is configuring those pages, server works) so in that period he can make all tunings safely. And then that special button will just give you nginx or apache (.htaccess) configs. 
Just as an idea =)

**Comment by GawainLynch** [comment] 2015-08-08 17:25
> User can configure server that will be cooperating with bolt, so it will handle errors outside Bolt.

No, only certain errors can be handled… if the occur early in the stack, e.g. extension initialisation, then this is useless. Hence why/how we handle it… Symfony doesn't do "extensions".

**Comment by Pinpickle** [comment] 2015-08-12 00:44
I came up with an idea to handle this in #3458

Where the error is appropriate to be handled by the error template (which currently universally cries 404), we could have twig variables exposed for the error code, error message and stack trace so template editors can expose as much or as little information as they like.

**Comment by Boorj** [comment] 2015-08-13 05:12
Actually, if the error is catchable it should be cought and seen by developer. I suppose it's enough for visitors to see "We're having some server troubles blah blah. Go here .. or try later". Also i assume that there should be a bunch of exception classes that are cought by superior script and then decide - what error to expose.
Point was to make a template for each basic type of errors, not for cute debugging. For those purposes we have whoops or whatever bolt has got.

**Comment by GawainLynch** [comment] 2015-08-13 07:01
For developers, catchable PHP errors go to Whoops! and fatal PHP errors go though to Bolt's error catcher… Trying to `render()` in there is nothing short of a bad idea as you run a very real risk of losing information in further error states caused by the stacks inability to operate.

HTTP errors are yes, a different story.

**Comment by SahAssar** [comment] 2015-09-29 22:53
Going to close this since it's basically a duplicate of #3458 

@Boorj If you feel this is not the case feel free to reopen :)

**Closed by SahAssar** 2015-09-29 22:53 UTC
Labels: Feature
