### ISSUE TITLE
Relation in templatefields

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/bolt#4072] opened 2015-09-09 13:13 UTC
Hey,

it would be cool if you can add relationships to the templatefields so the yaml structure would be the same as at the contentypes.

**Comment by bobdenotter** [comment] 2015-09-09 13:17
That's not really feasible right now. The "template fields" are stored inside the record, while relationships are linked via a different table in the DB. What's the usecase, where using 'normal' relationships don't make sense?

**Comment by PhillippOhlandt** [comment] 2015-09-09 16:55
We have many possible templates for a contenttype and need some relationships in the one template and other relationships in the other template. Now I have to catch the selected template with JS and hide the other relation select fields.

**Comment by SahAssar** [comment] 2015-09-14 19:24
This is something that'd I'd find useful too. Treating taxonomy and relations as regular fields in contenttypes and template specific fields would be awesome, but I'm guessing it would be quite complicated to implement properly.

**Comment by PhillippOhlandt** [comment] 2015-09-15 11:07
Yep that would be cool. But then you can have problems when a user want assign another contenttype for 3 different content fields.

**Comment by GawainLynch** [comment] 2015-10-04 22:19
@rossriley might have other ideas as he went thought the pain of trying to get some rationale into templatefields, but I honestly can't see this as possible in 2.x… the queries to make this happen would murder the database engine on medium to large sites.

Flat out, I don't think this is a valid approach but am willing to be shown that I am totally wrong :grinning:

**Comment by rossriley** [comment] 2015-10-05 07:04
Yes, this will need to go under things we are not going to be able to get working until 3.0, this is not necessarily by design, because the new Storage layer introduces the concept of aliases for relations, so it's feasible to have multiple groups of relations on a record.

The problem we've found is merging this in and maintaining backwards compatibility for the 2.x branch so we made the decision to keep the relations UI working the same and whilst the structure is there to have something like: `$record['aboutPages'];` and `$record['otherPages']` to get it working we've had to stick to `$record['relations']['pages']` which forces a single group for now.

Once we can retire this, then we can open up relations being another embeddable field type and thus they can work in both template fields and the new repeating fields.

**Comment by PhillippOhlandt** [comment] 2015-10-05 07:32
Ah ok. I don't need that now, it was only an idea, so relax guys =)

My first thought for a solution was to simpy merge the two relation arrays from the contenttype.yml and the template config.yml before you parse it to build the form.

But I see it's much more complicated.

**Comment by GawainLynch** [comment] 2015-10-05 07:35
> Ah ok. I don't need that now, it was only an idea, so relax guys =)

We're so relaxed, we're almost asleep :wink:

**Comment by PhillippOhlandt** [comment] 2015-10-05 07:37
Haha I saw that yesterday on the master branch. Now I have to test if everything still work as expected :P

**Comment by rossriley** [comment] 2016-03-24 21:28
Ok, I'm going to close this since there will at some point be a solution arriving in the 3.x series but it will probably take on a slightly different format than being added to templatefields.

**Closed by rossriley** 2016-03-24 21:28 UTC
Labels: Enhancement
