### ISSUE TITLE
BUG Update 2.2 -> 3.0.2 Database Check Loop.

### ISSUE THREAD

**Issue by dlightme** [bolt/bolt#5486] opened 2016-06-25 19:28 UTC
After upgrade, the "Check Database" tool is stuck in a loop:

> Modifications needed:
> Table bolt_users is not the correct schema: missing index on username, removed index idx_5585b54f85e0677

Details
-------

 - Relevant Bolt Version: [ 3.0 | master ]
 - Install type: [ Zip/tarball install ]
 - PHP version: [ 5.6 ]
 - Used webserver: [ Apache ]
-  MySql DB.

Reproduction
------------

 1. Upgrade from 2.2.22 ->3.0.2 via ftp. setting "public" folder to webhost root via .bolt.yml file
 2. Log-in and run "Database check / update"
 3. After pressing "Update the Database", the page refreshes with "Table bolt_users is not the correct schema: missing index on username, removed index idx_5585b54f85e0677", every consecutive try results in the same message.
 4. **Expected result**: "Database Updated Successfully"
 5. **Actual result**: Returns "Table bolt_users is not the correct schema: missing index on username, removed index idx_5585b54f85e0677"

**Comment by GawainLynch** [comment] 2016-06-26 07:20
Duplicate of #5110

This is a funky "bug" in DBAL that we are yet to find a way around. The current solution is to manually delete the index, which off the top of my head should be:
```
ALTER TABLE bolt_users DROP INDEX idx_5585b54f85e0677;
```

**Closed by GawainLynch** 2016-06-26 07:20 UTC
Labels: Duplicate

**Comment by dlightme** [comment] 2016-06-27 13:09
Perfect, resolved.
