### ISSUE TITLE
[BUG?] Different names for slug contenttype in 3.3.0 RC1 release

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#6847] opened 2017-07-23 12:36 UTC
I installed 3.3.0 RC1 and I notice that the slug has different names in different contenttypes. For each contenttype I use the same code:

```
slug:
            type: slug
            uses: titel
```

In the edit window one contenttype slug has the name 'Permalink' and the other contenttype slug name is 'Unique alias'.

**Comment by bobdenotter** [comment] 2017-07-23 12:47
Hey @gwbonline, 

I _think_ this is caused by the application/ purpose of the Contenttype. If the contenttype is `viewless: true`, it has a "Unique Alias", because there _is_ no direct link for it. If it's a "normal" contenttype, you will get the "Permalink" label. 

Could you check on your setup if this is the case?

**Comment by gwbonline** [comment] 2017-07-23 12:52
Yes, I can see the difference and I know why now. But I still think it isn't very obvious. Thought it was a bug or some issue with translation.

**Comment by GawainLynch** [comment] 2017-07-25 03:09
Thanks again @gwbonline … You'll see this appear on the docs site soon, once the branches are next merged and deployed.

**Closed** 2017-07-25 03:08 UTC
