### ISSUE TITLE
multiple relations to the same contenttype

### ISSUE THREAD

**Issue by jmschelcher** [bolt/bolt#2534] opened 2015-01-23 16:08 UTC
Hi,

I need to link a content type to another content type but twice. In oder words, I need to make two relations to the same content type.

Example:
- imagine a contenttype "persons"
- imagine another contenttype "discussion_groups"

"discussion_groups" has to be linked twice to "persons":
- one relation to designate a discussion group "chief" (unique)
- one relation to designate its "members" (multiple)

I think this is not yet possible because the relation is names based on the contenttype identifier.
Something like that should be cool:
```yml
persons:
    name: Persons
    singular_name: Person
    fields:
        [..]

discussion_groups:
    name: Discussion Groups
    singular_name: Discussion Group
    fields:
        [...]
    relations:
        chief:
            contenttype: persons
            multiple: false
            label: Select a chief
        members:
            contenttype: persons
            multiple: true
            label: Select members
```

Is something like that planned ?
Many thanks !

Jean-Michel

**Comment by bobdenotter** [comment] 2015-01-23 16:33
Hi @jmschelcher, 

This has been brought up occasionally. Originally we designed the relations to be non-directional, but it turns out to be limiting in some cases. Like the one you describe. 

It's on my list of things to fix, someteime in the near future.. My changes would allow you to have uni-directional relationships, as well as being able to do multiple relationships between two contenttypes.

**Comment by jmschelcher** [comment] 2015-01-23 16:35
Mmmh after watching the code and DB, it will probably need some DB changes.
I understood that the bolt_relations describes all many2many relations (fields: id, from_contenttype, from_id, to_contenttype, to_id).
It would need another field that could be called "relation_name"...

**Comment by jmschelcher** [comment] 2015-01-23 16:37
ok fine, if I can help, don't hesitate :-)

**Comment by bobdenotter** [comment] 2015-01-23 16:38
@jmschelcher Sure! I'll see if i can outline what needs to be done in the upcoming days, and we could split the actual work. :-)

**Comment by spicyroland** [comment] 2015-02-27 23:47
What about one to one relations? For example something like this:
```
category:
    name: Categories
    singular_name: Category
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
    relations:
        category:
          multiple: false
          order: id
          label: Select a parent id
    recordsperpage: 50
    default_status: publish
```
Couldn't get this working neither...

**Comment by ScreamZ** [comment] 2015-11-29 09:52
Any news about that feature ? :)

**Comment by rossriley** [comment] 2016-03-02 10:36
The work for this is now completed and will be available in the 3.x series of releases. 

It will initially be a bit of an unofficial feature since there were problems keeping the new behaviour backwards compatible with the old behaviour of relations, so the new-style behaviour is going to be opt-in via a slightly different configuration option. 

Documentation for this will be showing up at sometime during the beta release period, so closing this issue now.

**Closed by rossriley** 2016-03-02 10:36 UTC
Labels: Enhancement

**Comment by emik** [comment] 2018-08-21 14:59
@rossriley were multiple relations to the same content type ever implemented for v3? I cannot find it in the docs.

**Comment by SvanteRichter** [comment] 2018-09-14 19:44
@emik No, not really.

**Comment by ChangePlaces** [comment] 2020-05-07 18:16
This is sad and a deal-breaker for complicated projects.

**Comment by bobdenotter** [comment] 2020-05-07 18:38
@ChangePlaces You can add multiple "one way relations" by using the `type: select` field: 

https://docs.bolt.cm/3.7/fields/select#populating-the-values-from-a-contenttype

**Comment by ChangePlaces** [comment] 2020-05-07 18:49
@bobdenotter That's interesting, thanks, but if I have a million or so records that's be an unruly select, e.g. related products.

Is there any particular reason why this wasn't implemented? I'd be prepared to help out where possible.

**Comment by bobdenotter** [comment] 2020-05-07 18:53
Because most people don't have a million records. In accordance with [yagni](https://martinfowler.com/bliki/Yagni.html), it never rose to the top of the pile. 

Also, by design, the true relations are non-directional and not ordered. There's no way of implementing "multiples" without breaking the paradigm.

**Comment by ChangePlaces** [comment] 2020-05-07 19:55
True, I understand most people would use bolt to create websites or such. Me? I plan to use it In business as a product information manager. That is, a database of lots of products I sell (or have sold) and they have media, text, lots more text and also relations such as related products, replaced products etc. of course. I plan to pull out certain fields for an app (which is kinda already written) to help within business processes. There're manufacturers and lots more. Some of these products come from wholesalers and suppliers lists. Not quite a million, but a few more than a thousand for sure.

Not having ordered relations I could live with, but couldn't the relationships fields (without looking at middle table schema) have the field name that they're for contained within them which would allow the above.
