### ISSUE TITLE
composer create-project is missing .htaccess file

### ISSUE THREAD

**Issue by bfanger** [bolt/bolt#4061] opened 2015-09-07 10:56 UTC
I ran `composer create-project bolt/composer-install <MYPROJECT> --prefer-dist` chose `y` for a separate folder and `public` for the directory name.

Visiting the site resulted in an error:
"The requested URL /bolt/users/edit/ was not found on this server."

Which was caused by the missing **.htaccess**

**Comment by Pinpickle** [comment] 2015-09-08 10:20
Related issue: #3016

**Comment by melcarthus** [comment] 2015-09-08 15:27
Jup ran in to the same issue, I don't understand bolt / symfony / composer enough yet to fix this. I choose the composer approach for update reasons.

**Comment by MichaelMackus** [comment] 2015-09-10 20:36
Yup same here. I just created the [htaccess file manually](https://docs.bolt.cm/installation#apache-tweaking-htaccess-file) & checked it in, but would be nice to get functional through composer.

**Comment by GawainLynch** [comment] 2015-09-10 20:57
We're totally with everyone here… the problem is that this install target is designed for people who want to have full control —  are very much in control of *what* is delivered — and understand a lot of very specific detail about web server/site configuration… i.e. if you need htaccess files you are already "Doing It Wrong"… that's not a bad thing to us, just not the market that ***this*** install target is intended for.

To a larger audience who fit into the rest of our [manifesto](https://docs.bolt.cm/manifesto) groups, we absolutely want to provide more… It's just a small and very distributed market and nobody has had the time to ***correctly*** complete the work :grin:

**Comment by rossriley** [comment] 2015-09-10 20:57
Just to update, we've been discussing this over on the IRC channel. In principle we're not overly keen on adding `.htaccess` automatically, since we don't really want to provide server specific config in the install. 

Additionally if you are using Apache it's much more preferred to use the Apache config rather that .htaccess. In fact as long as you're on a relatively recent version of Apache all you need to do is add `FallbackResource /index.php` to your config and that should be all you need.

However we'll see if we can either add some advisory docs to the install or maybe have a supplementary question at the end that does the generation if requested.

**Comment by MichaelMackus** [comment] 2015-09-11 17:24
Completely understood. Personally, the only reason I'm using apache for my bolt sites is for the .htaccess support and will likely switch to nginx sometime anyway. It would just be nice to have composer install setup everything in a one step process, but really not a big deal IMO.

**Comment by rarila** [comment] 2015-09-12 09:11
@rossriley Would it be possible to add some switch like ``--htaccess`` to make everyone happy?

**Comment by SahAssar** [comment] 2015-09-30 20:44
Also open in bolt/composer-install/issues/5

**Comment by nlemoine** [comment] 2015-10-08 20:32
I also raised the problem here (last paragraph in About 3): https://github.com/bolt/bolt/issues/3551#issuecomment-111163907

I agree that a specific server conf (nginx or apache) shouldn't be shipped by default with Bolt but providing no information about it is wrong too. I had the same issue when I first installed Bolt with composer, took me some time (not much but still) to dig the docs and find the htaccess snippet to make everything work. 

IMO, displaying a notification with the snippet to configure your webserver on `composer create-project` command should be enough?

**Comment by Pinpickle** [comment] 2015-10-08 21:13
I feel like the approach to this is disparate between different Bolt repos. For example, this repo, [bolt/bolt](http, has a `.htaccess` file and a `web.config`, while the Composer project doesn't.

For what it's worth, I'm all for keeping server config strictly opt-in and not shipping by default. But consistency is rather important here.

Maybe have a folder in this repo (or another repo) for the different config files (nginx example included)

Although that will get in the way of it "just working" for the basic *download a zip file and extract* installation. It may be best to inject the `.htaccess` file into the root of that zip if it is chosen to remove them from the root of this repo.

**Comment by sbani** [comment] 2015-10-29 14:26
> I'm all for keeping server config strictly opt-in and not shipping by default.
:+1:

**Comment by SahAssar** [comment] 2016-01-05 23:16
I'm going to close this one since it's open in bolt/composer-install#5 and I think it only needs one open issue in the org.

**Closed by SahAssar** 2016-01-05 23:16 UTC
Labels: Bolt Library Issue
