### ISSUE TITLE
Unable to use PHP or HTML codesnippets inside markdown field

### ISSUE THREAD

**Issue by znegva** [bolt/bolt#6875] opened 2017-08-03 14:09 UTC
-----------
Its not possible to add HTML or PHP code-snippets through a markdown field. 

Details
-------

 - Relevant Bolt Version: 3.3.1
 - Install type: Zip/tarball install
 - PHP version: 5.6.30
 - Used web server: Apache
 - For UX/UI issues: [ browser name and version ]

Reproduction
------------

1. create contenttype with markdown field
2. add the following content to this field:
```
testing php:
```php
<?php
	phpinfo();
?>
...```

testing html:
```html
<html>
	test
</html>
...```
```
__the dots before ...``` need to be deleted!__ (its not that easy to nest markdown inside markdown :)

3. save the entry
4. on the page this is translated to:
```
<p>testing php:</p>
<pre><code class="language-php"></code></pre>
 <p>testing html:</p>
 <pre><code class="language-html">
 test
 </code></pre>
```
5. also when reopening the entry for editing the markdown field is "garbled" to:
```
testing php:
```php

...```

testing html:
```html

    test

...```
```

6. the same happens when using indentions for code-blocks:
```
testing php:

    <?php
    phpinfo();
    ?>

testing html:

    <html>
    test
    </html>
```

Assumption
----------------
So I think there is some preprocessing before saving an entry to database (probably html cleaner).
This process should ignore code inside of '```' blocks or indented code-blocks.

**Comment by SahAssar** [comment] 2017-08-05 10:13
The htmlcleaner runs on output, not save IIRC, and the correct way to deal with this IMO would be that the markdown editor should escape html chars (<> and so on) inside code blocks...

**Comment by bobdenotter** [comment] 2017-10-09 17:34
This is probably related to #7058

**Comment by bobdenotter** [comment] 2017-10-13 17:38
I'm going to close this one as a duplicate of #7058, even though this one was earlier. The other one got more traction, so we'll target the discussion there. 

@znegva Feel free to comment in the other one, so you'll get future notifications on updates.

**Closed by bobdenotter** 2017-10-13 17:38 UTC
Labels: Feature request
