### ISSUE TITLE
Request: a shareable link to an unpublished newsitem. 

### ISSUE THREAD

**Issue by anketwokings** [bolt/bolt#4077] opened 2015-09-10 15:38 UTC
I would love to have an option to create a (temporary?) link to send a preview of an unpublished item to someone.

Workflow example:
  I type an article
  The article is still unpublished
  I create a link (e.g. mysite.com/preview/f54gfjY)
  I send this link to another editor to preview
  After ok, i publish this.

No biggie, but would be nice in the future. 
Maybe an extension? Thanks in advance!

**Comment by GawainLynch** [comment] 2015-09-10 15:40
Do you perceive that second editor would also have a Bolt account?

**Comment by anketwokings** [comment] 2015-09-10 15:43
Hmmz, good question. Could be a good idea, that would make sense for security reasons. And prevents the unauthorized sharing of this link that is clearly not for publication.

**Comment by bobdenotter** [comment] 2015-09-10 15:47
I have a sneaking suspicion this is a duplicate of a previously reported issue.

**Comment by anketwokings** [comment] 2015-09-10 15:49
Oe, I did search but could not find anything. But if it's a duplicate, please close or mark or whatever it is you can do with is. :)

**Comment by bobdenotter** [comment] 2015-09-10 15:58
Can't find it either.. Maybe it was one of our client who requested it, perhaps? ¯\\\_(ツ)_/¯

**Comment by jadwigo** [comment] 2015-09-10 16:00
we had an extension for this in pivotx that allowed editors to generate a link with a token that allowed clients to see a page before it was published

**Comment by SahAssar** [comment] 2016-01-05 23:05
While suspect this will get peltered with penguins I'm going to close this one. AFAIK it is not a much requested feature and seems like implementing access tokens into bolt would be needlessly complicated for the very few times one needs this.

If I am wrong please feel free to reopen this issue! :)

**Closed by SahAssar** 2016-01-05 23:05 UTC
Labels: Enhancement
