### ISSUE TITLE
File Upload Hangs

### ISSUE THREAD

**Issue by slahav** [bolt/bolt#3903] opened 2015-07-30 16:56 UTC
STR (Steps to reproduce):
====================
1. create a content type with an image type, for example:
```       
    question_image:
            type: image
            label: Question Image
            required: true
            upload: /lessons/assets/images
            extensions: [ gif, jpg, png ]
            info: Please select the question image
```
2. in your form try to upload a file (you will need to make sure the folder structure exists and accessible under the files folder)

Expected Result:
=============
1. The file would upload to files/lessons/assets/images folder.
2. Preview of the file is presented.
Note: If there was an error during the upload process (for whatever reason) it should not be swollen by the app but propagated to the user. 

Actual Result:
===========
1. The UI seems to be hanging (progress bar stays visible).
2. Preview does not come up
3. Looking at the folder mentioned above, both the uploaded file and a .lock file exist.

Additional Information:
=================
Bolt Version 2.2.4 or 2.2.5
OS: OSX (Yosemite) 
Console Log: error displayed - Failed to load resource: the server responded with a status of 500 (Internal Server Error)
Screenshot:
![uploadhangs](https://cloud.githubusercontent.com/assets/1270557/8989436/40c9d854-36ba-11e5-985a-898f08ccc146.png)

**Comment by GawainLynch** [comment] 2015-07-30 16:57
@slahav any chance we could get a cleaned up output of the trace in the server log?

**Comment by slahav** [comment] 2015-07-30 17:10
[2015-07-30 13:10:21] bolt.DEBUG: Initialization of fileoverwriter extension complete. [] []
[2015-07-30 13:10:21] bolt.INFO: Matched route "upload" (parameters: "_controller": "{}", "namespace": "files", "_route": "upload") [] []
[2015-07-30 13:10:21] bolt.INFO: > POST /upload?handler=/lessons/assets/images [] []
[2015-07-30 13:10:21] bolt.DEBUG: Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelRequest". [] []
[2015-07-30 13:10:21] bolt.DEBUG: Notified event "kernel.request" to listener "Silex\Provider\SessionServiceProvider::onEarlyKernelRequest". [] []
[2015-07-30 13:10:21] bolt.DEBUG: Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\FragmentListener::onKernelRequest". [] []
[2015-07-30 13:10:21] bolt.DEBUG: Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest". [] []
[2015-07-30 13:10:21] bolt.DEBUG: Notified event "kernel.request" to listener "Silex\EventListener\LocaleListener::onKernelRequest". [] []
[2015-07-30 13:10:21] bolt.DEBUG: Notified event "kernel.request" to listener "closure". [] []
[2015-07-30 13:10:21] bolt.DEBUG: Notified event "kernel.request" to listener "Silex\EventListener\LogListener::onKernelRequest". [] []
[2015-07-30 13:10:21] bolt.DEBUG: Notified event "kernel.request" to listener "Silex\EventListener\MiddlewareListener::onKernelRequest". [] []
[2015-07-30 13:10:21] bolt.DEBUG: Notified event "kernel.controller" to listener "Silex\EventListener\ConverterListener::onKernelController". [] []
[2015-07-30 13:10:21] bolt.DEBUG: Notified event "kernel.controller" to listener "Symfony\Component\HttpKernel\DataCollector\RequestDataCollector::onKernelController". [] []
[2015-07-30 13:10:21] bolt.CRITICAL: League\Flysystem\FileNotFoundException: File not found at path: corn.jpg (uncaught exception) at /Users/sivan lahav/dev/projects/digit-authoring/vendor/rossriley/flysystem53/src/Filesystem.php line 537 {"exception":"[object] (League\\Flysystem\\FileNotFoundException(code: 0): File not found at path: corn.jpg at /Users/sivan lahav/dev/projects/digit-authoring/vendor/rossriley/flysystem53/src/Filesystem.php:537)"} []
[2015-07-30 13:10:21] bolt.DEBUG: Notified event "kernel.exception" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelException". [] []
[2015-07-30 13:10:21] bolt.DEBUG: Notified event "kernel.exception" to listener "Silex\EventListener\LogListener::onKernelException". [] []
[2015-07-30 13:10:21] bolt.DEBUG: Notified event "kernel.exception" to listener "Silex\ExceptionListenerWrapper::__invoke". [] []
[2015-07-30 13:10:21] bolt.DEBUG: Listener "Silex\ExceptionListenerWrapper::__invoke" stopped propagation of the event "kernel.exception". [] []
[2015-07-30 13:10:21] bolt.DEBUG: Listener "Silex\ExceptionListenerWrapper::__invoke" was not called for event "kernel.exception". [] []
[2015-07-30 13:10:21] bolt.DEBUG: Listener "Silex\ExceptionHandler::onSilexError" was not called for event "kernel.exception". [] []
[2015-07-30 13:10:21] bolt.INFO: < 500 [] []
[2015-07-30 13:10:21] bolt.DEBUG: Notified event "kernel.response" to listener "Silex\EventListener\MiddlewareListener::onKernelResponse". [] []
[2015-07-30 13:10:21] bolt.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ResponseListener::onKernelResponse". [] []
[2015-07-30 13:10:21] bolt.DEBUG: Notified event "kernel.response" to listener "closure". [] []
[2015-07-30 13:10:21] bolt.DEBUG: Notified event "kernel.response" to listener "closure". [] []
[2015-07-30 13:10:21] bolt.DEBUG: Notified event "kernel.response" to listener "Silex\EventListener\LogListener::onKernelResponse". [] []
[2015-07-30 13:10:21] bolt.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\SurrogateListener::onKernelResponse". [] []
[2015-07-30 13:10:21] bolt.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelResponse". [] []
[2015-07-30 13:10:21] bolt.DEBUG: Notified event "kernel.response" to listener "Symfony\Bundle\WebProfilerBundle\EventListener\WebDebugToolbarListener::onKernelResponse". [] []
[2015-07-30 13:10:21] bolt.DEBUG: Notified event "kernel.finish_request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelFinishRequest". [] []
[2015-07-30 13:10:21] bolt.DEBUG: Notified event "kernel.finish_request" to listener "Silex\EventListener\LocaleListener::onKernelFinishRequest". [] []
[2015-07-30 13:10:21] bolt.DEBUG: Notified event "kernel.terminate" to listener "closure". [] []
[2015-07-30 13:10:21] bolt.DEBUG: Notified event "kernel.terminate" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelTerminate". [] []

**Comment by slahav** [comment] 2015-07-30 17:13
@GawainLynch as you can see from the stack trace it seems that in Filesystem.php line 537 it could not find the object to upload, which is strange as i selected it from the mac finder window that was opened by the file upload process.

**Comment by GawainLynch** [comment] 2015-07-30 17:14
This shouldn't matter, but can you try using a location without a space in the directory name(s)?

**Comment by slahav** [comment] 2015-07-30 17:19
@GawainLynch i assume you meant that the location of the file i upload will not be in a path that has spaces. if that is the case, then i tried it --> same result. Do you want the trace for that as well?

**Comment by GawainLynch** [comment] 2015-07-30 17:20
`/Users/sivan lahav/dev/projects/digit-`

**Comment by slahav** [comment] 2015-07-30 17:22
Well, that is going to be a bit more difficult, As a personal note - i hate it, i think its stupid, but that is how our IT sets our macs, to do what you ask i will need to install another bolt instance in a new location and try and reproduce. it will take me a bit more time.

**Comment by veiko** [comment] 2015-07-30 17:29
Here's my error log. The username has no space

[2015-07-30 13:28:38] bolt.DEBUG: Initialization of fileoverwriter extension complete. [] []
[2015-07-30 13:28:38] bolt.INFO: Matched route "upload" (parameters: "_controller": "{}", "namespace": "files", "_route": "upload") [] []
[2015-07-30 13:28:38] bolt.INFO: > POST /clients/ca/digit-authoring/upload?handler=/lessons/assets/images [] []
[2015-07-30 13:28:38] bolt.DEBUG: Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelRequest". [] []
[2015-07-30 13:28:38] bolt.DEBUG: Notified event "kernel.request" to listener "Silex\Provider\SessionServiceProvider::onEarlyKernelRequest". [] []
[2015-07-30 13:28:38] bolt.DEBUG: Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\FragmentListener::onKernelRequest". [] []
[2015-07-30 13:28:38] bolt.DEBUG: Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest". [] []
[2015-07-30 13:28:38] bolt.DEBUG: Notified event "kernel.request" to listener "Silex\EventListener\LocaleListener::onKernelRequest". [] []
[2015-07-30 13:28:38] bolt.DEBUG: Notified event "kernel.request" to listener "closure". [] []
[2015-07-30 13:28:38] bolt.DEBUG: Notified event "kernel.request" to listener "Silex\EventListener\LogListener::onKernelRequest". [] []
[2015-07-30 13:28:38] bolt.DEBUG: Notified event "kernel.request" to listener "Silex\EventListener\MiddlewareListener::onKernelRequest". [] []
[2015-07-30 13:28:38] bolt.DEBUG: Notified event "kernel.controller" to listener "Silex\EventListener\ConverterListener::onKernelController". [] []
[2015-07-30 13:28:38] bolt.DEBUG: Notified event "kernel.controller" to listener "Symfony\Component\HttpKernel\DataCollector\RequestDataCollector::onKernelController". [] []
[2015-07-30 13:28:38] bolt.CRITICAL: League\Flysystem\FileNotFoundException: File not found at path: 20141218_MultipleFileViewer_1.png (uncaught exception) at /Users/veiko/Sites/clients/ca/digit-authoring/vendor/rossriley/flysystem53/src/Filesystem.php line 537 {"exception":"[object] (League\\Flysystem\\FileNotFoundException(code: 0): File not found at path: 20141218_MultipleFileViewer_1.png at /Users/veiko/Sites/clients/ca/digit-authoring/vendor/rossriley/flysystem53/src/Filesystem.php:537)"} []
[2015-07-30 13:28:38] bolt.DEBUG: Notified event "kernel.exception" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelException". [] []
[2015-07-30 13:28:38] bolt.DEBUG: Notified event "kernel.exception" to listener "Silex\EventListener\LogListener::onKernelException". [] []
[2015-07-30 13:28:38] bolt.DEBUG: Notified event "kernel.exception" to listener "Silex\ExceptionListenerWrapper::__invoke". [] []
[2015-07-30 13:28:38] bolt.DEBUG: Listener "Silex\ExceptionListenerWrapper::__invoke" stopped propagation of the event "kernel.exception". [] []
[2015-07-30 13:28:38] bolt.DEBUG: Listener "Silex\ExceptionListenerWrapper::__invoke" was not called for event "kernel.exception". [] []
[2015-07-30 13:28:38] bolt.DEBUG: Listener "Silex\ExceptionHandler::onSilexError" was not called for event "kernel.exception". [] []
[2015-07-30 13:28:38] bolt.INFO: < 500 [] []
[2015-07-30 13:28:38] bolt.DEBUG: Notified event "kernel.response" to listener "Silex\EventListener\MiddlewareListener::onKernelResponse". [] []
[2015-07-30 13:28:38] bolt.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ResponseListener::onKernelResponse". [] []
[2015-07-30 13:28:38] bolt.DEBUG: Notified event "kernel.response" to listener "closure". [] []
[2015-07-30 13:28:38] bolt.DEBUG: Notified event "kernel.response" to listener "closure". [] []
[2015-07-30 13:28:38] bolt.DEBUG: Notified event "kernel.response" to listener "Silex\EventListener\LogListener::onKernelResponse". [] []
[2015-07-30 13:28:38] bolt.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\SurrogateListener::onKernelResponse". [] []
[2015-07-30 13:28:38] bolt.DEBUG: Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelResponse". [] []
[2015-07-30 13:28:38] bolt.DEBUG: Notified event "kernel.response" to listener "Symfony\Bundle\WebProfilerBundle\EventListener\WebDebugToolbarListener::onKernelResponse". [] []
[2015-07-30 13:28:38] bolt.DEBUG: Notified event "kernel.finish_request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelFinishRequest". [] []
[2015-07-30 13:28:38] bolt.DEBUG: Notified event "kernel.finish_request" to listener "Silex\EventListener\LocaleListener::onKernelFinishRequest". [] []
[2015-07-30 13:28:38] bolt.DEBUG: Notified event "kernel.terminate" to listener "closure". [] []
[2015-07-30 13:28:38] bolt.DEBUG: Notified event "kernel.terminate" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelTerminate". [] []

**Comment by GawainLynch** [comment] 2015-07-30 17:30
Thanks @veiko that's really helpful.

**Comment by GawainLynch** [comment] 2015-07-30 17:37
@rossriley any ideas?

**Comment by rossriley** [comment] 2015-07-30 18:10
Yes, it seems that a bug has crept in where the error is no longer reported to the user.

I can reproduce this here where there is no write permission on the parent folder.
The old behaviour was to show an alert with the error, but It seems now that it doesn't happen.

**Comment by slahav** [comment] 2015-07-30 18:39
@rossriley in my case all the folders (starting from files are set with 777):
drwxrwxrwx   5 sivan lahav  NTDOMAIN\Domain Users     170 Jul 28 12:22 files
drwxrwxrwx   3 _www         NTDOMAIN\Domain Users   102 Jul 28 12:21 lessons
drwxrwxrwx  4 _www         NTDOMAIN\Domain Users  136 Jul 28 12:21 assets
✔ ~/dev/projects/digit-authoring/files/lessons/assets [AUP-416_mct2-template-definition|✚ 1…9⚑ 2]
14:36 $ ll
total 0
drwxrwxrwx  4 _www  NTDOMAIN\Domain Users  136 Jul 28 12:21 .
drwxrwxrwx  3 _www  NTDOMAIN\Domain Users  102 Jul 28 12:21 ..
drwxrwxrwx  4 _www  NTDOMAIN\Domain Users  136 Jul 30 12:49 images
drwxrwxrwx  4 _www  NTDOMAIN\Domain Users  136 Jul 28 12:23 vo
✔ ~/dev/projects/digit-authoring/files/lessons/assets [AUP-416_mct2-template-definition|✚ 1…9⚑ 2]

**Comment by slahav** [comment] 2015-07-30 19:02
Another note: This is 100% reproducible for all of our team members (7 Developers & QA)

**Comment by rossriley** [comment] 2015-07-30 22:05
Yes, this one has got me stumped, because whilst I can reproduce the UI failure, the hanging progress bar - this shouldn't happen in a real world situation since the page request checks everything is readable / writable before showing the upload button.

The particular exception that is being thrown is from the method that checks a file is present before doing an update/delete operation and so I'm not really sure why this would be happening on a new upload.

Couple of other questions on your setup...

1. Have you made any changes to the `upload` block in `config.yml` if so what are your settings?
2. Have you got any changes made to anything in the Upload provider, eg: `$app['upload.prefix']` or `$app['upload.overwrite']`
3. If you look at the ajax response in the console to `/upload?handler=xxxx` does the response contain any output? or is it empty.

thanks, and i'll try and get to the bottom of it.

**Comment by slahav** [comment] 2015-07-31 21:27
@rossriley Yes, we have the overwrite feature turned on.
I have turned it off to see if that might be the source of the problem and after doing that it seems to work fine. So i think the overwrite has something to do with it.
The response includes:
```
/upload?handler=/lessons/assets/images
```

```
{"error":{"type":"League\\Flysystem\\FileNotFoundException","message":"File not found at path: Sully-Monsters-University-3.jpg","file":"\/Users\/sivan lahav\/dev\/projects\/digit-authoring\/vendor\/rossriley\/flysystem53\/src\/Filesystem.php","line":537}}
```

**Comment by mhodges-cainc** [comment] 2015-08-10 14:16
Morning/Afternoon,

Has there been any progress on what could be causing this issue? It is still impacting our team. 

Thanks,
Matt

**Comment by rossriley** [comment] 2015-08-12 07:24
I am having trouble getting the problem to reproduce here, I'll run you through the steps and see if anyone can spot anything missing.

1: Installed Bolt 2.2.5
2: Created this field in contenttypes:
```
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
        image:
            type: image
            upload: /lessons/assets/images
            required: true
            extensions: [ gif, jpg, png ]
```
3: In Upload.php set: `$app['upload.overwrite'] = true;`
4: Set the permissions for the server to write on `public/files/lessons/assets/images`
5: Go to create a new page and upload, both a new and overwriting image:

Either way I get this response in the console:

![Screenshot](https://www.dropbox.com/s/pw6lv343ftos299/Screenshot%202015-08-12%2008.16.05.png?raw=1)

Can you spot any other setup changes that you guys do that might have an impact?

Alternatively, what I'm really interested in, in getting this to reproduce, is to see the stack trace of where the exception happens as that will at least mean we can see the stack of how the error gets thrown. Adding something like: `var_dump(debug_backtrace());` to the point where the exception is thrown might give us some more useful information.

The source is this method in Filesystem.php

    public function assertPresent($path)
    {
        if (! $this->has($path)) {
            throw new FileNotFoundException($path);
        }
    }

So changing to:

    public function assertPresent($path)
    {
        if (! $this->has($path)) {
            var_dump(debug_backtrace()); exit;
            throw new FileNotFoundException($path);
        }
    }

may give us some more useful information.

**Comment by GawainLynch** [comment] 2015-08-12 07:40
Another option if you're debugging AJAX code in Bolt is to use FirePHP… I only use [FirePHP for Chrome](https://chrome.google.com/webstore/detail/firephp-for-chrome/goajlbdffkligccnfgibeilhdnnpaead) myself and find it quite useful:

```php
public function assertPresent($path)
{
    if (! $this->has($path)) {
        $app['logger.firebug']->info('Backtrace', debug_backtrace());
        exit;
        throw new FileNotFoundException($path);
    }
}
```
Will give you output similar to this in your developer console:
![firephp dump](https://cloud.githubusercontent.com/assets/1427081/9218820/bc379ec8-40cd-11e5-8031-8816e85fb77e.png)

**Comment by mhodges-cainc** [comment] 2015-08-12 19:30
Good Afternoon,

The team discovered that this was due to an internal extension, which has been addressed. 

I wanted to make sure you didn't spend any additional time trying to reproduce. Thanks for digging into it on your end!

Thanks,
Matt

**Comment by GawainLynch** [comment] 2015-08-12 19:43
Excellent guys… I'll close this but as always, fell free to ping us if there are further problems.

**Closed by GawainLynch** 2015-08-12 19:43 UTC
Labels: Bug
