### ISSUE TITLE
Sidebar menu clicks not following links before popover animation is finished

### ISSUE THREAD

**Issue by xiaohutai** [bolt/bolt#3513] opened 2015-05-12 09:22 UTC
Commit 369a9c90fb68cef282e6c6b7bef8150e69301bba breaks a minor thing I noticed in the Bolt 2.2.0-beta releases. If you hover a menu item, and want to click a different menu item before the popover is done with the animation, the click does nothing.

Same thing happens if you try to click a menu item really fast.

**Comment by bobdenotter** [comment] 2015-05-25 15:42
Ah, now i get it.. This is really annoying.. @rarila Any idea how to fix this?

**Comment by rarila** [comment] 2015-05-25 18:21
Not really as it is by design: #3433
So either the fast people complain or the mobile people.
@bobdenotter Any idea how to fix this? ;-)

**Comment by rarila** [comment] 2015-05-25 18:31
Probably, just an idea, don't know if this is feasible, How about if we register via ``mouseEnter`` the menu item the mouse is over and unregister it ``mouseLeave``. Then on ``click`` we could check if the clicked menu is mouseovered it is desktop, if not it must be mobile?! (Assuming on touch there is no mouseover)

**Comment by bobdenotter** [comment] 2015-05-25 20:12
So, if I get it correctly, it is the _delay_ that's causing this? If so, let's try tweaking that to make it behave better. Or, at least, more how the user would expect..

**Comment by bobdenotter** [comment] 2015-05-27 17:31
Left this open on purpose: I hackishly tweaked it for 2.2 to make it less annoying. Rarila has an idea on how to fix it properly.

**Comment by SahAssar** [comment] 2015-09-30 06:27
Assigned to @rarila since bopp said you had a fix in mind ;)

**Comment by rarila** [comment] 2015-09-30 07:15
@SahAssar But it seems it doesn't find out! :smile:

**Comment by GawainLynch** [comment] 2016-03-06 13:15
@bobdenotter, @SahAssar & @rarila, any of you have thoughts on this? 

Scheduling for close on 01/04/2016

**Comment by bobdenotter** [comment] 2016-03-06 13:44
IMHO, not a priority for now. Plz to be closing. :-)

**Closed** 2016-03-06 13:48 UTC
Labels: Bug, JavaScript
