### ISSUE TITLE
saving user record after successful login kills the system

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#4542] opened 2015-11-28 16:38 UTC
v2.3a6
Not sure exactly what was that. Sequence was: updated to v 2.3a6. Tried to log in, get the error. 
![kfvyd70](https://cloud.githubusercontent.com/assets/2145313/11452863/22bf2c36-9620-11e5-84dc-f19fa74f68c3.png)

![6c9se7m](https://cloud.githubusercontent.com/assets/2145313/11452865/2569d256-9620-11e5-8d02-7e4c0701cd45.png)

I suppose it couldn't save user record after db change and successful update, but you know better)

This helped for me this time: 
![fdzfqon](https://cloud.githubusercontent.com/assets/2145313/11452870/47f2b568-9620-11e5-8fb7-aab961d73337.png)
then i updated database and deleted `try/catch` wrap. Now it's ok.

**Comment by GawainLynch** [comment] 2015-11-28 19:07
You either have an modified version of Bolt or you have not done an database update as that field has allowed and defaulted to NULL for months now.

**Comment by Boorj** [comment] 2015-11-29 09:04
indeed, as i said, i haven't update base for a while. but i couldn't login to update.

**Comment by SahAssar** [comment] 2015-12-01 21:42
@Boorj Closing since this seems to be an issue that stems from you having an old install (of an alpha at that)... If it happens on a fresh, new install please reopen! :)

**Comment by Boorj** [comment] 2016-02-04 18:23
#### Fatal error when updating from old version database (v3)

I was trying to login, when i was updating old sqlite db to the new one.
It had a problem with `stack` field of user entity:
![2016-02-05 00-15-09](https://cloud.githubusercontent.com/assets/2145313/12824903/bd1803cc-cb9d-11e5-9688-1e561228efb4.png)

**Comment by bobdenotter** [comment] 2016-02-04 18:24
Reopening, needs further investigation.

**Comment by Boorj** [comment] 2016-02-04 18:26
## ಠ_ಠ
I see no chance to update the system if you're not logged in. I have to comment checks in core, login, update db, and then uncomment code.

**Comment by Boorj** [comment] 2016-02-04 18:33
btw, it also shows **incorrect login attempt** as *last seen* on Users & permissons page. Is it correct?

**Comment by GawainLynch** [comment] 2016-02-07 09:31
@bobdenotter have you got a reproducible test case for me?

**Comment by Boorj** [comment] 2016-02-08 04:55
I suppose, that was when system was new and database was old. And during logging in, system was saving `failed attempts` or `last login date` or whatever, and had something wrong with **stack** variable.

**Comment by bobdenotter** [comment] 2016-03-08 19:51
Pretty sure this has been fixed in the meantime.. Can't reproduce anymore.

**Closed by bobdenotter** 2016-03-08 19:51 UTC
