### ISSUE TITLE
[BUG] getContent directives not clearing on subsequent queries

### ISSUE THREAD

**Issue by graham73may** [bolt/bolt#6057] opened 2016-11-17 08:50 UTC
We've identified a bug with getContent, where if you use a directive in one query, the directive is then not cleared when running another query further along in the file:

```
$result1 = $app['query']->getContent('research/1');

$result2 = $app['query']->getContent('news', ['tags' => 'a || b || c']);
```

`$result1` returns the correct result but `$result2` still has the `1` identifier defined so returns null because when looking at the SQL output it still searches for `research.id = 1`.

This happens with all directives including `returnsingle` which defines a limit on all future results to 1 unless overridden further down.

**Comment by SahAssar** [comment] 2016-11-17 20:46
Closing as a duplicate of #5391, please reopen if I'm wrong :)

**Closed by SahAssar** 2016-11-17 20:46 UTC
