### ISSUE TITLE
Upload fields with option: upload break if indicated path does not exist

### ISSUE THREAD

**Issue by cooperaj** [bolt/bolt#3081] opened 2015-03-10 14:39 UTC
I have some filelists, imagelists and images that have the "upload: <path>" option set. I have found that on upgrade to 2.1 these content types break for editing (either creation of new, or editing current) if the path given to the option does not exist.

![Image of error](https://www.dropbox.com/s/scebg8aq9yxrlbm/Screenshot%202015-03-10%2014.26.04.png?dl=1)

I have worked around the issue by manually creating the folders in question. In the case of the screenshot above the option was set to "upload: images/parts"

**Comment by rossriley** [comment] 2015-03-15 12:04
Duplicate of #3122

**Closed by rossriley** 2015-03-15 12:04 UTC
