### ISSUE TITLE
[BUG] sqLite DB is flushed, if Database not found

### ISSUE THREAD

**Issue by xstable** [bolt/bolt#5332] opened 2016-05-17 10:12 UTC
Bolt 3.0.0
ZIP-Install
Apache / PHP 7.0.4
Chrome (Linux) Version 50.0.2661.102 (64-bit)

Reproduction
------------

If you have a running BOLT 3.0.0 Webpage which use SQLite.

1. Rename /app/database to /app/database_old
1. Browse to your webpage. Because of the missing Database, you got the installscreen "userfirst"-Page.
1. Rename /app/database_old back to /app/database
1. Refresh the Page.
1. Now the used Database is fully flushed (only structure still exist in the database)

![screenshot_003_20160517](https://cloud.githubusercontent.com/assets/1778068/15318915/97a321e0-1c28-11e6-866e-720685c2c173.jpg)

**Comment by GawainLynch** [comment] 2016-05-17 10:21
I just tried this here and did not get the same result… are you sure you don't have something else running (backup script etc) that might cause this?

**Comment by bobdenotter** [comment] 2016-05-17 11:12
I have tried to reproduce this as well, but I couldn't get it to break either.

**Comment by xstable** [comment] 2016-05-17 11:55
I have nothing else run.
Did you have refresh the FE-Page twice? 
First after rename to got the userfirst-page, _and_ second time after rename back to working structure?
Strange that you've got different results as I got.

**Comment by GawainLynch** [comment] 2016-05-17 11:59
I did multiple refreshes on mine… I'll try again later and see if I can get it to trigger

**Comment by bobdenotter** [comment] 2016-05-17 12:14
I've made a short screencast.. Seems to work fine to me, so far.

http://recordit.co/RL5YgL5wQs

**Comment by SahAssar** [comment] 2016-06-21 21:58
Couldn't break it either. Sorry, but since this has been open for a month and we haven't been able to repro it seems appropriate to close this for now. If you have a way to reliably reproduce please reopen, but until then we probably won't be able to debug it.

**Closed by SahAssar** 2016-06-21 21:58 UTC
Labels: Bug verification needed
