### ISSUE TITLE
[BUG] Relationships with Multiple: True not displaying in editor correctly

### ISSUE THREAD

**Issue by Jovinsson** [bolt/bolt#5541] opened 2016-07-14 20:45 UTC
Details
-------

 - Relevant Bolt Version: 3.0.9
 - Install type: Zip/tarball install
 - PHP version: 5.5.35
 - Used webserver: Apache (XAMPP 5.5.35)
 - Host OS: Windows Server 2012

Reproduction
------------

**Bug Summary**
Contenttypes with relations that have the property of `multiple: true` do not correctly show the multiple records when viewing it after saving, instead, they only show 1 related record.

The relationships are still stored but not shown. When I go to the front end of the CMS (user side) it shows the related records correctly as per my .twig structure. It seems it is only impacting the "Relationships" tab of the editing screen.

**Steps to Reproduce**
1. Create multiple contenttypes with a relation to each other and have the `multiple: true` property set
2. Relate more than two records of a single contenttype to another and save the record
3. Refresh the page
4. View the relations again to find only 1 related record is shown per contenttype

**Expected Result**
It should show all related records for each contenttype.

**Actual Result**
Only a single record is displayed.

**Screenshots**
Note: I have removed the names of the records in paint for privacy reasons
 1. I have selected all related records ('Sites') and clicked save
![before saving](https://cloud.githubusercontent.com/assets/5206571/16855150/a586c392-4a46-11e6-806d-31599e069a7d.PNG)
 2. I have refreshed and can only see one record listed
![after saving and refreshing](https://cloud.githubusercontent.com/assets/5206571/16855151/a587db74-4a46-11e6-91e4-1894b89734da.PNG)

Please advise if any further information is required!

**Comment by Jovinsson** [comment] 2016-07-24 20:35
Any ideas?

**Comment by GawainLynch** [comment] 2016-07-24 20:58
Potentially just a case of real life overload hitting everyone's time. Currently triaging for 3.1 so let's see if we can reproduce and fix for that, or tag it for further look :smile:

**Comment by Jovinsson** [comment] 2016-07-24 20:59
Figured your team would be onto it! Thanks @GawainLynch

**Comment by GawainLynch** [comment] 2016-08-04 07:00
OK, just tried on 3.0.11 and 3.1-dev and I can't reproduce this on either, I don't suppose you have a dev install you could try 3.0.11 on do you?

**Comment by SahAssar** [comment] 2016-08-05 08:20
@Jovinsson Do you perhaps have an incoming relation from another record to that record? Or another outbound relation from it? I'm tinkering with bidirectional relations right now, and there seems to have been some bugs about relations affecting each other in odd ways.

**Comment by Jovinsson** [comment] 2016-08-05 08:25
@GawainLynch & @SahAssar - I'm not in the office but will check tomorrow when I'm back in. I've not updated as yet but will try that tomorrow. 

Relationally those records can be related to multiple of each type (Technology >--< Templates) (not referring to twigs). I'll check all relations as well

**Comment by GawainLynch** [comment] 2016-08-06 08:23
Fixed in #5641

**Closed by GawainLynch** 2016-08-06 08:23 UTC
