### ISSUE TITLE
[2.2.14] Error while previewing a non-published content.

### ISSUE THREAD

**Issue by pygillier** [bolt/bolt#4569] opened 2015-12-08 14:23 UTC
Tested on Bolt 2.2.14 

Steps to reproduce : 

create a new entry and save it with a status different from 'published'. After saving try to preview it. The following error occurs : 

`Call to a member function setFromPost() on a non-object`

After digging in source, it seems the method `Storage::decodeContentQuery` returns a array containing a where condition with 'status=published' inside. So, when Bolt requests DB, no content is returned and the exception is raised.

**Comment by cullyn** [comment] 2015-12-11 17:30
I have the same issue, slightly different error message.

PHP Fatal Error: Bolt Generic

Error: Call to a member function setFromPost() on boolean
File: src/Controllers/Frontend.php
Line: 182

Identical  steps to reproduce as above.

**Comment by bobdenotter** [comment] 2015-12-12 11:35
I can't reproduce this yet.. Made a short video: http://recordit.co/QklsQQx0Ku

Do you have more details on what you're doing exactly? 

 - Any modifications to `contenttypes.yml` or `routing.yml`? 
 - Mysql / sqlite? 
 - browser? 
 - server?
 - PHP version?

**Comment by pygillier** [comment] 2015-12-12 14:50
Hi, 

here is the screencast of the error on my live setup : http://recordit.co/KQHdWws6KL

On requested details: 

* No modifications to "entry" content-type, just changed singular_name to french one (did it before translation updates), routing changed to remove "entry" part in route. Was fully working in 2.2.10 (forgot a few updates)
* Mysql 
* Done on Firefox 42.0 on Win7
* Apache with PHP-FPM 5.5.9

I reproduce it on a codeanywhere box with almost same setup (PHP 5.5.9 as a module)

**Comment by cullyn** [comment] 2015-12-13 03:38
If I preview it before I save it no crash, but once you save it crashes.

Only modification was setting entries to hold on publishing.
firefox and chrome win 7
Apache: 2.4.16
PHP:      5.6.15
MySQL:  5.6.27

http://culcraft.com/news/files/output-02-.mp4

**Comment by SahAssar** [comment] 2015-12-13 08:53
I was able to recreate this, only to realize that this was fixed in #4544, which will be in the next 2.2 release. Closing, since fixed. :smile:

**Closed by SahAssar** 2015-12-13 08:53 UTC
Labels: Bug verification needed

**Comment by pygillier** [comment] 2015-12-13 09:28
Good news !
One last thing : is there a test on this issue ?

**Comment by GawainLynch** [comment] 2015-12-13 09:31
> One last thing : is there a test on this issue ?

No yet… but all this is changing in v3.x… but PRs always welcome!
