### ISSUE TITLE
[BUG] - setcontent does a wrong inference when using singular content type slug

### ISSUE THREAD

**Issue by dadaxr** [bolt/bolt#5067] opened 2016-03-21 19:07 UTC
Given Using : 
`{% setcontent banner = 'slider' where { status: 'published' } %}`
return an array of sliders... However "slider' is the singular slug of the "sliders" content type.

```
sliders:
    name: Sliders
    slug: sliders
    singular_name: slider
    singular_slug: slider
    fields: ....

```

while according to the [documentation](https://docs.bolt.cm/content-fetching#one-record-or-multiple-records) : 

> Bolt tries to make an assumption about how you want to use it, based on what you’re requesting. By default, an array is returned, unless one of the following is the case:
> ...
> {% setcontent foo = 'page' where { .. } %}: If ‘page’ is the singular slug of the contenttype ‘pages’, Bolt assumes you only need one.
> ...

when i use the "returnsingle" meta :
`{% setcontent banner = 'slider' where { status: 'published' } returnsingle %}`
I get only one result, as expected.

It seems the bug is in the Storage.php within the parseTextQuery method.

I think we should add a check wether the singular or the plural form of the content type is used... and assume the user knows what is he doing :)
- Relevant Bolt Version: [ 2.2.17 ]

**Comment by SahAssar** [comment] 2016-03-21 19:08
I think this is a combination of idealistic docs and a duplicate of #3914

**Comment by dadaxr** [comment] 2016-03-21 19:23
Not really duplicate of #3914 but indeed the similar code base is responsible of those 2 different bugs :)

**Comment by bobdenotter** [comment] 2016-03-22 16:54
I did some quick checks, and for Bolt3 it's at least consistent: 

```
    {% setcontent banner = 'slider' where { status: 'published' } %}
    {{ dump(banner) }}

    {% setcontent page = 'page' where { status: 'published' } %}
    {{ dump(page) }}
```

![screen shot 2016-03-22 at 17 51 20](https://cloud.githubusercontent.com/assets/1833361/13959995/b6646c22-f056-11e5-9595-1349d63ac474.png)


> I think we should add a check wether the singular or the plural form of the content type is used... and assume the user knows what is he doing :)

While _I_ would like that, lately the tendency has been to move towards "less magic" in the way Bolt does stuff. I think we should make the behaviour as it is in Bolt 3 "official", and update the docs accordingly.

**Comment by dadaxr** [comment] 2016-03-22 18:11
Looks fine to me, just wanted to reflect the documentation, but it's also fine to update the doc to reflect the code :v:

**Comment by bobdenotter** [comment] 2016-03-23 12:54
Ping @GawainLynch @rossriley @CarsonF 

Should we fix the code to match the documentation, or match the docs to the current implementation: 

> {% setcontent foo = 'page' where { .. } %}: If 'page' is the singular slug of the contenttype 'pages', Bolt assumes you only need one.

**Comment by rossriley** [comment] 2016-03-23 14:22
I must say i quite like the singular slug -> single record syntax although I guess it could cause some head scratcher moments in edge cases, especially when I use Bolt to manage my farming inventory and need to find sheep or fish ;-)

**Comment by GawainLynch** [comment] 2016-03-23 14:25
> especially when I use Bolt to manage my farming inventory and need to find sheep or fish ;-)

c.f. #823 :laughing:

**Comment by bobdenotter** [comment] 2016-03-23 14:29
The edgecases can be documented, though: 

> {% setcontent foo = 'page' where { .. } %}: If 'page' is the singular slug of the contenttype 'pages', Bolt assumes you only need one. Note: this will require the singular slug to differ from the plural version, so don't use this to retrieve one sheep or one scissors.

:scissors: :sheep: :fish: :water_buffalo: :dollar: :notes:

**Comment by CarsonF** [comment] 2016-03-24 04:45
When referring to a `content type` doesn't bolt generally try to "help" the user by accepting any of the singular/plural slug/name? It would be a bit WTF if _here_ it made the distinction.

Ross told me a while back that methods should always return type and I agree with him. 
What if we had two different tags for single item and multiple items?
```twig
{% setcontent item = 'meal' where { id: 1 } %}
{% setcontents items = 'meals' %}
```
I'm not sure `setcontents` is the best name, but you get the idea. It would be less verbose than `returnsingle` as well.

Thoughts on this?

Obviously this isn't for 3.0 though, so I would update the docs.

**Comment by GawainLynch** [comment] 2016-03-24 06:37
> Obviously this isn't for 3.0 though, so I would update the docs.

No, but as per a private discussion I just had with @CarsonF, it would be an idea to two two **new** commands, and maintain/deprecate `setcontent` (targeting Bolt v5 maybe).

**Comment by jadwigo** [comment] 2016-03-24 11:00
how about `{% setone thing = 'pages/1' %}` and `{% setmultiple things = 'pages/10' %}`
and let setcontent be backwards compatible.
`{% setcontent pages = 'pages' %}`

**Comment by SahAssar** [comment] 2017-02-25 12:48
It's fixed in the docs, it does not look like anyone is working on this ATM, and it's not really a (at least serious) bug, so I'm closing for now. Please reopen if it needs more discussion before implementation or if anyone is actively working on it! :)

**Closed by SahAssar** 2017-02-25 12:48 UTC
Labels: RFC

**Comment by martijneken** [comment] 2017-11-13 04:02
The existing functionality is very confusing, because it's really hard to distinguish 0, 1, and N results. In Bolt 3, what's the best way to check that the results are not empty? (e.g. to render a header before the data)

All of the following are false for a single Content item:
- {% if data is not empty %}
- {% if data is not null %}
- {% if data|length > 0 %}

In Bolt 3, the only workaround I've found is this conversion to an array:
{% if data.id %}{% set data = [data] %}{% endif %}

In Bolt 2, my workaround was this similar conversion:
{% if data|length == 1 %}{% set data = [data] %}{% endif %}

**Comment by bobdenotter** [comment] 2017-11-13 07:01
@martijneken 

Which version of Bolt are you using? In Bolt 3.3.6 the easiest way to do this is simply: 

```
        {% setcontent data = "pages" where {'id': '1' } returnsingle %}

        {% if data %}
            Yes
            {{ dump(data) }}
        {% else %}
            No
        {% endif %}
```

**Comment by martijneken** [comment] 2017-11-13 13:28
Thanks. I'm on 3.3.6. I have the inverse problem. I want the behavior of iterating multiple records (always want an array), and I need a null/empty check before the iteration.

The documentation says "By default, an array is returned":
https://docs.bolt.cm/2.2/templates/content-fetching#one-record-or-multiple-records

I'm following the pattern described here, querying items by ID (for limit, orderby):
https://docs.bolt.cm/2.2/content/relationships#relations-in-templates
{% set ids = record.relation.news|join(" || ") %}
{% setcontent messages = "news" where { id: ids } limit 5 %}

When there's one ID, I do not get an array back. I get a Content item. None of the empty checks above work on a single item, hence my item -> array conversion hack.

**Comment by SahAssar** [comment] 2017-11-17 19:45
@martijneken does this work for your use-case?

```
{% for item in messages is iterable ? messages : [messages] %}
```

I know it's a hack, but in the meanwhile it might do the trick.
