### ISSUE TITLE
Post-3.6.6 upgrade: js error in /bolt/files 

### ISSUE THREAD

**Issue by doertedev** [bolt/bolt#7765] opened 2019-04-01 10:14 UTC
Flawlessly the site was upgraded from 3.4 to 3.6.6 recently. Ever since the backend shows a JS error in the files management section and doesn't allow uploading of files. When working on an entry of a content type, files can be uploaded properly - and they'll be put in YYYY-MM directory as defined in the default behavior. Enabling the debug log sadly didn't give me any clue. All that is logged when reloading the page is that the session cookie is renewed (`Generating authentication cookie — User ID: '1' Salt...`).

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 3.6.6
| Install type                   | Composer install 
| BC Break                     | what is that?
| PHP version                 | 7.0.33-0ubuntu0.16.04.3
| Web server                  | Apache, version 2.4.18-2ubuntu3.8
| For UX/UI issues        | Chrome, MacOS, v. 73.0.3683.86

AppCFG:
```yaml
database:
    driver: mysql
    databasename: xxx
    username: xxx
    password: xxx
sitename: A sample site
payoff: The amazing payoff goes here
theme: xxx
locale: de_DE
timezone: Europe/Berlin
maintenance_mode: false
maintenance_template: maintenance_default.twig
cron_hour: 3
favicon: ./favicon.ico
homepage: /
homepage_template: index.twig
add_jquery: false
recordsperpage: 10
caching:
    config: true
    templates: true
    request: false
    duration: 120
    authenticated: false
    thumbnails: true
    translations: true
changelog:
    enabled: false
thumbnails:
    default_thumbnail: [ 160, 120 ]
    default_image: [ 1000, 750 ]
    quality: 80
    cropping: crop
    notfound_image: view/img/default_notfound.png
    error_image: view/img/default_error.png
    save_files: true
    allow_upscale: false
    exif_orientation: true
    only_aliases: false
htmlcleaner:
    allowed_tags: [ div, span, p, br, hr, s, u, strong, em, i, b, li, ul, ol, mark, blockquote, pre, code, tt, h1, h2, h3, h4, h5, h6, dd, dl, dh, table, tbody, thead, tfoot, th, td, tr, a, img, address, abbr, iframe, caption ]
    allowed_attributes: [ id, class, style, name, value, href, src, alt, title, width, height, frameborder, allowfullscreen, scrolling, target, colspan, rowspan ]
accept_file_types: [ twig, gif, jpg, jpeg, png, pdf, epub, svg, json]
debug: false
debug_show_loggedoff: false
debug_permission_audit_mode: false
debug_error_level: 8181           
debug_error_use_symfony: false      
production_error_level: 8181 
debuglog:
    enabled: false
    filename: bolt-debug.log
    level: DEBUG
strict_variables: false
wysiwyg:
    images: true            
    anchor: false            
    tables: false            
    fontcolor: true          
    align: false             
    subsuper: false          
    embed: false             
    underline: false         
    ruler: false             
    strike: false            
    blockquote: false        
    codesnippet: false       
    specialchar: false       
    ck:
        autoParagraph: true  
        disableNativeSpellChecker: true 
        allowNbsp: false
google_api_key: "xxx"
liveeditor: false
mailoptions:
    transport: mail
    spool: false
cookies_use_remoteaddr: false
cookies_use_browseragent: false
cookies_use_httphost: false
cookies_lifetime: 1209600
cookies_domain: ".xxx.com"
hash_strength: 10
enforce_ssl: true
```

![image](https://user-images.githubusercontent.com/1579335/55320263-f7b1a780-5476-11e9-8588-7eda641c1260.png)

**Comment by bobdenotter** [comment] 2019-04-01 15:19
Can't reproduce this yet.. Can you reproduce on a fresh installation?

**Comment by doertedev** [comment] 2019-04-01 17:33
I just installed 3.4.x via Composer and have exactly the same problem.

These debug messages showed up in the log, hoping that they give a hint to what's wrong:

	[2019-04-01 19:29:45] bolt.INFO: The Twig\Template class implements Twig_TemplateInterface that is deprecated since 1.12 (to be removed in 3.0) {"type":16384,"file":"/var/www/html/vendor/symfony/debug/DebugClassLoader.php","line":238,"level":28928,"stack":[{"function":"handleError","class":"Symfony\\Component\\Debug\\ErrorHandler","type":"->"},{"file":"/var/www/html/vendor/symfony/debug/DebugClassLoader.php","line":238,"function":"trigger_error"},{"function":"loadClass","class":"Symfony\\Component\\Debug\\DebugClassLoader","type":"->"},{"file":"/var/www/html/app/cache/development/twig/fd6cfe710c30f5d08f4d222f03be543e/74/7468b45a32dbdf51d7158b783214429a428f83e5a7e99f73c726133d601f4460.php","line":15,"function":"spl_autoload_call"},{"file":"/var/www/html/vendor/twig/twig/src/Cache/FilesystemCache.php","line":46,"args":["/var/www/html/app/cache/development/twig/fd6cfe710c30f5d08f4d222f03be543e/74/7468b45a32dbdf51d7158b783214429a428f83e5a7e99f73c726133d601f4460.php"],"function":"include_once"},{"file":"/var/www/html/vendor/twig/twig/src/Environment.php","line":471,"function":"load","class":"Twig\\Cache\\FilesystemCache","type":"->"},{"file":"/var/www/html/vendor/twig/twig/src/Environment.php","line":446,"function":"loadClass","class":"Twig\\Environment","type":"->"},{"file":"/var/www/html/vendor/twig/twig/src/Environment.php","line":424,"function":"loadTemplate","class":"Twig\\Environment","type":"->"},{"file":"/var/www/html/vendor/twig/twig/src/Environment.php","line":385,"function":"load","class":"Twig\\Environment","type":"->"},{"file":"/var/www/html/vendor/symfony/web-profiler-bundle/Controller/ProfilerController.php","line":213,"function":"render","class":"Twig\\Environment","type":"->"},{"file":"/var/www/html/vendor/symfony/http-kernel/HttpKernel.php","line":135,"function":"toolbarAction","class":"Symfony\\Bundle\\WebProfilerBundle\\Controller\\ProfilerController","type":"->"},{"file":"/var/www/html/vendor/symfony/http-kernel/HttpKernel.php","line":57,"function":"handleRaw","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->"},{"file":"/var/www/html/vendor/silex/silex/src/Silex/Application.php","line":586,"function":"handle","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->"},{"file":"/var/www/html/vendor/silex/silex/src/Silex/Application.php","line":563,"function":"handle","class":"Silex\\Application","type":"->"},{"file":"/var/www/html/vendor/bolt/bolt/src/Application.php","line":97,"function":"run","class":"Silex\\Application","type":"->"},{"file":"/var/www/html/public/index.php","line":12,"function":"run","class":"Bolt\\Application","type":"->"}]} []


	[2019-04-01 19:29:44] bolt.INFO: The "Webmozart\Assert\Assert::isTraversable" assertion is deprecated. You should stop using it, as it will soon be removed in 2.0 version. Use "isIterable" or "isInstanceOf" instead. {"type":16384,"file":"/var/www/html/vendor/webmozart/assert/src/Assert.php","line":330,"level":28928} []

^^ best guess these show up now in the vm instead of prod: on prod I didn't enable the debugbar.

Furthermore I think this info Icon should show a user which types are allowed, innit? 
![image](https://user-images.githubusercontent.com/1579335/55348741-3156d280-54b8-11e9-9fe6-cfa4cb1d7cde.png)

Digging deeper: thrown a debugger; in front of https://github.com/bolt/bolt/blob/3.6/app/src/js/modules/filemanager.js#L151 -> turns out that this shouldn't even be "join"able. I couldn't spot any code that uses this that isn't at least one year old. WTF?

![image](https://user-images.githubusercontent.com/1579335/55350203-ceffd100-54bb-11e9-835d-8b7d44cc46d4.png)

**Comment by doertedev** [comment] 2019-04-01 18:30
Quickfix: wrapping in Object.values(): 
![image](https://user-images.githubusercontent.com/1579335/55350666-e7bcb680-54bc-11e9-946a-9398905b2add.png)

Also this looks wrong: case insensitive unique maybe? 
![image](https://user-images.githubusercontent.com/1579335/55351403-8990d300-54be-11e9-90c2-81d8256b2aae.png)

**Comment by mikiolsz** [comment] 2019-04-03 09:26
I can confirm it happens on a clean installation (php 7.2, apache 2.4.29 on ubuntu 18.04) and also can confirm that the workaround works, file to edit is `bolt/public/bolt-public/js/bolt.js` (around column 36540) in an installed Bolt, and apparently https://github.com/bolt/bolt/blob/7b9aa6ac570c6744fe2264e790fe5343d5912429/app/src/js/modules/filemanager.js#L155 here in the sources

**Comment by bobdenotter** [comment] 2019-04-03 15:42
Thanks for the report.. For a quick fix, edit `vendor/bolt/bolt/Config.php, around line 312: 

```php
            $general['accept_file_types'] = array_values(
                array_unique(
                    array_merge(
                        $general['accept_file_types'],
                        array_map(function ($extension) {
                            return strtolower($extension);
                        }, $general['accept_file_types']),
                        array_map(function ($extension) {
                            return strtoupper($extension);
                        }, $general['accept_file_types'])
                    )
                )
            );
```

**Comment by Spomsoree** [comment] 2019-04-10 16:09
This quick fix does not work for me.

I also don't understand how this should fix the js error. The error is thrown because you can't join an object, right?
How can this be fixed without @doertedev 's suggestion?

I've also installed the fix-branch, which didn't fix this error for me.

**Closed as completed** 2019-04-11 12:55 UTC
