### ISSUE TITLE
Newly created bolt/passwordlib package breaks compatibility with PasswordLibFactory

### ISSUE THREAD

**Issue by taakberg** [bolt/bolt#7684] opened 2018-10-03 07:39 UTC
Bolt uses the passwordlib/passwordlib library to hash passwords. Since there is no stable-tagged version of this library, the bolt/passwordlib library was created. This replaces the former, but with a stable tag.

Since the bolt/bolt package requires `passwordlib/passwordlib ^1.0@beta`, the `passwordlib/passwordlib 1.0.0-beta1` package used to be installed by composer. Now that the `bolt/passwordlib` package is created (and tagged with 1.0.1), _that_ package is installed instead.

However, after the `1.0.0-beta1` tag, some refactoring commits were done on the master branch of the `passwordlib/passwordlib` package. Those changes have now also been added to tag `1.0.1` of `bolt/passwordlib`. This causes the following error to be thrown in php5:

```
PHP Strict Standards:  Declaration of Bolt\Legacy\PasswordLib\PasswordLibFactory::createHash() should be compatible with PasswordLib\Password\Factory::createHash($password, $prefix = '$2a$', array $options = Array) in vendor/bolt/bolt/src/Legacy/PasswordLib/PasswordLibFactory.php on line 16
```

(which gets thrown as a ContextErrorException in php7).

The Bolt\Legacy\PasswordLib\PasswordLibFactory file needs to be updated to be compatible with the `1.0.1` version of the `bolt/passwordlib` package to prevent these errors from occurring.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 3.5
| Install type                   | Composer install
| BC Break                     | yes
| PHP version                 | 5.6 / 7.2
| Web server                  | Any

Reproduction
------------

The error mentioned above occurs both when browsing to any bolt page, or by running any `nut` command-line commands.

**Comment by bobdenotter** [comment] 2018-10-03 17:00
Thanks for bringing this up. Bolt 3.x should remain compatible with PHP 5.5.9 and up.. 

I've tried it on PHP 5.5, and didn't see any errors when doing some quick monkeytesting, and Travis passes as well. When exactly are you seeing this error? 

![screen shot 2018-10-03 at 18 57 36](https://user-images.githubusercontent.com/1833361/46426295-6a4b0000-c73e-11e8-86ba-557b44e671ef.png)

**Comment by taakberg** [comment] 2018-10-03 17:20
On php5, the notice is only visible in the php error logs when opening bolt in the browser. When any `nut` command line is run, it shows the error. On php7 however, since errors are now exceptions, you do see it right away when opening bolt in the browser.

I've now updated to the 3.6 (beta) version and this resolves the issue though.

**Comment by bobdenotter** [comment] 2018-10-03 18:21
If you're on 3.5, you shouldn't even be getting bolt/passwordlib, right? The `composer.json` for that version states `"passwordlib/passwordlib": "^1.0@beta",` still. See: https://github.com/bolt/bolt/blob/3.5/composer.json#L44 

I mean, it's probably something I messed up, just not certain what it is, yet. :-)

**Comment by taakberg** [comment] 2018-10-03 18:43
If I'm not mistaken, this has to do with one of the packages required by bolt/bolt that in turn requires bolt/passwordlib. Since the bolt/passwordlib composer.json states that it replaces the passwordlib/passwordlib package, it uses the bolt/passwordlib instead.

I didn't dig deep into the dependency tree to see which package requires which, but imagine that this is the case here.

**Comment by bobdenotter** [comment] 2018-10-03 19:21
Oh, that might be the case.. Will also dig in 👍

**Comment by bobdenotter** [comment] 2018-10-03 20:45
Ok, I still can't reproduce this.. running `composer` update on an existing 3.5 setup just pulls in the stuff it needs: 

```
$ php composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 29 updates, 0 removals
  - Updating bolt/themes (v2.0.9 => v2.0.10): Downloading (100%)
  - Updating embed/embed (v3.3.5 => v3.3.6): Downloading (100%)
  - Updating filp/whoops (2.2.0 => 2.2.1): Downloading (100%)
  - Updating symfony/asset (v2.8.45 => v2.8.46): Loading from cache
  - Updating symfony/filesystem (v2.8.45 => v2.8.46): Downloading (100%)
  - Updating symfony/config (v2.8.45 => v2.8.46): Downloading (100%)
  - Updating symfony/debug (v2.8.45 => v2.8.46): Downloading (100%)
  - Updating symfony/console (v2.8.45 => v2.8.46): Downloading (100%)
  - Updating symfony/finder (v2.8.45 => v2.8.46): Downloading (100%)
  - Updating symfony/property-access (v2.8.45 => v2.8.46): Downloading (100%)
  - Updating symfony/options-resolver (v2.8.45 => v2.8.46): Downloading (100%)
  - Updating symfony/intl (v2.8.45 => v2.8.46): Downloading (100%)
  - Updating symfony/event-dispatcher (v2.8.45 => v2.8.46): Loading from cache
  - Updating symfony/form (v2.8.45 => v2.8.46): Downloading (100%)
  - Updating symfony/http-foundation (v2.8.45 => v2.8.46): Downloading (100%)
  - Updating symfony/http-kernel (v2.8.45 => v2.8.46): Downloading (100%)
  - Updating symfony/monolog-bridge (v2.8.45 => v2.8.46): Loading from cache
  - Updating symfony/process (v2.8.45 => v2.8.46): Downloading (100%)
  - Updating symfony/security (v2.8.45 => v2.8.46): Downloading (100%)
  - Updating symfony/stopwatch (v2.8.45 => v2.8.46): Loading from cache
  - Updating symfony/translation (v2.8.45 => v2.8.46): Downloading (100%)
  - Updating symfony/validator (v2.8.45 => v2.8.46): Downloading (100%)
  - Updating symfony/var-dumper (v2.8.45 => v2.8.46): Loading from cache
  - Updating symfony/twig-bridge (v2.8.45 => v2.8.46): Downloading (100%)
  - Updating symfony/routing (v2.8.45 => v2.8.46): Downloading (100%)
  - Updating symfony/web-profiler-bundle (v2.8.45 => v2.8.46): Downloading (100%)
  - Updating symfony/yaml (v2.8.45 => v2.8.46): Downloading (100%)
  - Updating league/flysystem (1.0.46 => 1.0.47): Downloading (100%)
  - Updating composer/xdebug-handler (1.2.1 => 1.3.0): Downloading (100%)
Package silex/silex is abandoned, you should avoid using it. Use symfony/flex instead.
Package silex/web-profiler is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
> Bolt\Composer\ScriptHandler::updateProject
> Bolt\Composer\ScriptHandler::installAssets
Installing bolt_assets to /home/pi/www/bob.biz.tm/public/bolt-public
```

Updated correctly: 

```
$ php app/nut init

 Welcome to Bolt! - version 3.5.7.
```

```
$ composer show | grep pass
ircmaxell/password-compat          v1.0.4      A compatibility library for the proposed simplified password hashing algorith...
passwordlib/passwordlib            1.0.0-beta1 A Password Hashing Library
```

Could you do a `composer why bolt/passwordlib` on your setup, to see which dependency causes it?

**Comment by taakberg** [comment] 2018-10-04 06:29
This is the output of the command you requested:

`$ composer why bolt/passwordlib`
```
There is no installed package depending on "bolt/passwordlib"
```
`$ composer why passwordlib/passwordlib`
```
bolt/bolt         v3.5.6  requires  passwordlib/passwordlib (^1.0@beta)
bolt/passwordlib  1.0.1   replaces  passwordlib/passwordlib (*)
```
`$ ./nut database:check`
```
PHP Strict Standards:  Declaration of Bolt\Legacy\PasswordLib\PasswordLibFactory::createHash() should be compatible with PasswordLib\Password\Factory::createHash($password, $prefix = '$2a$', array $options = Array) in /vagrant/src/cms/vendor/bolt/bolt/src/Legacy/PasswordLib/PasswordLibFactory.php on line 16
...output truncated...
```

_However_, I think I figured out why this is happening. Along with some other changes, I've changed the `minimum-stability` to `stable` in my composer.json file. In principle, it looked like this:
```
{
    "require": {
        "bolt/bolt": "v3.5.6"
    },
    "minimum-stability": "stable"
}
```

I removed the entire `/vendor` directory and ran a composer update, then was confronted with this message:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for bolt/bolt v3.5.6 -> satisfiable by bolt/bolt[v3.5.6].
    - bolt/bolt v3.5.6 requires passwordlib/passwordlib ^1.0@beta -> satisfiable by passwordlib/passwordlib[1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-beta1, 1.0.x-dev] but these conflict with your requirements or minimum-stability.
```

To fix this, I've added the passwordlib library with the `@beta` version explicitly:
```
{
    "require": {
        "bolt/bolt": "v3.5.6",
        "passwordlib/passwordlib": "^1.0@beta"
    },
    "minimum-stability": "stable"
}
```
And this now installs a working setup of Bolt! Somehow composer seemed to have cached that the `bolt/passwordlib` was a valid installation candidate for this package, probably because it was already present in my vendor directory or something, and didn't want to get rid of it.

Thanks for all the help! This took way more effort than I anticipated.

**Comment by bobdenotter** [comment] 2018-11-09 12:33
Going to close this, because it seems like it's not a _real_ bug.. 

If somebody read this, and has the same issue, resolve it by running: 

```
rm -rf composer.lock vendor
composer install
``` 

See also: #7699

**Closed as completed by bobdenotter** 2018-11-09 12:33 UTC
