### ISSUE TITLE
local extension autoloader in windows/xampp

### ISSUE THREAD

**Issue by mcbmcb0** [bolt/bolt#4604] opened 2015-12-17 10:41 UTC
Hello
using xampp (php 5.6.8, apache 2.4, win7-64) and as far as I can tell the composer autoloader does not rebuild its 'autoload_psr4.php' (in extensions/vendor/composer) with any reference to the contents of /extensions/local/{vendorname}/{ext_name} folders.  I've installed 'bolt-extension-starter-extended' identically on fresh installs of bolt ( 2.2.14) on both xampp and a debian-apache stack and the debian setup works fine. I've tried a homemade local extension too. I've done various things to rebuild the autoload - 'composer dump-autoload', commenting out new class reference then reinstalling all extensions, deleting the composer.json and composer folder in extensions/vendor/ , "?rebuild-autoloader". I also noticed when the debian install encountered a class loader error it would attempt to 'rebuild the extension autoloader' while the xampp install would just die.

The classes don't autoload. when examining the 'autoload_psr4.php' file the local/extension/ elements for the returned array are missing on the xampp test. file permissions are full control everyone (like 777).  the xampp bolt otherwise works fine. htaccess passes the 'test your htaccess' file. when i manually include the class files (in the extension's init.php) it all works fine.

I'd be happy to blame xampp if I could find a cause or if other windows stacks worked.
is this a reproducible bolt bug?

thanks

**Comment by SahAssar** [comment] 2016-01-05 16:56
I downloaded xampp, installed it and bolt and put the bolt-extension-starter-extended as a local extension and could not see anything out of the ordinary. It was on a windows 8 computer though, do you have another windows 7 install that you can try it on?

 If it's still wonky on another windows 7 install I can pull down a win7 VM and try do debug it further.

**Comment by SahAssar** [comment] 2016-01-12 19:23
Closing since I couldn't reproduce, but if you are having the issue on multiple installs feel free to reopen and I'll dig deeper! :)

**Closed by SahAssar** 2016-01-12 19:23 UTC
Labels: Bug verification needed
