### ISSUE TITLE
[RFC] Limit on pictures?

### ISSUE THREAD

**Issue by mattiaslundback** [bolt/bolt#5170] opened 2016-04-12 21:49 UTC
There seems to be a limit of 2MB uploading a picture when creating a new entry. Most digital pictures are much bigger and this is rather inconvenient. This limit was not present in Bolt 2.2.

**Comment by SahAssar** [comment] 2016-04-12 21:56
That's your server config, I've tested bolt3.0beta with larger files than 2MB. 

I'm closing this, but if you can't find the issue feel free to post here and I'll dig deeper.

**Comment by mattiaslundback** [comment] 2016-04-12 22:15
I'm running on the same server, so there shouldn't be a difference. upload_max_filesize is 32MB on the server, and also in the other library where I run Bolt 2.2. But of course there might be other things that limits the file size. Strange ...

**Comment by SahAssar** [comment] 2016-04-13 08:23
I just tried it out on a bolt 3.0 beta 2 install with a 119Mb file, so I'm pretty confident that it isn't the filesize. Are you sure that the filetype is allowed in your config.yml? I've earlier had bolt mischaracterize why a file couldn't be uploaded (usually the other way around, but worth checking).

**Comment by mattiaslundback** [comment] 2016-04-13 08:42
Noted also that there is no limit if I use the file upload function. Only in the template (entries).

**Comment by SahAssar** [comment] 2016-04-13 09:51
Alright, I just tried in a record's image field (I assume that's what you meant), and it worked to upload a 10Mb image... So the limit you see is only when uploading to an image or file field?

**Comment by mattiaslundback** [comment] 2016-04-13 15:33
It is the image field. Puzzled how it can tell me the limit is exactly 2MB, since that figure is nowhere in phpinfo. But I give up for now. It will probably solve itself over time.

**Comment by mattiaslundback** [comment] 2016-04-26 15:11
I have found a limit on filesize in the upload handler siriusphp that fits well with my problem. If - for some reason - this limit is not changed the result would be blocking of imagefiles larger than 2M. If someone can verify that siriusphp is used in the backend to upload files this explains why the uploads do not work. My apache settings are 32M both for upload_max_filesize and post_max_filesize.

https://github.com/siriusphp/validation/blob/master/src/Rule/Upload/Size.php

**Comment by SahAssar** [comment] 2016-04-26 18:52
Hmm... I'm at whits end on this... I can't reproduce it, but what you say about siriusphp/validation makes a lot of sense (since we use it). I'm reopening and I'll see if I someone on slack/irc is more knowledgeable on this...

**Comment by SahAssar** [comment] 2016-04-26 18:55
@mattiaslundback Also, could you perhaps open the phpinfo in the debug bar and just check that your changes to upload_max_filesize and post_max_filesize have actually been picked up?

**Comment by mattiaslundback** [comment] 2016-04-26 18:56
Have the same problem on two separate servers, with almost no similarities. The strange thing is that the limit is said to be 2.1M on my cloudserver (testserver) and not 2.0 as on my ordinary server. But neither will accept large files. Only when uploading images when creating a new entry. The problem does not occur when using the file-manager.

**Comment by mattiaslundback** [comment] 2016-04-26 19:00
I did that earlier and they are both ok (32M) on my ordinary server. But now I see that my cloudserver has only 2M upload_max_filesize. I'ĺl try to change that to see what happens.

**Comment by mattiaslundback** [comment] 2016-04-26 19:05
Didn't help. Set both to 8M. Now it says the limit is 2.0 instead of 2.1

**Comment by SahAssar** [comment] 2016-04-26 19:08
Okay, but it works with images larger than 2M on your ordinary server which actually accepts the 32M values? Cause if so, it seems like this is how you change the php.ini values on c9.io (which I assume you use): https://community.c9.io/t/customizing-php-ini/1487

**Comment by mattiaslundback** [comment] 2016-04-26 19:10
No, it doesn't work on either server. The same error-message on both servers. And both run Bolt 3.0 beta  3.

**Comment by SahAssar** [comment] 2016-04-26 19:17
> two separate servers, with almost no similarities

What do you mean no similarities? Are both run on the same platform/provider? Same php/apache config?

I'm trying to nail down why we can't reproduce the error you're getting...

**Comment by mattiaslundback** [comment] 2016-04-26 19:18
I have no problem changing php.ini on c9.io, it's just changing the value for those two variables. But the file is not in the workspace directory, but in the root of the server. Harder to do it on my Synology. I never SSH into it because I don't want to mess anything up. But phpinfo says its 32M for both variables. Checked by using the debugger (nut) in Bolt.

**Comment by mattiaslundback** [comment] 2016-04-26 19:22
One server is a Synology that's in my home. That's the production server. Apache 2.2, PHP 5.6.17

The other is c9.io, a cloudserver with a virtual setup. That's Apache 2.47 and PHP 5.5.9

So they have very little in common, besides both running Bolt 3.0 beta 3.

**Comment by rossriley** [comment] 2016-04-26 21:43
Just for reference, the Sirius upload validator isn't the problem. That would only be an issue if the validation rule was added, which we don't do. We only use the valid extensions rule.

**Comment by rarila** [comment] 2016-04-27 03:52
Check if you use [``post_max_size``](http://php.net/manual/en/ini.core.php#ini.post-max-size) and not ``post_max_filesize`` as mentioned!

**Comment by mattiaslundback** [comment] 2016-04-27 11:23
Yes, only a typo from my part :-)

**Comment by SahAssar** [comment] 2016-04-27 11:47
As in typo here in the issue or typo in the actual config?

**Comment by mattiaslundback** [comment] 2016-04-28 09:04
Just here. Haven't touched the name in the config, that's preset.

**Comment by bobdenotter** [comment] 2016-04-28 09:45
@mattiaslundback Could you be a bit more clear? Does this mean the issue can be closed, because it was a typo on your end?

**Comment by mattiaslundback** [comment] 2016-04-28 11:45
No, it is not a typo. I only answered the question from rarila whether I had typed the wrong term into my php.ini. I have not typed "post_max_filesize" by mistake into my php.ini.

So the problem is very much alive. Actually surprised nobody else gets this error, since I get it on two independent servers.

**Comment by lenlorijn** [comment] 2016-05-11 12:45
Hi All,

I think I might have found the problem.

I was able to reproduce this locally with a bolt 3.0 upgrade from a bolt 2.* install.
I'm using Chrome 50.0.2661.94 .

The issue seems to be that the buicUpload widget tries to determine if the maxSize setting is an int. If it is not an int it will fall back to a default 2MB limit. 
After checking my settings it showed me that the setting value is actualy a float.

So eventhough the setting is larger it fails to recognise it as an int and falls back to the default 2MB.

Please see:
app/src/js/widgets/buic/buicUpload.js:41
![selection_035](https://cloud.githubusercontent.com/assets/4076882/15181311/dc526842-1786-11e6-9434-528a767ef3d1.png)

Could you confirm that this is the issue here?

**Comment by bobdenotter** [comment] 2016-05-11 12:47
Ping @rarila: Do you think this could be the case?

**Comment by lenlorijn** [comment] 2016-05-11 13:34
I forgot to mention I'm using PHP 5.6.11-1ubuntu3.3 with the following upload/post settings:
post_max_size = 8M
upload_max_filesize = 32M

**Closed** 2016-05-13 16:06 UTC
Labels: Bug

**Comment by mattiaslundback** [comment] 2016-05-29 21:05
Updated today. The bug is now gone.

**Comment by SahAssar** [comment] 2016-05-29 21:06
@mattiaslundback Thanks!
