### ISSUE TITLE
Relationships restricted to one contenttype break easily

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3192] opened 2015-03-20 00:30 UTC
I have a record that can have relationships with itself (but only one). I want several relationships related to one record so in their edit pages, I set their relationship to that one record.

However, due to the bi-directional nature of relationships, when I open the record that all of those records are linked to, it picks one of those relationships as the "true" one. When I save this record, I lose all of the other relationships.

Is this by design? It's quite frustrating, and even more so for people who don't quite get the "one-to-one" thing. If it is by design, a warning should appear when setting this from another record, that this relationship has already been set.

**Comment by SahAssar** [comment] 2015-09-29 19:52
I don't really understand, if contenttype XYX has singular relations within itself there shouldn't be a way for you to have multiple relations from one XYX record to another XYX record, right?

Is the record with multiple relationships to XYX records not of contenttype XYX?

**Comment by SahAssar** [comment] 2015-10-02 21:22
Going to close this as I haven't been able to reproduce (or couldn't understand? I tried!) If this is still an issue in current versions please feel free to reopen :)

**Comment by Pinpickle** [comment] 2015-10-04 15:49
@SahAssar I don't think this should be closed, let me explain a use case.

You have 3 records, A, B, and C with a one-to-one relationship allowed with each other.

A user sets A to be related to B
A user (maybe a different one) sets C to be related to B.

This would probably affect some way the site is displayed. For a time, fetching related records for B will retrieve C and A (at least last time I checked, this was the case). By the sounds of things, this is not expected behaviour. When a user goes and saves B, only one of those relationships is maintained (expected behaviour but not intuitive).

The relationship *should* break when C was set to be related to B (to maintain one-to-one relationships). Also, there should be a warning displayed as this is done that relationships will be broken because it could be very difficult to predict this as a user.

**Comment by SahAssar** [comment] 2015-10-04 16:46
@Pinpickle Ah, then I understand! Sorry, you're right this seems to be a bit dodgy. I'm not really sure how it was intended to behave in such a scenario. Pinging @GawainLynch  or @bobdenotter for more answers or wisdom?

**Comment by GawainLynch** [comment] 2015-10-04 21:54
@Pinpickle… both of your explanations broke my brain… :grinning: 

OK, so… `A`, `B` and `C` are records… but are they the same ContentType or different, or does that even matter?

More importantly, a relationship is defined by a single record. If `foo` sets a relationship to `bar` that is all that matters, if `bar` sets a relationship to `booze` and not `foo` that is, and should be, irrelevant to `bar`… `bar` and `booze` are welcome to do their own thing…

…my head just exploded.

Maybe, assuming I am missing the point and @bobdenotter hasn't facepalmed me, you could add a "steps to reproduce" section for those tired people that need a hug.

**Comment by SahAssar** [comment] 2015-12-13 15:25
Since this has been aged a bit (to bring out the oaky taste we all love) I'll just re-explain the issue since it still seems present.

User has three records in the same contenttype: A, B, C. The contenttype has a relation to itself with `multiple: false`.

1. User edits A and sets a relation to B
2. User edits C and sets a relation to A

This then breaks in some pretty weird ways. 

In 2.2 it shows A as related to C, It shows B as related to A until A is saved again (and therefore overwriting the previous relation), and shows C as related to A.

In current master it's just plain weird. When editing A it shows A as related to itself and C, editing B shows it as related to itself and A, editing C shows it as related to itself and A. See this: http://i.imgur.com/ee3Cz61.png

After writing this my head hurts...

**Comment by SahAssar** [comment] 2016-01-05 20:39
Relations are left as-is in v3 (for BC reasons). We might see some changes in v4, but that's in the future.

It seems (to me) this issue still stands though (but I might be wrong, @rossriley said he'd have a look)

**Comment by SahAssar** [comment] 2016-07-26 18:58
Assigning this to @rossriley for fix or dismissal! :)

**Comment by GawainLynch** [comment] 2016-10-08 09:36
Moving to 3.3 while waiting on feedback from Ross

**Comment by GawainLynch** [comment] 2016-10-08 10:30
Quoth @rossriley in Slack:

> I’m pretty sure it can go… I think we addressed the problem and as far as I can see it behaves correctly now
> I think for reference that this is the PR which improved it: #4773

**Closed by GawainLynch** 2016-10-08 10:30 UTC
Labels: Bug

**Comment by SahAssar** [comment] 2016-10-08 10:47
This isn't really fixed... If one has 2 pages and one entry and has configured bidirectional relations between them with `multiple: false` and then 1. set relation from entry1 to page1 and 2. sets relation from page2 to entry1 you will end up with multiple relations in entry1 even though it has it's relation set to `multiple: false`.

I don't think it's a huge issue and I'm not sure if the desired behavior is to overwrite the original relation, but something to be aware of nevertheless.

The biggest problem with this is that the second relation is hidden when editing entry1 and if entry1 is saved it will remove the second relation, so this can lead to very confusing situations for an editor.

**Comment by GawainLynch** [comment] 2016-10-08 10:51
> you will end up with multiple relations in entry1 even though it has it's relation set to `multiple: false`.

Correct me if I am wrong — :koala: — but isn't what you're describing an "incoming" relationship? … ergo multiplicity settings don't (logically) apply?

**Comment by SahAssar** [comment] 2016-10-08 10:53
@GawainLynch Fair enough, but since bidirectional relations make no UI difference between incomming and outgoing this can still lead to confusion. Also

> The biggest problem with this is that the second relation is hidden when editing entry1 and if entry1 is saved it will remove the second relation, so this can lead to very confusing situations for an editor.

**Comment by GawainLynch** [comment] 2016-10-08 11:20
Stop throwing rational thought at me :laughing: `</kidding>`

OK, so I think what I am hearing then — oh dear, Gawain is about to comment on UI … #1555 might have finally become a reality — is that this is actually then a UI issue, which is probably rather easy to address?

If that's the case, shall we reopen, move from `bug` to `UI/UX enhancement` and assign to a willing ~~victim~~ team member?

**Comment by SahAssar** [comment] 2016-10-08 11:40
Well, sortof. We have two ways of dealing with this

1. Fix UI, but we'd need to make showing bidirectional relations more complex by showing incoming and outgoing as separate, and if we separate them there I think we need to have some way of showing only outgoing or incomming in FE too...
2. Throw a warning if someone has configured bidirectional relations without setting `multiple: true`.

I vote for 2.

**Comment by bobdenotter** [comment] 2016-10-09 10:55
My vote is for option 2 as well. 👍
