### ISSUE TITLE
[BUG] - index.php isn't redirected

### ISSUE THREAD

**Issue by nlemoine** [bolt/bolt#5578] opened 2016-07-25 10:36 UTC
Hi,

When accessing a bolt install directly with hostname.com/index.php, the page isn't redirected to domain root "/". 

Details
-------

 - Relevant Bolt Version: 3.0 | master
 - Install type: any
 - PHP version: [ 5.4 | 5.5 | 5.6 | 7.0 ]
 - Used webserver: Apache

Reproduction
------------

Go to any Bolt website an hit: hostname.com/ + index.php
The page isn't redirected. 

This issue triggers many problems:
- thumbnails returns 40, URL becomes something like /index.php/thumbs/500x500/image.jpg and thumbnail aren't generated anymore
- all generated links are prefixed with "/index.php"
- duplicate content issues (related to the above issue)

And maybe others, I didn't test everything.

The fix is quite easy to implement, see how Symfony Standard Edition deals with this: https://github.com/symfony/symfony-standard/blob/master/web/.htaccess#L37-L49

If you're ok with this bugfix, let me know, I can submit a PR.

**Comment by PhillippOhlandt** [comment] 2016-07-25 10:40
For me, this seems to be a user config problem.

**Comment by PhillippOhlandt** [comment] 2016-07-25 10:44
Update: ah, Bolt comes with an own .htaccess file (nginx user here). Well, I see no problems in doing a PR. ping @GawainLynch

**Comment by nlemoine** [comment] 2016-07-25 10:46
Sure it is, but as you mention, Bolt provides an htaccess file and an nginx config file to deal with both server softwares. And users tend to trust provided files ;)

If @GawainLynch is ok, I'll submit a PR.

**Comment by SahAssar** [comment] 2016-07-25 10:46
Any duplicate content issues should have been fixed in #4793, also, see that issue for some discussion on the redirect.

**Comment by GawainLynch** [comment] 2016-07-25 11:01
Where are we looking here? The asset try.bolt.cm is an Aura router install and not Bolt.

**Comment by nlemoine** [comment] 2016-07-25 11:02
You mean https://github.com/bolt/bolt/pull/4794 ? 

Fixing this redirection problem on the PHP side isn't the right way to do this. This is a rewrite rule issue. 

Fixing the canonical meta tag doesn't mean the duplicate content issue is fixed. Let's say I post some URLs prefixed with `/index.php` of a bolt site on some page crawled by Google. If this the website hasn't set the canonical (which isn't set by default), this will generate duplicate content. 

It also seems quite obvious to redirect the router file. I can't name a CMS/Framework not doing this.

**Comment by nlemoine** [comment] 2016-07-25 11:03
@GawainLynch, from the showcase page: http://nicalala.com/index.php

**Comment by GawainLynch** [comment] 2016-07-25 11:04
> Fixing this redirection problem on the PHP side isn't the right way to do this. This is a rewrite rule issue.

Agreed. We do in the Nginx config, so I am guessing that it just needs to be applied to our *default* `.htaccess`

**Comment by SahAssar** [comment] 2016-07-25 11:51
@GawainLynch We don't do it in the nginx config... We pass every request (that's not a file) to the index.php, but we don't redirect requests that contain index.php.

@nlemoine: yeah, but I thought I'd link to the one with the relevant discussion. Also, on the duplicate content thing, the canonical does get set by default to the current hostname if not explicitly set (unless you set it to false), so even if you don't set a canonical this does not lead to duplicate content.

I'm not against putting in the redirect, but if we do we should probably add it to the nginx conf too.

**Comment by bobdenotter** [comment] 2016-07-25 12:28
> When accessing a bolt install directly with hostname.com/index.php, the page isn't redirected to domain root "/".

As far as I know this is intended behaviour. Symfony / Silex apps do this by default. I'm not sure if this is something we need to "fix".

**Comment by bobdenotter** [comment] 2016-07-25 12:28
And, as @SahAssar says: The canonical is set correctly, so imho this is a non-issue.

**Comment by nlemoine** [comment] 2016-07-25 13:09
> As far as I know this is intended behaviour. Symfony / Silex apps do this by default. I'm not sure if this is something we need to "fix".

They even provide a fallback when mode_rewrite isn't available: https://github.com/symfony/symfony-standard/blob/master/web/.htaccess#L60-L68
Which is the case where the router file is actually needed in URL. And redirect when it's not. 

But if you think /index.php/ shouldn't redirect to /, it's ok, let's close the issue, I'll keep these changes in my own settings.

**Comment by bobdenotter** [comment] 2016-07-25 13:13
> But if you think /index.php/ shouldn't redirect to /,

Well, no, that's not what I meant. I'd _prefer_ it if we silently and unobtrusively got rid of `/index.php`. I just assumed that SF behaved like that for a reason, and didn't dig deeper, because it didn't bother me too much personally. 

If we can can fix it without apparent downsides, i'm all for it 👍

**Comment by cdowdy** [comment] 2016-07-25 13:43
Here is how symfony does it specifically to not have `app.php/path-here` https://github.com/symfony/symfony-docs/blob/00aad1e5a2455993a287a39ee73236cc14ed5655/cookbook/configuration/web_server_configuration.rst

**Comment by bobdenotter** [comment] 2016-09-27 15:38
Fixed by #5605

**Closed by bobdenotter** 2016-09-27 15:38 UTC
Labels: Low hanging kumquat, Question
