### ISSUE TITLE
Drop down menu hidden in users overview

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#4228] opened 2015-10-05 12:56 UTC
![users](https://cloud.githubusercontent.com/assets/1427081/10280916/8a7e82c8-6b68-11e5-9d7e-56f931dcede1.png)

**Comment by SahAssar** [comment] 2015-10-05 14:23
Duplicate of #3985, Closing.

**Closed by SahAssar** 2015-10-05 14:23 UTC
Labels: Regression, UX/UI

**Comment by bobdenotter** [comment] 2015-11-09 13:56
Fixed in aee9e5307990e6e4950f01c64b2264828798613d
