### ISSUE TITLE
Userfirst err_too_many_redirects

### ISSUE THREAD

**Issue by joshuan** [bolt/bolt#5222] opened 2016-04-19 10:18 UTC
When create new instance with database mysql (if select sqlite - all right) and first go to browser, bolt return 301 from /bolt/firstuser.

```
~/Projects/bolt/dist30$ curl http://dist30.bolt/
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="1;url=/bolt/userfirst" />

        <title>Redirecting to /bolt/userfirst</title>
    	<meta name="generator" content="Bolt">
    </head>
    <body>
        Redirecting to <a href="/bolt/userfirst">/bolt/userfirst</a>.
    </body>
</html>

~/Projects/bolt/dist30$ curl http://dist30.bolt/bolt/userfirst
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="1;url=/bolt/userfirst" />

        <title>Redirecting to /bolt/userfirst</title>
    </head>
    <body>
        Redirecting to <a href="/bolt/userfirst">/bolt/userfirst</a>.
    </body>
</html>
```

Details
-------
 - Relevant Bolt Version: 3.0
 - Install type: Github checkout
 - PHP version: 5.5
 - Used webserver: Nginx

P.S. In issue template need add database type select, because this bug exists in mysql and not in sqlite.

**Comment by d-m-** [comment] 2016-04-19 10:39
This is likely the same issue as https://github.com/bolt/bolt/issues/5213.

**Comment by GawainLynch** [comment] 2016-04-19 11:24
Definitely a duplicate of #5213 … tracking in there.

**Closed by GawainLynch** 2016-04-19 11:24 UTC
Labels: Blocking release, Bug, Duplicate
