### ISSUE TITLE
Upload handler doesn't carry HTTPS

### ISSUE THREAD

**Issue by my2ter** [bolt/bolt#4092] opened 2015-09-15 01:37 UTC
> Mixed Content: The page at 'https://www.my-site.com' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.my-site.com/upload?handler='. This request has been blocked; the content must be served over HTTPS.

Hey,

This is a weird one... Locally if I try to upload an image, the upload handler url will carry the HTTPS, but on production it does't... I am using Bolt 2.2.4.

Inspecting the "Upload image" button I can clearly see:

```
<input accept=".jpg,.png" data-upload="{&quot;type&quot;:&quot;Image&quot;,&quot;key&quot;:&quot;image&quot;,&quot;width&quot;:200,&quot;height&quot;:150}" data-url="http://www.my-site.com/upload?handler=" id="fileupload-image" name="files[]" type="file">
```

Any thoughts? Thanks.

**Comment by my2ter** [comment] 2015-09-15 04:50
To prevent this issue I have updated the following file:

`view/twig/editcontent/fields/_image.twig`
```html
data_url:     url('upload', {'handler': option.upload}, true),
```

It enforces the use of a relative scheme.

**Comment by rossriley** [comment] 2015-09-15 07:48
I've come across this one before too, the root of the problem is that the Symfony request component can't detect that you are using https, in my case it was because nginx was proxying to php without the correct headers being passed on.

If you follow the instructions here: http://symfony.com/doc/current/components/http_foundation/trusting_proxies.html and Bolt allows you to add trusted proxies to your `config.yml` file then it should work without needing the modification.

**Comment by SahAssar** [comment] 2015-10-01 20:41
Closing as this seems to be mostly a server/config issue and @rossriley provided a proper fix.

@my2ter If you feel this is not the case please feel free to reopen.

**Closed by SahAssar** 2015-10-01 20:41 UTC
