### ISSUE TITLE
[BUG] asset() generates wrong URL if installed in userdir

### ISSUE THREAD

**Issue by rompcik** [bolt/bolt#6158] opened 2016-12-12 17:18 UTC
bolt 3.2.3 flat installed in userdir (in my case: /home/irata/public_html/bolt-3.2.3/).

asset('css/foundation.css', 'theme') of Base Theme generates "http://localhost/~irata/bolt-3.2.3/~irata/bolt-3.2.3/theme/base-2016/css/foundation.css"

RewriteBase in .htaccess is set to /~irata/bolt-3.2.3/

Details
-------

 - Relevant Bolt Version: [ 3.2.3 ]
 - Install type: [ Zip/tarball install ]
 - PHP version: [ 5.6.27 ]
 - Used web server: [ Apache version 2.4.10 ]

**Comment by bobdenotter** [comment] 2016-12-12 18:20
Duplicate of #6071

**Closed by bobdenotter** 2016-12-12 18:20 UTC
