### ISSUE TITLE
[Bug] Recent articles in content menu in backend empty for non-root

### ISSUE THREAD

**Issue by ToBe998** [bolt/bolt#7487] opened 2018-05-18 11:49 UTC
Inside Bolt's backend, on the content menu (the dark part on the left, starting with "overview") shows entries for each contenttype. When you hover over a contenttype there, it will shows a link for the contenttypes overview and a link to create a new item.
Below those two, you can see a list of the most recently edited articles.

**Problem**
The list is correctly showing recent items when logged in as a **root** user, but is empty for non-root users (in my example a **chief-editor**.

The permissions.yml is untouched in this example.

-------

 - Relevant Bolt Version: 3.4.7
 - Install type: Composer install
 - PHP version: 5.6
 - Used web server: Apache 2.4
 - For UX/UI issues: Chrome

Reproduction
------------
- Make sure you have a couple of edited items in at least one contenttype
- Login as **root* user and hover over that contenttypes menu -> The recent items show up
- Logout
- Login as user with **chief-editor** role and hover over that contenttypes menu -> The recent items are empty

**Comment by ToBe998** [comment] 2018-05-18 11:51
I did some debugging and could at least see that:
- The recent items get loaded from storage and added to the menu entry
- The items get the permission "contenttype:<contenttype slug>"
- The items arrive inside the menu builder

that's as far as i got

**Comment by bobdenotter** [comment] 2018-05-18 13:14
I can confirm this behaviour. I'll see if I can figure out where it goes wrong. 

Good find, @ToBe998 👍

**Comment by bobdenotter** [comment] 2018-05-18 15:14
Turns out this is a duplicate of the dreaded "Configuration error: Permission 'everyone' is not granted to any roles. You should add a role for this permission to  permissions.yml. (5 minutes ago)" issue.. 

![screen shot 2018-05-18 at 17 12 25](https://user-images.githubusercontent.com/1833361/40242784-d5e549ca-5abe-11e8-9388-1a57862fa5d2.png)

Still digging..

**Closed as completed** 2018-05-19 10:04 UTC
Labels: bug

**Comment by ToBe998** [comment] 2018-05-22 08:41
Is there some hack for the permissions.yml to fix this in Bolt 3.4 too?

**Comment by jadwigo** [comment] 2018-05-23 07:43
Probably by adding a single line to your `permissions.yml` as in the change: https://github.com/bolt/bolt/pull/7488/commits/7963589cd8d041fae46e3b2cae620a69bb4510ff

```yml
global:
    checks: [ admin, developer ]
```

**Comment by bobdenotter** [comment] 2018-05-23 07:50
@ToBe998 In addition to that, add `everyone: [ everyone ]` to make other users also see the "latest entries".
