### ISSUE TITLE
[BUG][RFC] Sorting of records in taxonomy pages is completely off

### ISSUE THREAD

**Issue by ToBe998** [bolt/bolt#5229] opened 2016-04-20 09:02 UTC
The current mechanism in bolt to load records for taxonomy pages has serious problems with sorting.

The current logic in `Storage->getContentByTaxonomy()` will sort records by the id in `bolt_taxonomy`. This means records will be sorted by the time a record was assigned a specific taxonomy. I can't think of any scenario where this would actually make sense.

Currently the generated query produces something along these lines:

```
SELECT * FROM bolt_taxonomy 
WHERE (taxonomytype = 'tag' AND (slug = 'sometag' OR name = 'Some Tag')) 
ORDER BY id DESC LIMIT 10 OFFSET 0
```

The underlying problem is, that we do not know what contenttype to select as taxonomy pages return any contenttype with the respective taxonomy. So just doing a _INNER JOIN_ won't work.

What we would need for this and many similar problems with selecting more than one contenttype at once would be some kind of meta table, which stores special fields for all contenttypes. This is of course a rather heavy change of bolt's data structure.

A smaller approach might be this however: Just "cache" the important meta fields inside the `bolt_taxonomy` page. This means at least the following fields:
- datepublish
- status

More stuff like a Title would be handy, but we probably don't know if all contentypes have this field. So that's it i guess.

In the end, the query could look something like this:

```
SELECT * FROM bolt_taxonomy 
WHERE (taxonomytype = 'tag' AND (slug = 'sometag' OR name = 'Some Tag')) 
ORDER BY datepublish DESC LIMIT 10 OFFSET 0
```

**Comment by SahAssar** [comment] 2016-04-21 07:53
Related: #2446

The problem is that while "datepublish" might solve yours and pinpickles issues, it is not a solution as much as a workaround since it would only allow sorting on that field...

That issue was dead for a year before I closed it, and no one (as far as I know) did any work on it, so while I hope this gets done at some point I don't think that solely opening an issue will do it.

**Comment by bobdenotter** [comment] 2016-04-21 08:04
Tobe: This has been an "issue" and documented as such for ages. It's not trivial to fix, but you're more than welcome to work on it. 

As @SahAssar says: If we fix it, we should fix it _properly_ and not just patch it up for a specific usecase. :-)

**Comment by ToBe998** [comment] 2016-04-21 08:04
Yea. i'm fully aware that this problem can not easily (if at all) be fixed as it would need some more complex changes under the hood. Non the less, the current sorting is definitly not what anyone would expect, so it's technically a bug.

**Comment by SahAssar** [comment] 2016-07-26 22:23
@ToBe998 Are you still interested in working on this?

**Comment by ToBe998** [comment] 2016-07-27 07:20
I created an extension which provides an alternative to `setcontent` that can select more than one type at once, sort, search and do taxonomy filters. So, no i can live without.

Still would be something important for a future release, i think.

**Comment by SahAssar** [comment] 2016-07-27 07:26
That extension isn't public, right? Just asking since it sounds like it could be useful for other people (including myself) :)

**Comment by ToBe998** [comment] 2016-07-27 09:13
im sooooo close to getting greenlight on making some extensions public ;)

**Comment by SahAssar** [comment] 2016-11-08 16:56
Closing this for the same reason as https://github.com/bolt/bolt/issues/2446#issuecomment-190897829 ... Still would love to see it done (either in core or in that extension), but keeping these issues open isn't going to get that done and only makes it harder to herd other issues.

**Closed by SahAssar** 2016-11-08 16:56 UTC
Labels: Duplicate, Enhancement
