### ISSUE TITLE
UI blocking uninstall of extension

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#6116] opened 2016-12-01 07:57 UTC
The one time I use the UI :laughing: 
![screenshot from 2016-12-01 08-55-28](https://cloud.githubusercontent.com/assets/1427081/20786076/132bead8-b7a4-11e6-8320-8aa5acaba49e.png)

**Comment by SahAssar** [comment] 2017-02-25 13:15
@GawainLynch Sorry, but do you mean that it blocks the UI thread (as in scrolling/whatever) or as in that it blocks errors/flashes?

**Comment by bobdenotter** [comment] 2017-02-25 13:26
I think this is just about the bottom part of the "manage" pull-down being hidden by the debug toolbar.

**Comment by SahAssar** [comment] 2017-02-25 13:31
@bobdenotter Ah, in that case I'm closing. The debugbar is fixed by design and it will block certain UI elems because of that. That's why there is a button to hide it in the bottom right corner.

**Closed by SahAssar** 2017-02-25 13:31 UTC
Labels: UX/UI

**Comment by bobdenotter** [comment] 2017-02-25 13:39
Yeah, it'll all be different in Bolt 4, with the updated UI as well. :-)
