### ISSUE TITLE
[RFC] Don't use hidden files .bolt.yml and .bolt.php

### ISSUE THREAD

**Issue by rossriley** [bolt/bolt#5729] opened 2016-09-04 11:00 UTC
Since we've moved to this setup we've had quite a few issues with users' production deploys breaking because many ftp/sftp applications and indeed operating systems ignore hidden files.

Historically dotfiles are primarily used for storing user preferences or extra metadata that ideally don't disable the program in question by being wiped / not there whereas in our case these files specify a directory structure that is co-dependent on the hidden files being present.

How do we feel about 

  1. Having them as plain filesystem files `bolt.yml` and `bolt.php` or maybe
  2. Having a new top level `boot` folder and keeping them in there for some extra structure.

Obviously in the intervening period we could support both but for new distributions we can update to the new method.

**Comment by PhillippOhlandt** [comment] 2016-09-04 11:27
I like the hidden file but I also see the problem. I suggest moving to `bolt.yml` and `bolt.php` but still fallback to `.bolt.*` for the people who like that.

**Comment by GawainLynch** [comment] 2016-09-05 07:59
> Having a new top level `boot` folder

:-1: 

>  keeping them in there for some extra structure.

That might work, but the place for them is probably `app/` IMHO (follow upstream's behaviour). However, the problem is two fold:
  1. This is where we define paths
  2. It needs to know where its paths are to find the path of the file that has the location of the files that knows where the files are to find the file that has the location of the …

The file itself is a compromise to allow path configuration, that needs to be loaded early enough that it can be used prior to the configuration cycle. We're almost there on fully abstracted filesystems :smile: 

Transition…  What is valid and override the other? A lot of installs are going to have edited/adapted a `.bolt.XXX` file now (and committed to git, etc) and we'd expect every one of those sites to reconfigure if they were installing from tarball as that would drop a new (non-hidden) file.

Moreover, a lot of people will want to stay with the hidden file approach as, to us, the non-hidden approach doesn't make sense for a file that should only ever be edited once.

**Comment by bobdenotter** [comment] 2016-09-05 08:18
This is the same issue as #5720

**Comment by bobdenotter** [comment] 2016-09-05 08:22
> Having them as plain filesystem files bolt.yml and bolt.php

I'd be in favor of this. With a 'fallback' to `.bolt.yml` for BC.

**Comment by GawainLynch** [comment] 2016-09-05 08:23
> I'd be in favor of this. With a 'fallback' to `.bolt.yml` for BC.

Yes, but that will break installs for people who use tarball *and* have modified the file's contents

**Comment by bobdenotter** [comment] 2016-09-05 08:46
> Yes, but that will break installs for people who use tarball and have modified the file's contents

Couldn't we circumvent that by letting `.bolt.yml` take priority over `bolt.yml`?

**Comment by GawainLynch** [comment] 2016-09-05 08:49
Yes, until the stream of "why are my path broken" and "what do you mean my `index.twig` can't be found" due to the visible file **and** the hidden file being present, **and** the hidden file taking precedent.

**Comment by GawainLynch** [comment] 2016-09-05 08:51
All I am pointing to is that one way breaks things for some people, another way breaks things for another group of people … and moving this file's location around is going to break it for the one group of people that struggle the most with these concepts.

**Comment by rossriley** [comment] 2016-09-05 09:06
I might not have been so clear in the original message, what I meant was that we add the non dot versions of the files to the tests, so the same as now except we add..

    `elseif(file_exists($rootPath . '/bolt.yml')) {`

and 

    `elseif (file_exists($rootPath . '/bolt.php')) {`

effectively supporting either dot file or non-dotfile version.

**Comment by GawainLynch** [comment] 2016-09-05 09:12
> I might not have been so clear in the original message,

:beers: 

That works for me.

**Comment by bobdenotter** [comment] 2016-09-05 09:25
Ok, works for me, but what are we going to put in the distro files? The 'non dotfile' version?

**Comment by GawainLynch** [comment] 2016-09-06 06:00
Yeah, well that goes back to the start … that file is generated, and for generated installs is should be hidden IMHO.

Catering to people who struggle with technical concepts is something we try to do, but there needs to be a line in between punishing everyone else's installation as a result, and just providing useful documentation.

**Comment by bobdenotter** [comment] 2016-09-27 14:51
IMHO, the "packaged" `.zip` and `.tgz` versions should have the non-dotfile version.

**Comment by GawainLynch** [comment] 2016-09-27 15:12
Yeah, I am coming around to being included to agree … but … a problem still remains, like the `.gitignore`/`.htaccess` one, of overwriting people's changes.

**Comment by bobdenotter** [comment] 2016-09-30 12:36
Not _that_ relevant to people using the `.zip`.. They'll _always_ get `public` and `app`, regardless of what they changed. If they changed stuff, they'll have to fix it manually regardless. 

I think we can close this for now. :-)

**Closed** 2016-09-30 15:37 UTC
Labels: Due for closing, RFC
