### ISSUE TITLE
config buttons are overlapped

### ISSUE THREAD

**Issue by dmm1** [bolt/bolt#2630] opened 2015-01-30 13:00 UTC
V. 2.0.5 - Chrome latest 

![bolt](https://cloud.githubusercontent.com/assets/343625/5975919/f5fbbeca-a887-11e4-971e-1ed2a9dfe471.jpg)

**Comment by cdowdy** [comment] 2015-01-30 16:42
I don't get the button overlap:  

![bolt-205confg-cropped](https://cloud.githubusercontent.com/assets/5969974/5979230/dd10885a-a873-11e4-86ce-3b1e6652af66.png)  

another with the same locale:  
![bolt-de_de](https://cloud.githubusercontent.com/assets/5969974/5979236/e462c884-a873-11e4-8f9a-5dbb0c5023a6.png)  

Chrome Version 40.0.2214.94 m (64-bit) on Windows.  

Maybe you need to scroll down outside of the config editor area. You should see two scroll bars on the right hand side. One for the config editor. the other for the screen. If I'm off base I apologize :-)

**Comment by dmm1** [comment] 2015-01-30 20:11
thanks for your reply @cdowdy i don't know i have the same version 64 bit of chrome on win7 pro but your hint with the scrollbars doesn't help on 2.0.3 it worked maybe i can figure out why this is happen (to me) thanks

**Comment by rarila** [comment] 2015-01-30 20:28
Ok, I have exactly this config. Gonna test later…

**Comment by rarila** [comment] 2015-01-30 22:47
Master, Win 7, Chrome 40.0.2214.94 m / IE11 / Firefox 35.x => everything fine
Sorry, can't reproduce :-(
Either something fixed in master or some problem with your installation

**Comment by bobdenotter** [comment] 2015-01-31 10:36
Judging by your screenshot, it looks like the editor didn't load properly (no linenumbers on the left). Does the console in your browser's development tools show any errors?

**Comment by dmm1** [comment] 2015-01-31 21:25
@bobdenotter yes:
![screenshot 2015-01-31 22 22 18](https://cloud.githubusercontent.com/assets/343625/5989898/0d12e5b4-a998-11e4-94b2-4b723597b25d.png)

**Comment by bobdenotter** [comment] 2015-02-01 14:12
Ok. that error indicates something's wrong. Are you sure Bolt is installed correctly?

**Comment by dmm1** [comment] 2015-02-01 14:53
Sure sure :smile: will reinstall directly to 2.0.5 without upgrade later.

**Comment by jirimedved** [comment] 2015-02-01 18:32
Hi, i have some a problem (2.1.0 alpha1). Firefox 35.0.1.

Firebug:
ReferenceError: CKEDITOR is not defined
...dVideoEmbed(a.key)},ckeditor:function(){CKEDITOR.editorConfig=function(a){var b,...

**Comment by rarila** [comment] 2015-02-01 18:56
@jirimedved Sorry, fixed by #2666

**Comment by jirimedved** [comment] 2015-02-01 19:02
@rarila Thank you ...

**Comment by rarila** [comment] 2015-02-01 19:04
@jirimedved again sorry, there's another one… fix coming soon

**Comment by rarila** [comment] 2015-02-01 19:25
@jirimedved here we go #2667

**Comment by dmm1** [comment] 2015-02-01 21:49
thanks, works for me now :smile_cat:

**Closed** 2015-02-02 06:59 UTC
