### ISSUE TITLE
Config options issue for setting theme paths

### ISSUE THREAD

**Issue by opb** [bolt/bolt#3514] opened 2015-05-12 14:14 UTC
I'm using 2.2.0b3 as a composer package inside a laravel 4.2 application. I'm having trouble reconciling all the available options for setting where the theme is located. This includes:

- setting up `config.yml` correctly
- calling `setPath()` on the Bolt configuration object correctly
- calling `setThemePath()` on the Bolt configuration object, if indeed this is needed.

Due to the existing app layout, I need to be able to customise the path of the theme.

- I need `{{ paths.theme }}` to resolve to `/bolt-themes/mytheme`. I am seemingly unable to set this using `setPath` or `setThemePath` methods on the configuration object - I can only do it via options in `config.yml`:
```
theme_path: /bolt-themes
theme: ca
```
- Because I have set the options above, I seem unable to specify that the `bolt-themes` folder does not reside in the bolt root folder. I want to tell it that it will find `bolt-themes` in my existing  public html folder.

OK, maybe the following summary best explains what I am trying to achieve:

> Hey, Bolt. I want you to generate all urls to static files in the theme so that they begin with /bolt-themes/mytheme instead of /theme/mytheme. You can find the bolt-themes/mytheme folder inside '../public' relative to the bolt root.

If there's any set of config options which will allow me to achieve this, it would be great to know!

Many thanks

**Comment by rossriley** [comment] 2015-05-12 14:30
try this: 

`$configuration->setPath("themebase","public/bolt-themes");`

assuming that your bootstrap file runs in the root of the project, then leave the theme_path in config.yml commented out

**Comment by opb** [comment] 2015-05-12 14:47
Thanks for the response. Editing `theme_path` in `config.yml` was actually a last resort, as nothing else seemed to shift the url from `/theme/mytheme`. Sure enough, if I make the changes you suggested, then it reverts again.

Here is the full output from `$app['paths']`:

```
array (size=38)
  'root' => string '/' (length=1)
  'rootpath' => string '/home/vagrant/repos/mycompany/app/MyNamespace/Bolt/../../../bolt' (length=68)
  'apppath' => string '/home/vagrant/repos/mycompany/vendor/bolt/bolt/app' (length=56)
  'extensionsconfig' => string '/home/vagrant/repos/mycompany/app/MyNamespace/Bolt/../../../bolt/app/config/extensions' (length=90)
  'extensionsconfigpath' => string '/home/vagrant/repos/mycompany/app/MyNamespace/Bolt/../../../bolt/app/config/extensions' (length=90)
  'extensionspath' => string '/home/vagrant/repos/mycompany/app/MyNamespace/Bolt/../../../bolt/extensions' (length=79)
  'filespath' => string '/home/vagrant/repos/mycompany/app/MyNamespace/Bolt/../../../bolt/files' (length=74)
  'web' => string '/home/vagrant/repos/mycompany/app/MyNamespace/Bolt/../../../bolt/../public/bolt-public' (length=90)
  'webpath' => string '/home/vagrant/repos/mycompany/app/MyNamespace/Bolt/../../../bolt/../public/bolt-public' (length=90)
  'cache' => string '/home/vagrant/repos/mycompany/app/MyNamespace/Bolt/../../../bolt/mythemeche' (length=74)
  'cachepath' => string '/home/vagrant/repos/mycompany/app/MyNamespace/Bolt/../../../bolt/mythemeche' (length=74)
  'config' => string '/home/vagrant/repos/mycompany/app/MyNamespace/Bolt/../../../bolt/config' (length=75)
  'configpath' => string '/home/vagrant/repos/mycompany/app/MyNamespace/Bolt/../../../bolt/config' (length=75)
  'database' => string '/home/vagrant/repos/mycompany/app/MyNamespace/Bolt/../../../bolt/database' (length=77)
  'databasepath' => string '/home/vagrant/repos/mycompany/app/MyNamespace/Bolt/../../../bolt/database' (length=77)
  'themebase' => string '/home/vagrant/repos/mycompany/app/MyNamespace/Bolt/../../../bolt/../public/bolt-themes' (length=90)
  'themebasepath' => string '/home/vagrant/repos/mycompany/app/MyNamespace/Bolt/../../../bolt/../public/bolt-themes' (length=90)
  'composer' => string '/home/vagrant/repos/mycompany/vendor/bolt/bolt' (length=52)
  'composerpath' => string '/home/vagrant/repos/mycompany/vendor/bolt/bolt' (length=52)
  'app' => string '/bolt-public/' (length=13)
  'composerbackendviews' => string '/home/vagrant/repos/mycompany/app/MyNamespace/Bolt/../../../bolt/app/view/twig/' (length=83)
  'composerbackendviewspath' => string '/home/vagrant/repos/mycompany/app/MyNamespace/Bolt/../../../bolt/app/view/twig/' (length=83)
  'themepath' => string '/home/vagrant/repos/mycompany/app/MyNamespace/Bolt/../../../bolt/../public/bolt-themes/mytheme' (length=93)
  'templatespath' => string '/home/vagrant/repos/mycompany/app/MyNamespace/Bolt/../../../bolt/../public/bolt-themes/mytheme' (length=93)
  'extensions' => string '/extensions/' (length=12)
  'files' => string '/files/' (length=7)
  'async' => string '/async/' (length=7)
  'upload' => string '/upload/' (length=8)
  'bolt' => string '/bolt/' (length=6)
  'theme' => string '/theme/mytheme/' (length=10)
  'current' => string '/' (length=1)
  'canonicalurl' => string 'http://myapp.dev/' (length=18)
  'currenturl' => string 'http://myapp.dev/' (length=18)
  'hosturl' => string 'http://myapp.dev' (length=17)
  'rooturl' => string 'http://myapp.dev/' (length=18)
  'canonical' => string 'http://myapp.dev' (length=17)
  'protocol' => string 'http' (length=4)
  'hostname' => string 'myapp.dev' (length=10)
```
Nothing I do will allow me to change `theme` to `/bolt-themes/mytheme` without altering one of the other theme paths.

Thanks again

**Comment by opb** [comment] 2015-05-12 16:34
A bit more info. Here's a snippet from where I create the bolt application instance:

```php
            $configuration->setUrl('files', '/bolt-public/files/');
            $configuration->setUrl('theme', '/bolt-themes/');

            $bolt = new BoltApplication(['resources' => $configuration]);
            $bolt->initialize();

            return $bolt->handle($request);
```

The `setUrl()` method works for `files`, but not for `theme`. This is because as part of bolt's `initialize()` method, it (indirectly )calls the `setThemePath()` method on the `$configuration` object, and this overrides any previously-set values for the `theme` key. 

I guess the answer for now is to extend the configuration object, and override the relevant method so that `setThemePath()` is not called.

**Comment by Pinpickle** [comment] 2015-08-04 03:56
Been running into this issue myself as well. Currently my solution is to set `theme_path` in config file and set the theme URL *after* initialising. My case is a little different as the theme path points to a different location than the URL - the URL just contains static assets to serve while the path location has all of the source files and templates.

**Comment by SahAssar** [comment] 2015-10-01 19:21
Does the theme/config.yml `template_directory` help with this? It's now documented here: https://docs.bolt.cm/building-templates

**Comment by SahAssar** [comment] 2015-10-02 21:33
Since no comments have come in to the contrary (Well I have to go by something, right?) I'm going to close this.

If this is still an issue please feel free to reopen :)

**Comment by Pinpickle** [comment] 2015-10-04 15:44
@SahAssar `template_directory` may *help* in my case, but I believe it won't solve the original issue. The problem is that Bolt is quite stubborn with setting a custom theme directory altogether - whether you want a different template directory or not.

**Comment by SahAssar** [comment] 2015-10-04 16:52
@Pinpickle I'll reopen the issue :)

BTW, if you feel I close the issues too fast you have only to let me know. I just got this responsibility a few days ago, so I've been trying to clear up what is and isn't still an issue. A few real issues might be caught in the crossfire sometimes ;)

**Comment by Pinpickle** [comment] 2015-10-04 16:56
@SahAssar I don't think your closing was unreasonable - I was just a bit slow (haven't had a chance recently). Closing issues certainly gets people talking faster!

**Comment by GawainLynch** [comment] 2015-10-04 21:57
Just adding that @CarsonF is currently working on paths… though some of this will probably be bumped to 2.4, as #BPFL has laid down some laws for getting 2.3 out.

**Comment by SahAssar** [comment] 2015-12-13 11:50
Info for anyone that comes along: The version roadmap has changed, and since this issue mentions v2.4 (which is now 3.1/3.X) I'm posting this here https://discuss.bolt.cm/d/112-bolt-version-roadmap-changes/7 

Same text in Mongolian for @rarila:

Хувилбар заалтуудын өөрчлөгдсөн байна, энэ асуудал (одоо 3.1 / 3.X юм) v2.4 дурдсан хойш би энд https://discuss.bolt.cm/d/112 энэ илгээхээсээ байна: хэнд ч Мэдээлэл хамт ирдэг гэдгийг -bolt-ын-заалтуудын-өөрчлөлт / 7

**Comment by SahAssar** [comment] 2016-07-26 20:15
I'm gonna (perhaps recklessly) close this again. please reopen with details pertaining to the current master or release 3.X if it does not work since a lot might have changed.

**Closed by SahAssar** 2016-07-26 20:15 UTC
Labels: Enhancement, RFC
