### ISSUE TITLE
[BUG] Extension Manager does not use correct URL to fetch extension list json

### ISSUE THREAD

**Issue by claudissimus** [bolt/bolt#5359] opened 2016-05-23 08:41 UTC
When accessing the extension manager in the backend, I'm getting a JSON.parse Error. 
Bolt does not seem to take into account whether the Site is installed in the domain root or in a subfolder. The bolt admin is accessible under http://domain.tld/subfolder/admin/ but Bolt wants to fetch the extension list from http://domain.tld/admin/. 

 - Relevant Bolt Version: 3.0.1
 - PHP version: 5.5 

------------
![bolt_extension_error](https://cloud.githubusercontent.com/assets/10771727/15464970/5bd30302-20d2-11e6-8b3a-bf176bcbf924.png)

**Comment by bobdenotter** [comment] 2016-05-30 07:51
Duplicate of #5339

**Comment by GawainLynch** [comment] 2016-05-30 07:54
> Duplicate of #5336

Erm… You sure?

**Comment by GawainLynch** [comment] 2016-05-30 07:56
Will you stop being so quickc at fixing your typos, @bobdenotter :stuck_out_tongue_winking_eye:

**Closed** 2016-05-30 10:20 UTC
Labels: Bug, Duplicate
