### ISSUE TITLE
save options, overset text.

### ISSUE THREAD

**Issue by serweb-labs** [bolt/bolt#2366] opened 2014-12-29 08:46 UTC
By clicking the chevron in save button , the text options are overset (text-overflow).
Only the button on the side panel.

:v: 
![screenshot - 291214 - 04 42 21](https://cloud.githubusercontent.com/assets/6233822/5567198/07b0e6b4-8f1e-11e4-9f97-a758c0690f34.png)

**Comment by bobdenotter** [comment] 2015-01-03 11:16
Duplicate of #2013

**Closed by bobdenotter** 2015-01-03 11:16 UTC
Labels: bug, UX/UI
