### ISSUE TITLE
[BUG/ MISSING] Cannot modify backend contenttype listing view

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/bolt#5102] opened 2016-03-30 10:31 UTC
With [this](https://github.com/bolt/bolt/tree/master/app/view/twig/custom/listing) files, you can change the rows of the contenttype listing in the backend. 

With a composer installation, where all Bolt files live in `vendor` you cannot use this anymore. When I create the exact same folder path in my `app` folder, the templates won't be loaded. 
But it works fine when I edit them in the `vendor` folder. 

So the files in my own `app` folder are just not loaded. 
## Details
- Relevant Bolt Version: 3.0.0 beta 1
- Install type: Composer install
- PHP version: 7.0
- Used webserver: php dev server

**Comment by SahAssar** [comment] 2016-03-30 22:34
I'm thinking this is a case of "It works as implemented, but not as intended" and another indication that custom listings need to be reworked and rethought. Just like you can't override any other backend twig file by just creating the file on a composer install this is no different.. 

Context: https://github.com/bolt/bolt/blob/master/app/view/twig/dashboard/_recently_edited.twig#L20

**Comment by rarila** [comment] 2016-03-31 05:35
I already have a branch here refactoring them as they have other problems too. One thing still to do is moving them to ``config``

**Comment by GawainLynch** [comment] 2016-03-31 05:39
Ah, I forgot about that @rarila 

That means there is a partially done BC breaking change inbound… how far from complete is it @rarila?

**Comment by rarila** [comment] 2016-03-31 05:54
It's done, but I'm not 100% happy with it as twig doesn't allow 100% isolation. That would need us to extend twig with some global set like command.

**Comment by GawainLynch** [comment] 2016-03-31 05:59
@CarsonF ^ comments?

@rarila I don't suppose you could push and link the branch so we can have a look?

**Comment by CarsonF** [comment] 2016-04-07 03:00
* Yeah they definitely still need refactoring. There's too much logic in twig.
* It is confusing for users because the project structure wasn't designed with composer in mind. It is on the roadmap to change with 4.0.
* Config and ContentTypes are getting refactored in 3.x (next) which could lead to changes here. 

To make it work, you'll need to add a directory to the twig loader. Unfortunately, we don't really have a defined spot for users to add php code, but here's the snippet:
```php
// After $app->initialize()
$app['twig.loader.filesystem'] = $app->share(
    $app->extend(
        'twig.loader.filesystem',
        function ($filesystem, $app) {
            $filesystem->prependPath(   $dir   , 'bolt');

            return $filesystem;
        }
    )
);
```

**Comment by rossriley** [comment] 2016-04-07 07:06
To be honest I think this is something that is much better served by documentation rather than putting the feature in core. We do have a very well defined way for users to add their own code, via Silex providers and anyone who is building a non-trivial app where they may need to override or add to the default behaviour should start by building their own providers and defining this.

If we go too far down the route of hardcoding directories everywhere then we end up with a situation where too much magic depends on the correctly named folders being in the right place and that's what moving to composer installs and configurable resources was designed to open up.

A small section in the docs about 'How to Override Bolt Templates' with the above snippet that @CarsonF has above inside a provider means that the user can configure where their Bolt templates are kept and we're also teaching them how to properly structure an app at the same time, rather than doing everything out of the box for them.

**Comment by PhillippOhlandt** [comment] 2016-04-07 07:26
@rossriley Yeah that sound's good. A general section for extending Bolt this way would be nice.

**Comment by SahAssar** [comment] 2016-04-21 22:03
@rarila Do you have an update on your work? IIRC it was near to being "test ready" last we spoke about it?

**Comment by rarila** [comment] 2016-04-22 05:22
Looks like tbis will land in 3.1 then

**Comment by phpetra** [comment] 2017-01-11 19:59
Hi guys,
I'm looking for a way to do exactly this: override a Backend template but can't seem to find the docs that should explain it.
Can this be done easily in a 3.2 composer-installed version? And how?

**Comment by CarsonF** [comment] 2017-01-11 20:04
@phpetra I wouldn't call it easy, and definitely not supported as the templates are going to be changing a lot in the next few months.

Take the snippet from my above comment and put it in a service provider. For version 3.3+ the service provider class name can be put in the `.bolt.yml` file like this:
```
services:
  - My\App\ServiceProvider
```
For 3.2 and below you'll need to register it yourself. 

Then just match the file structure for your overrides in the folder you added.

**Comment by phpetra** [comment] 2017-01-11 20:09
Thanks a lot @CarsonF , that's perfectly doable ;-)

**Comment by SahAssar** [comment] 2017-01-11 22:22
This is very much tied into the refactoring of the backend twig, and in a pinch it is possible to do via extension overrides or like @CarsonF suggested.

Since this was mainly a 2.2 feature (custom listings) that was dropped from 3.0 I'm going to close this, but we should definitely write up some docs on how to do it.

**Closed by SahAssar** 2017-01-11 22:22 UTC
Labels: Bug

**Comment by dispicio** [comment] 2017-01-28 19:39
@CarsonF I am trying to achieve the same thing as @phpetra (override a backend template). Using your snipped in a Service Provider, the problem is it only overrides/uses my custom twig if the original one gets deleted! `dump($app['twig.loader.filesystem']);` shows me "bolt" is set correctly (my custom path is listed as the first element in the array, before the original path). I also tried to setPaths(array(..), 'bolt') using just my custom path instead of prependPath, getting me the same result (I expected this would result in an error as twig doesn't know where to look for twigs in app/view/twig). Can you please tell me what I'm doing wrong?

**Comment by CarsonF** [comment] 2017-01-29 14:43
@dispicio Try with `twig.loader.bolt_filesystem`; that loader is before `twig.loader.filesystem` in the chain.

**Comment by dispicio** [comment] 2017-01-29 16:19
Thank you so much! Works :) (after some digging in bolt/filesystem)

**Comment by blaues0cke** [comment] 2018-10-11 06:20
@dispicio Can you please share the code that finally managed it? I also try to overwrite a backend template but I got stuck injecting the new directory:

(Edit: Moved my question to stackoverflow: https://stackoverflow.com/questions/52754936/overwrite-backend-template-in-bolt-cms)
