### ISSUE TITLE
Question about allowed_tags and CKEditor options (i tag)

### ISSUE THREAD

**Issue by lswest** [bolt/bolt#3454] opened 2015-04-26 12:50 UTC
I noticed that there's an entry in the config.yml file called "allowed_tags", and includes a list of allowed HTML elements.  However, I'm not entirely sure which editor this impacts, as the html field in my contenttypes does not allow "i" tags (although it is listed in allowed_tags).

According to the documentation on bolt.cm, you should also be able to configure ckeditor options from contenttypes.yml.  I've configured the field as follows (based off information off the CKEditor page):

```
body:
    type: html
    options:
        ckeditor:
            extraAllowedContent: 'i'
```

However, the i tags still disappear in the HTML editor.  Have I misunderstood something, or have I just made a mistake in my implementation?

I originally used a twig function via an extension to add i elements for font icons, but would prefer a simpler solution (hence why I'm looking into these options now).

**Comment by bobdenotter** [comment] 2015-04-26 13:00
Hi, 

How and when do they disappear? I'm not able to reproduce this yet. Both `<i>` and `<em>` tags stay present, even after saving and reloading. See screenshot: 

![screenshot 2015-04-26 14 57 22](https://cloud.githubusercontent.com/assets/1833361/7337286/fd923e12-ec24-11e4-98d0-3ce114449b21.png)

**Comment by lswest** [comment] 2015-04-26 13:02
Thanks for the quick reply.

The tags disappear for me when switching to/from source view, or when reloading the page.  The i tags are being nested within li tags, in case that has any impact.

This is on Bolt 2.1.6.

**Comment by lswest** [comment] 2015-04-26 15:01
I think I just figured out the issue - using empty <i></i> tags (such as for Font Awesome icons) doesn't work, as the editor removes them when they're empty.  I have gotten it to stay after one save by placing a non-breaking space in the tags, but after the save the editor will convert it to a normal space, resulting in an empty tag the next time around.

For the moment I've got it working by nesting a span tag with text inside the i, then setting font-size 0 on the span tag.  It's definitely not ideal, but now I see where the error is coming from.

**Comment by rarila** [comment] 2015-04-26 19:19
After some short googling I found out that there's a command like that involved:

```javascript
CKEDITOR.dtd.$removeEmpty['i'] = false;
```
But I don't think that can be achieved easily from inside Bolt now. I was trying to refactor CKEditor configuration a while ago and the only thing I found out is, that it will take quite some time to make it right (easy and powerful, probably impossible to bring both under one hat). So I deferred that refactoring …

**Comment by Pinpickle** [comment] 2015-04-27 08:47
@rarila, with the complexity of CKEditor config, it may be impossible to do it all through yaml. Enabling an easy way to tag on a JS callback to modify the config (maybe, without making an entire extension just for that purpose), could satisfy the needs of developers with very specific requirements. Because, chances are, there is a config setting to achieve what a developer wants.

**Comment by rarila** [comment] 2015-04-27 11:45
@Pinpickle absolutely my thoughts…

**Comment by GawainLynch** [comment] 2015-07-28 08:03
Closing as part of a general issue clean up.

**Closed by GawainLynch** 2015-07-28 08:03 UTC
Labels: Question
