### ISSUE TITLE
[BUG] contenttypes and underscores

### ISSUE THREAD

**Issue by gonoszcsiga** [bolt/bolt#5601] opened 2016-07-27 20:44 UTC
Hi, I trying to update my Bolt 2 to Bolt 3 and contenttypes.yml is giving me an error. I used underscores everywhere, but Bolt 3 doesn't like this.

Reproduction
------------
Create a content type in contenttypes.yml:
```yaml
foo_bars:
    slug: foo_bars
    singular_slug: foo_bar
    fields:
        title:
            type: text
            required: true
        slug:
            type: slug
            uses: title
    relations:
        foo_bars:
            multiple: true
```
and you will get this message on admin:

___"In the contenttype for 'Foo_bar', the relation 'foo-bars' is defined, which is not a valid contenttype. Please edit contenttypes.yml, and correct this."___

Details
-------

 - Relevant Bolt Version: 3.0.11
 - Install type: trying to update my Bolt 2 to Bolt 3 :)
 - PHP version: 7.0
 - Used webserver: Nginx 1.10.0

The relevant lines in Config.php parseContentType() function:
```php
        // when adding relations, make sure they're added by their slug. Not their 'name' or 'singular name'.
        if (!empty($contentType['relations']) && is_array($contentType['relations'])) {
            foreach (array_keys($contentType['relations']) as $relkey) {
                if ($relkey != Slugify::create()->slugify($relkey)) {
                    $contentType['relations'][Slugify::create()->slugify($relkey)] = $contentType['relations'][$relkey];
                    unset($contentType['relations'][$relkey]);
                }
            }
        }
```
The error happens when ```$relkey``` is compared to slugified ```$relkey``` and it doesn't match, after this it unsets my correct foo_bars key and it set an incorrect foo-bars.

Solution?
---------------
My solution currently is to rename the slug value and the relations key to foo-bars and hope it doesn’t break anything elsewhere. 
But it is definitely a bug, because nowhere to be found in the documentation: "do not use underscores in the slug values". :)

My thoughts:

The content type slug (I prefer calling this code) calculation is very weird in Bolt. Using the slugified key (if not numeric) or slug (without! slugify) or slugify the name... it is complicated. Why not using one required value for this purpose?

**Comment by GawainLynch** [comment] 2016-07-28 07:03
So `foo_bar` is related to `foo_bar` … People, I think we're witnessing ContentTypeCeption :wink: 

Seriously though, this is a problem we've been chasing though the code base in a few forms for a while, and in this case might be as smile as just allowing the `_` in the Slugify call.

**Comment by SahAssar** [comment] 2016-07-30 11:49
I think this highlights the need for one db slugifier that is run on every column and table name that goes in the db and every contenttype key, and a separate one that is used for URLs.... That would also ease allowing special/uppercase chars in urls without messing up db keys or column names, which is something that we at intendit do.

**Comment by GawainLynch** [comment] 2016-07-30 11:58
Somewhat easier said than done … but far from impossible. 

We're not very consistent yet with config, so we can absolutely try to patch it in now, but it might be better to make (intermediate) config refactoring go into 3.2 with the exception handling.

**Comment by rossriley** [comment] 2016-08-03 16:06
What's the consensus on approach here, as far as I can see we've always piped the key of a contenttype to slugify, (eg 2.2 branch - https://github.com/bolt/bolt/blob/release/2.2/src/Config.php#L407) 

I think that the default for this is that underscores are replaced with hyphens, so if we have previously allowed underscores to slip through (or perhaps slugify has modified its default regexp along the way) then I don't think this was intended behaviour.

So we can either:
1: Start allowing underscores
2: Document that we don't allow them and throw a more informative error.

**Comment by SahAssar** [comment] 2016-08-03 17:20
:+1: for allowing underscores. We use them in so many places in our config keys and so on, so if I was new I'd assume I could use them in contenttype keys and slugs too.

**Comment by GawainLynch** [comment] 2016-08-03 17:25
Agree with @SahAssar 

Biggest problem is we need to kill the 1.2.1 BC problem with keys vs. slugs. v.s tablenames … that is really starting to hurt

**Comment by rossriley** [comment] 2016-10-05 00:49
Ok, with the final PR in #5853 this should be fixed.

**Closed by rossriley** 2016-10-05 00:49 UTC
Labels: Bug

**Comment by GawainLynch** [comment] 2016-10-05 06:25
A great big thank you from me, @rossriley :+1:
