### ISSUE TITLE
[RFC] As a CMS, wouldn't it be better to move to utf8mb4?

### ISSUE THREAD

**Issue by phoenixgao** [bolt/bolt#4485] opened 2015-11-17 14:39 UTC
Wordpress moved to utf8mb4 since 4.2

https://github.com/WordPress/WordPress/blob/40b303069af246f9c50a0e38e4ab50daf0282d1e/wp-admin/includes/schema.php#L54

Some of bolt users might need publish some contents which include special characters only in utf8mb4?
As I know a lot of Chinese classical poems and names of ancients contains utf8mb4 characters, when trying to save a string contains a character of those into a utf8 field, all data after that character will be lost.

**Comment by bobdenotter** [comment] 2015-11-17 14:43
Since I live in north-western europe, i've not had to deal with multi-byte UTF-8 much. Can you give my an example of what doesn't work currently in Bolt? 

We're of course open to improving this. :-)

**Comment by phoenixgao** [comment] 2015-11-17 14:46
Yeah I will find some examples for you, I also will try to manually change my bolt db to utf8mb4 to see if it breaks... :D

**Comment by bobdenotter** [comment] 2015-11-17 14:50
Great! Keep us posted! :-)

**Comment by PhillippOhlandt** [comment] 2015-11-17 14:58
As I know, emoticons (like in tweets or fb posts) can only be stored in an utf8mb4 database.

Let's imagine someone want to import those tweets or postings.

**Comment by phoenixgao** [comment] 2015-11-17 15:03
Here I found an example character, I hope you won't mind to open some webpage in Chinese ;P

𩔪  <-- This is from a poet's name who lived in Tang dynasty, but I don't know if github would save it after I click "Comment" button.. so here is some links:

http://sou-yun.com/PoemIndex.aspx?dynasty=Tang&author=%E7%8E%8B%EA%88%BE
You might see a big square, looks like 王囗 (I also see a square on Mac because mac font doesn't support this, but it works on my windows pc, but you can copy this character from that page to search on google)，but the "囗" is actually looks like this:

http://www.zdic.net/z/aa/js/2952A.htm
U+2952A

**Comment by phoenixgao** [comment] 2015-11-17 15:05
Yeah emoji characters also have to be stored in utf8mb4

**Comment by xiaohutai** [comment] 2015-11-17 15:15
For me, the characters/emoji work fine in SQLite, but not for MySQL with `utf8_unicode_ci` encoding.

**Comment by bobdenotter** [comment] 2015-11-17 15:15
I see! The name of 𩔪 doesn't show up on Github, but i did get it correctly in my email.. 

@phoenixgao If you could investigate if changing to utf8mb4 wouldn't cause any problems, I'd be interested to hear.

**Comment by PhillippOhlandt** [comment] 2015-11-17 15:18
![Just do It!](http://www.theloop.ca/wp-content/uploads/2015/06/Shia-LaBeouf-really-wants-you-to-justdoit.jpg)

**Comment by rossriley** [comment] 2015-11-17 15:37
The cause from what I remember is because MySQL messed up the utf-8 implementation by restricting the number of bytes that can be stored in a character set. 

Other implementations eg SQLite and Postgres should be fine but not MySQL. I was under the impression that there was something like 64,000 caracters available so should be ok for most languages, but properly implemented utf8 should allow up to 2 million characters.

**Comment by bobdenotter** [comment] 2015-11-17 16:25
I can imagine the amount of issues will increase steadily when testing it on older version of MySQL as well.

**Comment by phoenixgao** [comment] 2015-11-19 00:21
I've created a pull request to make it possible to install tables with the configured charset and collate

https://github.com/bolt/bolt/pull/4498/

**Comment by SahAssar** [comment] 2015-11-19 22:16
Closed in #4498, no?

**Closed by SahAssar** 2015-11-19 22:16 UTC
