### ISSUE TITLE
Error alert when deleting file

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#4854] opened 2016-02-16 05:40 UTC
When i'm trying to delete a file, Bolt shows an error
![2016-02-16 11-37-09](https://cloud.githubusercontent.com/assets/2145313/13068076/b726d832-d4a1-11e5-93ff-9a4b347bf455.png)
but **deletes the file**. But you can't see that file is removed until you reload the page.

**Comment by bobdenotter** [comment] 2016-03-02 10:18
On a fresh Bolt 3 alpha 7 checkout, i can't reproduce this anymore, so i'm going to assume it's been fixed in the meantime. 

Feel free to re-open this issue, if the problem persists after updating Bolt.

**Comment by GawainLynch** [comment] 2016-03-02 10:19
Yeah, this was fixed in #4882 but I missed closing this one at the time!

**Closed by bobdenotter** 2016-03-02 10:18 UTC
Labels: Bug verification needed
