### ISSUE TITLE
[BUG] unable to choose different session storage methods, filesystem hard-coded

### ISSUE THREAD

**Issue by dwolfhub** [bolt/bolt#5534] opened 2016-07-11 16:13 UTC
In the SessionServiceProvider, when gathering options for the Session classes in `registerOptions(Application $app)`, the method ends by adding `$app['session.options']`, effectively hard-coding these values and not allowing me to override them in any way. By switching this line and the ones adding `$app['session.storage.options']` (lines 168-170), we can overwrite the option values in our `.bolt.php` files and customize the way sessions are handled. (PR incoming)

**Comment by dwolfhub** [comment] 2016-07-11 17:05
unfortunately this still doesn't solve my original issue, which was that i wanted to use native php redis sessions... it seems like there could be some work done to this provider to add more flexibility based on different hosting situations.

**Comment by GawainLynch** [comment] 2016-07-12 04:31
Added a comment on #5535 regards that.

As per our conversation on Slack yesterday, this ended up having to be finished too quickly to push 3.0.0 out, so if you have time to dig deeper that would be really useful.

**Comment by CarsonF** [comment] 2016-07-12 15:52
The real problem is bigger than this. Silex/Pimple was designed to define services and parameters _first_, then override default values in a configuration phase. Bolt does/tries to do the opposite, configure everything first, then add services/parameters. It's a huge nightmare on a lot of fronts.

Unfortunately, the right way and our way had to be bridged somewhere, which is where `configure` comes in. Either way though I would expect `session.options` to be overridden after the service provider is registered if needed.

---

`.bolt.php` is still in a new concept. I want to explore it more and add more features, but as @GawainLynch said it was decided to release 3.0. I want to keep that file as small as possible though. It should only be used to bridge your paths/app to the common web endpoint (`index.php`) and `nut`. Features should be added to this file very cautiously. It shouldn't replace a config file.

**Comment by CarsonF** [comment] 2016-07-12 16:03
I'm not sure where `session` gets invoked and therefore freezing the config parameters.
What would work for now is subclassing `Bolt\Application`, and overriding `initSession`. You can update `session.options` before the `session` service gets invoked.

The end goal is clearly defined loading phases where you can override services and parameters in one spot. But we are in transition still from a Service Locator pattern to Dependency Injection, which causes pain for this exact problem.

**Comment by ToBe998** [comment] 2016-08-01 15:03
I just stumbled on this too. Our Bolt2 instances use a clustered memcache session handler. In Bolt2, you could just put `session_use_storage_handler: false` into your config.yml and it worked.
Now in Bolt3, this option is no longer used.

It seems the session handler can no longer be disabled. There seems to be support for memcache sessions by Bolt3 and even the option to parse PHP's session config, but no documentation on how to use this.

This is a bit critical atm as it blocks a couple of new website deployments on our site. Is there any progress or some hack we can use?

**Comment by GawainLynch** [comment] 2016-08-01 16:55
Should be fixed in  #5535

**Closed by GawainLynch** 2016-08-01 16:55 UTC
Labels: Bug, Unfinished functionality
