### ISSUE TITLE
[BUG] Extra </tbody> in listing

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#5008] opened 2016-03-12 05:08 UTC
Looks like in listings (all listings) there's something redundant:
![2016-03-12 11-04-15](https://cloud.githubusercontent.com/assets/2145313/13720990/948005a6-e842-11e5-8857-411ef44e1192.png)

Probably the problem is here
![2016-03-12 11-06-10](https://cloud.githubusercontent.com/assets/2145313/13720993/a0bb12b6-e842-11e5-86cd-0c4316d35473.png)

Does it need investigation?

**Comment by rarila** [comment] 2016-03-12 09:21
Duplicate of #5000

**Comment by SahAssar** [comment] 2016-03-12 14:58
If this is a duplicate it should be closed, so I'm closing it.

**Closed by SahAssar** 2016-03-12 14:58 UTC

**Comment by bobdenotter** [comment] 2016-03-14 15:48
Fixed by #5022
