### ISSUE TITLE
[BUG] Image in field repeater not displaying

### ISSUE THREAD

**Issue by Mikescops** [bolt/bolt#6126] opened 2016-12-03 16:49 UTC
When you use an image field in a repeater field you can't get the {{ field.image }} working.

In fact the output is "Array".

The fix is to use {{ filed.image**.value** }} but I assume this is not a clean solution.

**Comment by SahAssar** [comment] 2016-12-03 18:12
Closing as a duplicate of #5846

**Closed by SahAssar** 2016-12-03 18:12 UTC
