### ISSUE TITLE
php file limit gives 'File does not have an acceptable extension'

### ISSUE THREAD

**Issue by dromer** [bolt/bolt#4603] opened 2015-12-17 08:56 UTC
When uploading a file to Bolt that exceeds the php 'upload_max_filesize' the users gets the error 'File does not have an acceptable extension' which is very confusing (took me quite a while to figure out what was happening).

Please include a more precise/verbose error-message for these situations.

**Comment by SahAssar** [comment] 2015-12-17 09:32
Closing as this is a duplicate of #4291 :)

**Closed** 2015-12-17 09:33 UTC
