### ISSUE TITLE
Image field to be stored as a separate table? 

### ISSUE THREAD

**Issue by DevonshireCow** [bolt/bolt#2059] opened 2014-11-02 03:26 UTC
How should bolt manage a compound field? By this, I mean a set of fields which represent one 'thing'. It's common for a content type to consist of other one or more instances of content types.

Example, an image field is a compound field and is stored as a json object - it has a file and title. This is fine for such a basic object, but if the user had another usecase, and needed to search on, say, file, or by title, they wouldn't be able to. The use of json objects doesn't scale well to other uses, unless of course you're using posgresql which can treat json as objects and allow you to search on its properties.

So, thinking aloud: as an image is a content type, whenever an image is used, it should be stored inside an image table which stores the image properties? or, maybe if a content type has an image field, there should be a contenttype_images table created? As this would be a potential manytomany relationship, either a comma separated list of image ids could be stored in the content type, or a middle table is managed which handles the relationships

The former method would allow extensions to modify the images table for other uses and make the dev's life easier when it comes to using compound fields (one property of a content type, which is actually made up of other fields), and would be totally transparent to the user.

**Comment by bobdenotter** [comment] 2015-01-03 10:47
Closing this as a duplicate of #574

**Closed by bobdenotter** 2015-01-03 10:47 UTC
Labels: feature
