### ISSUE TITLE
templateselect filter in contenttypes.yml has no effect

### ISSUE THREAD

**Issue by jadwigo** [bolt/bolt#4857] opened 2016-02-17 11:28 UTC
The templateselect filter is not working as expected anymore in bolt 3.x in the new themes.

In bolt 2.x it filteded out any templates that are not matching the filter.
https://github.com/bolt/bolt/blob/release/2.2/app/config/contenttypes.yml.dist#L35

**Comment by PhillippOhlandt** [comment] 2016-02-17 11:29
Has you named your templates?

**Comment by jadwigo** [comment] 2016-02-17 11:34
good point - yes, the theme.yml has named templates

**Comment by PhillippOhlandt** [comment] 2016-02-17 11:39
I reported the same a while ago with v2.2.x. Let me search for the long discussion.

**Comment by PhillippOhlandt** [comment] 2016-02-17 11:40
Here:
https://github.com/bolt/bolt/issues/4577

**Comment by bobdenotter** [comment] 2016-03-03 19:37
Closing, because duplicate of #4577 

(workaround: Don't name the templates)

**Closed by bobdenotter** 2016-03-03 19:37 UTC
Labels: Bug, Regression
