### ISSUE TITLE
Previews in backend shows nothing if no image is set

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#4475] opened 2015-11-16 18:59 UTC
![2015-11-17 00-36-36](https://cloud.githubusercontent.com/assets/2145313/11191598/423cf4a2-8cc6-11e5-9e07-ac091f5e519d.png)
address for that image is
![2015-11-17 00-36-52](https://cloud.githubusercontent.com/assets/2145313/11191611/50a7dc8c-8cc6-11e5-8fa8-178b18a87b12.png)

Maybe something else should be there?

**Comment by rarila** [comment] 2015-11-17 00:47
Master or 2.2? I get an preview with ``app/view/img/default_empty_4x3.png`` (e.g. when doing "New page"). It also works as expected when deleting the image.

**Comment by Boorj** [comment] 2015-11-17 08:05
It's 2.3, yes.

**Comment by SahAssar** [comment] 2015-11-23 21:09
Hmm, working for me in both 2.2 and master, are you getting a 500 or 404 (or some other response) on the image?

**Comment by SahAssar** [comment] 2015-12-01 21:53
Closing because it seems like it is a server config issue and no reply has been posted in over a week.

If it turns out to be a bolt issue or an issue with out recommended server setup please reopen! :)

**Comment by Boorj** [comment] 2016-01-24 09:26
it happens when field value is `{"file":""}` that came when file was saved with an error

**Comment by rarila** [comment] 2016-01-24 09:53
Previews are refactored by me at the moment, I just have very limited spare time. Gonna display an error image in this case.

**Comment by SahAssar** [comment] 2016-03-28 14:44
@rarila did anything come of this?

**Comment by SahAssar** [comment] 2016-04-21 21:18
Can't recreate on current bolt 3.0 beta, so closing again... Again, please reopen if it is reproducible!

**Closed by SahAssar** 2016-04-21 21:18 UTC

**Comment by Boorj** [comment] 2016-04-27 07:46
it was when file was set, but empty. So image value in db was  `{file : ''}`.

**Comment by SahAssar** [comment] 2016-04-27 10:12
@Boorj When I set an image, save then remove the image and save I get the value "[]" in the DB.

If I manually set the value to "{file : ''}" in the DB and then open the site I still get the correct error image...

Could you write the exact steps to follow to reproduce the error in a current bolt 3.0beta?

**Comment by Boorj** [comment] 2016-04-27 11:44
ok, @SahAssar it's closed. thank you for cooperation!
