### ISSUE TITLE
Error then uninstall of an extension dsduit/big-picture-html5up - 1.0.0Derk Duit 

### ISSUE THREAD

**Issue by mgageo** [bolt/bolt#4236] opened 2015-10-06 11:01 UTC
In bolt 2.2.12, I have this error when I try to uninstall:
Composer Error
Failed to execute git status --porcelain --untracked-files=no

error: bad index file sha1 signature
fatal: index file corrupt

**Comment by mgageo** [comment] 2015-10-06 11:04
And I have this message in the system log:
Bolt\Composer\Action\RemovePackage::execute recieved an error from Composer: Failed to execute git status --porcelain --untracked-files=no error: bad index file sha1 signature fatal: index file corrupt in /home/nicalala/public_html/vendor/composer/composer/src/Composer/Downloader/GitDownloader.php::109

**Comment by SahAssar** [comment] 2015-10-06 11:26
As this is a duplicate of #3691 I'll close this and open that. Hope that is okay with you @mgageo.

**Closed by SahAssar** 2015-10-06 11:26 UTC
