### ISSUE TITLE
&nbsp; in editor happening in 2.0.5

### ISSUE THREAD

**Issue by peterboorsma** [bolt/bolt#2660] opened 2015-02-01 15:25 UTC
Bolt 2.0.5 apparently still has issues with nbsp stuff.

They appear when editing text in the WYSIWYG editor: backspacing, copying & pasting, entering, etc.
I'm not exactly sure which action mentioned above causes it..

I do know that the editors add their article like this (especially long texts):
Type stuff in a text editor. 
Paste it into the WYSIWYG editor
Use the xT button to discard all shitty code from editors
Save the article
...
(Another) editor opens the article, edits it (by backspacing, copying & pasting, entering, etc.)
Saves it once again.

**Comment by Pinpickle** [comment] 2015-02-02 05:48
This issue may have been hindered/helped by #2486, as it changes how the HTML is outputted.

**Comment by bobdenotter** [comment] 2015-02-04 18:23
Peter mentioned this issue to me before, and it was my hope that it would be fixed with those changes in 2486, but unfortunately it didn't.

**Comment by Pinpickle** [comment] 2015-02-05 06:56
Maybe newer text editors should be looked at? CKEditor just seems so clunky and is only kind of responsive. It also has issues like this one, and from the [research I've done](http://stackoverflow.com/questions/9741620/ckeditor-unwanted-nbsp-characters), it seems unavoidably caused by pasting content - it can be sanitised but then again, the odd user may want nbsps. It's also ugly.

Something like [Redactor](http://imperavi.com/redactor/) or [Quill](http://quilljs.com/) would help keep the text editor current. And to be honest, writing is one of the most important experiences for an average CMS user.

**Comment by GawainLynch** [comment] 2015-02-05 07:51
> Maybe newer text editors should be looked at?

Personally speaking, CKEditor is one of my least favourites...  and would be very keen.

**But** it is going to be a hard one to replace as it needs good functionality, and a lot of it.

> Quill 

Loses "out of the box" as I can't see any way to manipulate images that have been inserted, nor can you view source.

> Redactor 

Much nicer, can view source and some additional image functions.

Breakers (immediately looking) are that it can't handle HTML5 `<figure>` and nothing to edit code...  Like I said, personal :grinning:

**Comment by bobdenotter** [comment] 2015-02-05 08:21
Despite all of its flaws, CKEditor really is the best option as far as I can tell. Most of the newer "sleek" ones break in various unpredictable ways, when you're not using the latest version of Chrome or Firefox. 

Redactor looks nice, but it has a license that is not compatible with Bolt: http://imperavi.com/redactor/download/

**Closed** 2015-02-07 13:08 UTC
Labels: bug

**Comment by peterboorsma** [comment] 2015-02-07 13:24
Thank you very much! I'll let some editors test it.

**Comment by svivian** [comment] 2015-04-02 15:10
This "fix" has created the opposite problem now - every single `&nbsp;` is removed! This means you can't use multiple spaces e.g. to indent lines. As soon as I save, any indentation is removed.
