### ISSUE TITLE
[BUG] record.taxonomy data is different under preview. 

### ISSUE THREAD

**Issue by graham73may** [bolt/bolt#6293] opened 2017-01-24 11:42 UTC
Details
-------

 - Relevant Bolt Version: 3.2.6
 - Install type: Composer install
 - PHP version: 7.0.9
 - Used web server: Apache

Reproduction
------------
 1. **Bug summary**: 
`record.taxonomy` arrays return differently in preview mode, in turn breaking taxonomies outputs in theme files. 

 2. **Specifics**:
`setFromPost()` at
`C:/MAMP/htdocs/nuffieldtrust.org.uk/vendor/bolt/bolt/src/Controller/Frontend.php::210`

Combined with the taxonomy loop at
`C:/MAMP/htdocs/nuffieldtrust.org.uk/vendor/bolt/bolt/src/Storage/Entity/ContentValuesTrait.php::482`

 3. **Steps to reproduce**:
Create a taxonomy with terms that have multiple words, tag some content. 
Dump out record.taxonomy to see the values don't match up. 

This in turn is causing issues as record.taxonomy is being used to show taxonomies and breaks under preview. 

 4. **Expected result**: 
To receive the same array values as when viewing a published item .

![image](https://cloud.githubusercontent.com/assets/6642498/22245799/bb82ad7a-e229-11e6-95bc-36b94f8ec77d.png)

 5. **Actual result**: 
The "slug" values of each taxonomy are returned / displayable.

![image](https://cloud.githubusercontent.com/assets/6642498/22245772/a17310d2-e229-11e6-8093-73805e308ce1.png)

**Comment by bobdenotter** [comment] 2017-01-24 12:18
Duplicate of #6260, although this one has more info.

**Closed** 2017-02-02 15:00 UTC
