### ISSUE TITLE
[WARNING 1549] failed to load external entity

### ISSUE THREAD

**Issue by salacr** [bolt/bolt#3576] opened 2015-05-25 20:39 UTC
Hi, i have found several issues in past but all are closed, I'm using bolt 2.1.9 with czech language enabled and I see error like this.

It's show in dashboard, no special reprosteps are required.

![image](https://cloud.githubusercontent.com/assets/424837/7802046/bec1f008-032e-11e5-91f9-f7e94895dda9.png)

Is there any posibility how to fix it ? Can i assist you?

Thanks

**Comment by GawainLynch** [comment] 2015-05-25 20:46
It is a system error… it can be caused by many things, a small but incomplete list:
* The system doesn't have the PHP php-intl library installed/enabled
* RAID errors
* Your web server doesn't have read permissions on file in `app/resources/` or `vendor/symfony/intl/`

**Comment by salacr** [comment] 2015-05-25 21:00
Thanks,
I checked all you mentioned but nothing helps :(

**Comment by GawainLynch** [comment] 2015-05-26 05:28
How have you installed Bolt?  It looks like the Symfony paths that are failing are the Symfony Framework ones, not the individual module.

On a normal Bolt install, the xml.xsd file is located at `vendor/symfony/translation/Loader/schema/dic/xliff-core/xml.xsd`. Is it possible you have the framework installed as a global package?

**Comment by salacr** [comment] 2015-05-26 06:20
I installed it by composer as 
composer create-project bolt/composer-install pegasreal.salac.org --prefer-dist
the file is present at: 
/var/www/pegasreal.salac.org/vendor/symfony/translation/Symfony/Component/Translation/Loader/schema/dic/xliff-core/xml.xsd

composer.json contains:

{
    "name": "bolt/composer-install",
    "description": "Handles an install of Bolt with a few path customisations.",
    "license": "MIT",
    
    "require": {
        "bolt/bolt": "~2.1",
        "composer/composer": "1.0.*@dev",
        "ircmaxell/random-lib": "dev-master"
    },
    "authors": [
        {
            "name": "Ross Riley",
            "email": "riley.ross@gmail.com"
        }
    ],
    "minimum-stability": "beta",
    "prefer-stable": true,

    "scripts": {
        "post-create-project-cmd": [
            "Bolt\\Composer\\ScriptHandler::bootstrap"
        ]
    },

    
    "extra": {
        "branch-alias": {
            "dev-master": "2.1-dev"
        },
        "bolt-web-dir": "./",
        "bolt-app-dir": "./app"
    }
   
    
}


Thanks for your help! I really apriciate it!

**Comment by Pinpickle** [comment] 2015-05-28 09:09
I had this at one point. I think the cause was that the computer that Bolt was on was running out of space.

**Comment by salacr** [comment] 2015-05-28 09:29
That isn't that problem i have plenty of free space. But thanks for your help. For now i disabled the validation in symfony code (ugly hack) and i try to look at it when i will have some spare time

**Comment by GawainLynch** [comment] 2015-07-28 07:48
Closing as part of a general issue clean up. Please let us know if you find anything more details on the Symfony behaviour.

**Closed by GawainLynch** 2015-07-28 07:48 UTC
