### ISSUE TITLE
Upload files in file manager with less clicks

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#6776] opened 2017-06-27 13:34 UTC
I noticed the following when uploading files trough Bolt (file manager). I first need to click the 'Choose files' button. Then I have to choose the files and click 'Ok' or 'Open' (Windows window). And after that I must click the 'Upload files' button. Why not one button 'Upload file(s)' that opens a windows to select the files?

-------

 - Bolt 3.2.13
 - PHP 7+

**Comment by GawainLynch** [comment] 2017-06-27 13:36
Duplicate of #2263

**Closed by GawainLynch** 2017-06-27 13:36 UTC
Labels: Duplicate
