### ISSUE TITLE
{{ menu() }} fails on POST

### ISSUE THREAD

**Issue by sageamdp** [bolt/bolt#4540] opened 2015-11-28 08:27 UTC
The route that generates the issue is created in an extension controller class. 

    $ctr->get('/tool/edit/{tool_id}', array($this, 'addTool'))
    ->bind('ManageToolEdit')
    ->method('GET|POST')->value('tool_id', -1);

The menu call is being made within `theme/testsite/manage/header.twig`
`{{ menu('manage', 'manage/partials/_admin_menu.twig') }}`

After POSTing information the following crash occurs: 
https://gist.github.com/anonymous/14a171048b7001b21ab3

I've tried to POST via form on the page and from REST client and received the same crash. 

Removing the offending menu() call fixes the issue, but changing the parameters for the parameters for it does not.

**Comment by bobdenotter** [comment] 2015-12-08 12:21
Hi, I can't verify this. Not on master, at least. See the screenshot below. If i request the frontpage over `POST`, the menu displays just fine. 

![screen_shot_2015-12-08_at_13_19_03](https://cloud.githubusercontent.com/assets/1833361/11655505/9821afa4-9dae-11e5-84fa-58e6c4d79fb0.png)

**Comment by SahAssar** [comment] 2015-12-13 10:45
@sageamdp What is that extension that you are using? Just to help recreate the issue :)

**Comment by SahAssar** [comment] 2016-01-03 10:54
@sageamdp Any info on this? 

Just a small FYI, I'm tagging this for closing on the 6th since we need more details to recreate/fix. Looking forward to getting those details so we can get this fixed! :)

**Comment by SahAssar** [comment] 2016-01-06 09:51
Closing per my comment on the 3:rd. Please reopen if this is still an issue for you and you have the info necessary to reproduce! :)

**Closed by SahAssar** 2016-01-06 09:51 UTC
Labels: Bug verification needed
