### ISSUE TITLE
Required mailoptions, TMI on login form

### ISSUE THREAD

**Issue by aerth** [bolt/bolt#4126] opened 2015-09-22 18:51 UTC
![Image of login form](http://i.imgur.com/qdiBqjy.png)
Extension being used is boltforms

**Comment by bobdenotter** [comment] 2015-09-22 19:05
Good catch! Thanks, @aerth

**Comment by GawainLynch** [comment] 2015-09-23 06:56
Duplicate of #3905

**Comment by GawainLynch** [comment] 2015-09-23 06:57
This is a tricky one too as there are flashes that we want to show on that page.

**Closed** 2015-09-28 15:04 UTC
Labels: Duplicate
