### ISSUE TITLE
Setting jQuery File Upload sequentialUploads to true

### ISSUE THREAD

**Issue by aralon** [bolt/bolt#3455] opened 2015-04-26 16:11 UTC
When uploading a lot of files it is very useful if they upload in the order you selected them in. 

From the jQuery File Upload documentation:
> Set this option to true to issue all file upload requests in a sequential order instead of simultaneous requests.
- Type: boolean
- Default: false

https://github.com/blueimp/jQuery-File-Upload/wiki/Options#sequentialuploads

I *think* this is the file that should be changed:
https://github.com/bolt/bolt/blob/master/app/src/lib/jquery-fileupload/main.js

**Comment by rarila** [comment] 2015-04-26 20:29
Not quite: https://github.com/bolt/bolt/blob/master/app/src/js/bind-fileupload.js would be the place to go. ``main.js`` isn't used at all :-)

Question is, if we really want this. Although in the end you get the desired effect it isn't the setting for that purpose. It's for uploading one file after the other and I guess it defaults to ``false`` as it is probably slower than uploading many files at the same time.
Gotta have a look into this, there has to be done some refactoring/updating in this area anyway.

**Comment by Aralon** [comment] 2015-04-26 21:16
After uploading some files, it definitely is a lot slower, because of that, I agree this should stay false, if some users (like me) really need the functionality, they can always override it. 
A 'cleaner' solution to sorting uploaded files would be very nice :)

**Comment by Pinpickle** [comment] 2015-04-27 08:39
A solution that gets the best of both worlds (biggest speed, files in order), would be for the object model used by the client to remember the order the files were uploaded in, and then rearrange them as successful uploads are completed, wouldn't it?

**Comment by rarila** [comment] 2015-04-27 11:47
@Pinpickle Yet again absolutely my thoughts :-)
Just didn't have the time to look into it.

**Comment by rarila** [comment] 2015-11-10 02:37
@aralon Ok, with recent refactorings this can be done now. The problem is, what is the selection order? On Chrome/Windows the last selected file is prepend to the upload list so that you get the reversed order. The upload is queued one by one so reversing the order isn't possible also. Even if that would be possible, I don't know if this reversing behavior is browser or OS dependend or always the case.

**Comment by SahAssar** [comment] 2016-07-26 19:07
@rarila Any good solution to the issue you mentioned Nov 10, 2015? Or is this just one of those that can't be solved by us?

**Comment by rarila** [comment] 2016-07-26 19:29
Can't think of a solution

**Comment by SahAssar** [comment] 2016-07-26 19:33
Righto, closing this for now, perhaps we can make this work when the browser/OS behavior is standardized (if ever :mask: ).

**Closed by SahAssar** 2016-07-26 19:33 UTC
Labels: Enhancement, JavaScript

**Comment by rarila** [comment] 2016-07-26 19:38
That'll be when they sell :icecream: on the :sunny:.
