### ISSUE TITLE
Clearing a templatefields selection doesn't clear the warning

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#4223] opened 2015-10-05 11:14 UTC
Set a templatefields template, then clear it:
![template-problem](https://cloud.githubusercontent.com/assets/1427081/10279047/4f00eea6-6b5a-11e5-9522-a8aeefaae8b4.png)

**Comment by rarila** [comment] 2015-11-10 03:27
That's not an easy one. The whole process is a bit clunky. Not only having to save to get the additional templates field in the beginning but also requiring to reload the page is more than suboptimal. We could either render all possible templates fields as hidden ones and (de-)activate them on selection or get them ajaxy. If you could provide me with an ajaxy hook …
Still not an easy task then with having to add an tab at the right place …

**Comment by SahAssar** [comment] 2015-11-10 20:00
Well, the reload is okay in my mind, the issue is (*was*) that if you set a template with templatefields and then (without a save) reset it to the "default template" option it will still display the warning. I can't reproduce on current master though. The issue here seems to be that it no longer reloads the page when saved and there is a templateselect with template specific fields, no?

**Comment by SahAssar** [comment] 2015-12-13 12:25
Closing since fixed, more fixes in this area coming in #4502 :)

**Closed by SahAssar** 2015-12-13 12:25 UTC
Labels: Blocking release, UX/UI
