### ISSUE TITLE
Overflow of "Storage: No valid contenttype" log messages

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#1799] opened 2014-10-01 15:56 UTC
I am getting 30+ of these per page-load.

```
Storage: No valid contenttype '' / in: [snip]/app/src/Bolt/Storage.php::1691
```

**Comment by gwbonline** [comment] 2015-02-21 10:20
I have the same problem. Every time I reload the frontpage, I get an error:

№ 20
Lvl 1 	Storage: No valid contenttype '' /
in: /httpdocs/src/Storage.php::1688 ()

I deleted everything so only the header and the footer where left. I still get the error No valid contenttype " /. So it must be in the footer or header. The footer doesn't contain a setcontent etc. The header does. But after removing all that code, so the header only contains html, the problem is still there. Is there any other way to track down what's causing this? I tried to implement the above code, but that results in no error in the log (error is still there).

**Comment by GawainLynch** [comment] 2015-02-21 10:23
This was the `menu.yml` containing unresolvable entries.

**Comment by gwbonline** [comment] 2015-02-21 14:41
Yes, but I don't use menu.yml... Even when the frontpage is empty, Bolt notes an error.

**Comment by GawainLynch** [comment] 2015-02-21 14:43
I'm a bit confused. If you don't have a `menu.yml` file Bolt will copy `menu.yml.dist` to `menu.yml` and if you don't have the routes that it defines, it will create these messages.

**Comment by gwbonline** [comment] 2015-02-21 14:46
I have the file, I only don't use it to display a menu. I tried to empty it just now, but Bolt puts in the default code again.

**Comment by GawainLynch** [comment] 2015-02-21 14:57
Oh right! Less confused now :+1: 

It is kind of hard to say without looking at what your frontpage Twig is doing. But what triggers this is some sort of request for a record or contenttype that doesn't exist, maybe the about page or similar.

This one drove me nuts too :grin:

**Comment by gwbonline** [comment] 2015-02-21 19:03
I will look in to it again. It is strange, because even when the frontpage is empty, the problem stays the same. Could it be some setting in a config file? Is it possible to add some code to make the error more specific like you did? 






Van: Gawain Lynch
Verzonden: ‎zaterdag‎ ‎21‎ ‎februari‎ ‎2015 ‎15‎:‎57
Aan: bolt/bolt
CC: Willem Bosm



Oh right! Less confused now  :+1: 

It is kind of hard to say without looking at what your frontpage Twig is doing. But what triggers this is some sort of request for a record or contenttype that doesn't exist, maybe the about page or similar.

This one drove me nuts too  :grin:

**Comment by gwbonline** [comment] 2015-02-22 09:28
I removed all twig code from the header, footer and index files. The error is still noted. Then I checked the config file... nothing strange. And then the contenttype files... also nothing strange. And the menu file... removed all paths. Checked the database, emptied the cache, checked all other template files for content code (although other pages don't produce any error). I get still an error about a content type that is not valid. I can reproduce the same error by introducing a non valid content type on purpose, but after removing it I know for sure that the template files don't contain any more bad content types.

**Comment by gwbonline** [comment] 2015-02-24 08:22
I've done everything in my power trying to solve this. Nothing worked. I think I'm closing my eyes for this and leave it the way it is.

**Comment by bobdenotter** [comment] 2015-02-24 08:29
This will be fixed in Bolt 2.1. Patience, my young Padawan. ;-)

**Comment by gwbonline** [comment] 2015-02-24 08:41
Patience... That's difficult when someone is a perfectionist. I think I'll never become a Jedi... But maybe in the future...

So the problem with no valid contenttype is something I can't correct by editing templates or config files when there is no invalid contenttype set?

**Comment by GawainLynch** [comment] 2015-02-24 08:54
This is triggering badly for me too, from extensions. I am going to reopen this one as all this discussion has migrated here and as @bobdenotter said we'll address this.

**Closed** 2015-02-24 18:14 UTC
Labels: Blocking release, bug
