### ISSUE TITLE
[UX] File Management / Uploaded files / Upload file

### ISSUE THREAD

**Issue by rarila** [bolt/bolt#3018] opened 2015-03-04 22:41 UTC
Just took some time to find out why ``Upload file`` does not work to finally get the :bulb:.

I somehow saw `` Select file …`` and ``Upload file`` as two different things that do not belong together. The former probably something like ``Select from Stack`` or ``Browse Server``. We have some similar combinations elsewhere.

So the question is, is there a reason for having two buttons instead of just ``Upload file`` that fires up the fileselector and on ``Ok`` immediately uploads the file?

**Comment by GawainLynch** [comment] 2015-03-05 07:19
The amount of times this has bitten me!

**Comment by bobdenotter** [comment] 2015-03-05 07:24
> is there a reason for having two buttons instead of just Upload file that fires up the fileselector and on Ok immediately uploads the file?

Because I couldn't get it to work easily. If you can, please fix it. :-)

**Comment by SahAssar** [comment] 2015-10-26 19:40
Duplicate of #2263, no?

**Closed by SahAssar** 2015-10-26 19:40 UTC
Labels: UX/UI
