### ISSUE TITLE
Warning: ini_set(): A session is active.

### ISSUE THREAD

**Issue by bebetodias** [bolt/bolt#6537] opened 2017-04-02 15:46 UTC
My website start to show this message:

 **You cannot change the session module's ini settings at this time in /vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php on line 56**

And I don't know how to solve this issue.

Anyone can help?

**Comment by bobdenotter** [comment] 2017-04-02 16:18
🔮

You'll need to tell us more: 

 - When does this happen? 
 - What version of Bolt?
 - What version of PHP / webserver? 
 - How was it installed? 
 - What caused it to "start to show" this?

**Comment by GawainLynch** [comment] 2017-04-02 16:40
An extension is using session before the request cycle … dis able /remove you extensions and re-enable or re-add one at a time until you find the cause, probably an upstream problem :wink:

**Comment by bebetodias** [comment] 2017-04-02 18:43
**When does this happen?**
This starts two days ago.
**What version of Bolt?**
Version 2.2.8
**What version of PHP / webserver?**
PHP Version 5.4.45
**How was it installed?**
It was installed vis FTP
**What caused it to "start to show" this?**
I don't know what caused... I just access my site and the message was there

**Comment by bebetodias** [comment] 2017-04-02 18:45
When I access my extensions this message is show:

![image](https://cloud.githubusercontent.com/assets/13684326/24590024/6381343a-17bb-11e7-89de-6c1d4563978e.png)

**Comment by bebetodias** [comment] 2017-04-02 21:17
In my php.ini, the directive session.auto_start is On. 
This can be the answer? It must be Off?

I read this here: [http://stackoverflow.com/questions/13539269/errorexception-warning-ini-set-a-session-is-active-you-cannot-change-the-s](http://stackoverflow.com/questions/13539269/errorexception-warning-ini-set-a-session-is-active-you-cannot-change-the-s)

**Comment by CarsonF** [comment] 2017-04-03 16:14
Yes that's the answer. Bolt v2 by default tries to use a different session save handler and this doesn't work if the session is already started.

**Comment by bobdenotter** [comment] 2017-04-04 05:31
Closing this one, because I don't think it's an actual bug (at least not one that's feasible to fix on our end). Feel free to update, if help is needed. 

2.2.8 is pretty old, though. An upgrade to 2.2.24 (or somesuch) should be painless and fix a bunch of quirks.

**Closed by bobdenotter** 2017-04-04 05:31 UTC

**Comment by bebetodias** [comment] 2017-04-04 10:58
I updated to 2.2.24 and ask to my host to change the directive and it works!
Thanks for support!
