### ISSUE TITLE
Environment.php tries to sync unexisting folders and throws an error.

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#4386] opened 2015-11-04 21:32 UTC
calling to @GawainLynch  :leaves: 

I assume this code tries to sync my `root\app\view\*` folders with `root\web\app\view\*`
```php
    // \Bolt\Configuration\Environment::syncViewDirectory
    protected function syncViewDirectory($dir)    {
        //...
        $source = $this->srcRoot . '/app/view/' . $dir; 
        $target = $this->webRoot . '/app/view/' . $dir;
        //...
        $this->filesystem->mirror($source, $target, null, ['override' => true, 'delete' => true]);
        //...
    }
```
So.. points are:
1. in my setup there's no `root\app\view` folder. I've got one in `root\vendor\bolt\bolt\app\view`. 
2. all bolt assets are layed in root\web\bolt-public. So it's strange check.

So working if i turn `syncViewDirectory` off, otherwise :skull: **it dies** with an error in `\Symfony\Component\Filesystem\Filesystem::mirror`

**Comment by GawainLynch** [comment] 2015-11-04 23:04
How are you setting `webroot` ?

**Comment by Boorj** [comment] 2015-11-05 05:35
```php
$configuration->setPath("web", "web");
```
But anyway, i don't have `*/app/view` anywhere except `root\vendor\bolt\bolt\app\view`, so it's still weird to sync with *$target*.

**Comment by GawainLynch** [comment] 2015-11-05 07:35
Why is it weird, it is valid for all our supported configurations… that'd be why they're *supported* :stuck_out_tongue_winking_eye: 

However, you can customise this by overriding `$app['config.environment']` with a class as simple as
```php
class Boorj
{
    public function checkVersion() {}
}
```
As @CarsonF would say, "The beauty of Dependency Injection". :+1: 

Note that it should only get called on version change or first install.

I am however curious as to how/why your set up would trigger an error… 

…and why you would want to expose Bolt `root/vendor/bolt/bolt/app/` to we users, it's not a secure approach.

**Comment by Boorj** [comment] 2015-11-05 08:13
I suppose it has to work for each configuration that could be made with paths customization. :factory: 
So all usages of `->getPath('src')` should be made with assumption, that user can have custom paths. Otherwise - you could put that to docs.

**Comment by rossriley** [comment] 2015-11-05 09:21
Confirmed here as an issue on Composer installs too. 

Root on composer installs always goes to the root of the project and thus has none of the source code available.

Most of this can be fixed by using `$app['resources']->getPath('app')` which is used elsewhere across Bolt to refer to `<root>/app` on standard installs and `<root>/vendor/bolt/bolt/app` on composer installs.

The one thing we don't have a path for (since we currently only access it as a URL) is for the target for public assets so I'd propose to fix this we add a new path accessible via: `$app['resources']->getPath('webassets')` which on standard installs returns the same as the `web` path, but within the Composer configuration returns `web/bolt-public`.

**Comment by Boorj** [comment] 2015-11-05 09:53
Great solution, since it doesn't break anything (i hope). 
i think @rossriley is speaking about `apppath`. In my case it's:

    paths['apppath'] == <root>/vendor/bolt/bolt/app
    paths['app'] == /bolt-public/

Maybe we can even avoid this 'webassets' by using
```php
$web_assets_path = $app['resources']->getPath('web') . $app['resources']->getPath('app');
```

So @GawainLynch 's function can use 
```php
$source_dir = $app['resources']->getPath('apppath');
$target_dir = $app['resources']->getPath('web') . $app['resources']->getPath('app');
```
Or call that as arguments for Environment, depending on how Gawain initialize that..

In my case in seems to be working solution.

**Comment by Boorj** [comment] 2015-11-05 10:01
here's my paths (if interested) : https://gist.github.com/Boorj/6437875c573df38c49e5
(btw, weird `thumbs` path)

**Closed** 2015-11-09 16:25 UTC
