### ISSUE TITLE
[BUG?] info sign after each field title in 3.3.0 RC1 release

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#6848] opened 2017-07-23 12:39 UTC
I installed the 3.3.0 RC1 release and I notice an info sign (gray circle with a white i in it) after each field title. Not every field needs an explanation. Most of them contain no text. Is this a bug or can I disable them?

**Comment by bobdenotter** [comment] 2017-07-23 12:41
Hey @gwbonline, 

Could you post a screenshot of this, along with the contenttype used? I think i know what you're saying, but i'm not seeing this behaviour myself.

**Comment by gwbonline** [comment] 2017-07-23 12:49
Contentype code is an example. All contenttypes show this behaviour.

```
evenementen:
    name: Evenementen
    singular_name: Evenement
    fields:
        titel:
            type: text
            postfix: "Omschrijf met één of maximaal drie woorden het evenement"
            required: true
            class: large
            group: tekst      
        datum:
            type: text
            postfix: "Voorbeeld: 1 april 2017"
        tijd:
            type: text
            postfix: "Voorbeeld: 10.00"
        locatie:
            type: text
            postfix: "Naam locatie en adres. Voorbeeld: Roskam, Dorpsstraat 95, 6681 BM, Bemmel"            
        omschrijving:
            type: html
            height: 150px
            postfix: "Omschrijf het evenement zo volledig mogelijk"            
            required: true
        slug:
            type: slug
            uses: titel
        afbeelding:
            type: image
            postfix: "Let op: alleen liggende foto uploaden, staande foto wordt niet goed weergegeven"
            required: true
            group: media
    taxonomy: [ categorie ]
    record_template: evenement.twig
    listing_template: listing.twig
    listing_records: 10
    default_status: publish
    sort: -datepublish
    recordsperpage: 10
```

![2017-07-23](https://user-images.githubusercontent.com/9332608/28499431-2c429da8-6fb6-11e7-803b-33b370fc1a0a.png)

**Comment by bobdenotter** [comment] 2017-07-23 13:56
Have you cleared the cache? Both in your browser, and the one in Bolt?

**Comment by jackiboy** [comment] 2017-07-23 15:50
Having the same issue as @gwbonline. it's appearing on all content types. Here is my Project content type
```
projects:
    name: Projects
    singular_name: Project
    fields:
        title:
            label: Project Name
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
            postfix: "<p>This is the url the project is located (You do not need to change this).</p>"
        location:
            label: Location
            type: text
            variant: inline
            postfix: "<p>Set Project Location (e.g. Wellington).</p>"
        type:
            label: Project Type
            type: select
            variant: inline
            values: { 'maintenance': "Maintenance", 'residential': "Residential", 'commercial': "Commercial", 'commercial interiors': "Commercial Interiors"}
            postfix: "<p>Select Project Type.</p>"
        image:
            label: Project Image
            type: image
            upload: projects
            postfix: "<p>The main project image that is used on the Home and Projects pages.</p>"
        introbody:
            label: Intro Project Body
            type: html
            height: 150px
            postfix: "<p>The introduction text that sits under the heading.</p>"
        projectimage:
            label: Project Body Image
            type: image
            upload: projects/body
            postfix: "<p>The secondary image thar sits under the introduction body text.</p>"
        decriptionheading:
            label: Description Heading
            type: text
            variant: inline
            postfix: "<p>The heading of the main content (This is optional).</p>"
        description:
            label: Project Body
            type: html
            height: 250px
            postfix: "<p>The main content for the project.</p>"
        gallery:
            type: imagelist
            upload: projects/gallery
            postfix: "<p>If you have multiple images and would like to display them in a gallery upload the images here.<br> The gallery will be displayed under the main content text.</p>"
    taxonomy: [ groups ]
    record_template: project.twig
    recordsperpage: 100
    default_status: publish
    description: '<p style="font-size: 1.5rem; line-height: 1.15em">Edit and create new Projects.</p>'
    icon_many: "fa:wrench"
    icon_one: "fa:wrench"
```
and what shows on the front end.

![screen shot 2017-07-23 at 11 45 14](https://user-images.githubusercontent.com/16835243/28500802-0073353e-6f9d-11e7-8ff4-eac721e0c780.png)

**Comment by gwbonline** [comment] 2017-07-23 18:30
Yes, I have done those standard things when having an issue. Still have an info sign after each field title.

**Comment by larsvansche** [comment] 2017-07-23 20:27
I can confirm it is appearing on every field in RC2 aswell. I also noticed that, regardless of the use of an acutal info attribute in contenttypes.yml, the popup is always empty (see screenshot) 
![image](https://user-images.githubusercontent.com/16673968/28502592-1de38a52-6ff6-11e7-82d2-f41f5f9d5926.png)

**Comment by rossriley** [comment] 2017-07-23 21:55
OK, I've tracked down the issue to this change: https://github.com/bolt/bolt/commit/76b48ff956287a89fa1ceaec94617cc9bc11852a

It looks like Twig returns an empty string for a block even if it's empty in the view.

Whilst the original looks shorter, in the interest of being more explicit then can I suggest we use:

`{% if block('fieldset_label_info') is defined and block('fieldset_label_info') is not empty %}`

for the condition... I've just tested on latest 3.3 and after the change everything reverts to proper behaviour.

**Comment by rossriley** [comment] 2017-07-23 21:58
@GawainLynch sorry meant to ping you in that comment, will my suggestion avoid the exception in newer versions of Twig?

**Comment by bobdenotter** [comment] 2017-07-24 05:05
I've noticed somewhere else too, that blocks always return an empty string, and made a similar change. Here: #6837

Wouldn't `{% if block('fieldset_label_info') is not empty %}` suffice?

**Comment by GawainLynch** [comment] 2017-07-24 05:21
No, the problem here is the macro unless I am missing something … the `defined` just prevent the fatal in v2, `empty` will still trigger it.

Macro abuse is macro abuse :wink:

**Comment by GawainLynch** [comment] 2017-07-24 05:58
@rossriley That might be an adequate "quick fix" but as above the macro mess is going to hit us left and right, so we might get over the line, but we might also be opening a can of worms :laughing:

**Comment by bobdenotter** [comment] 2017-07-24 06:02
I'd say we do the "quick fix" now, because we need to get 3.3.0 over the line. :-)

**Comment by GawainLynch** [comment] 2017-07-24 06:09
That is kinda where I am heading too … but can we combine said quick fix with both testing changes to the macro to see if there isn't a better quick fix, and a few more days of testing of all the things that we're wrestling with?

**Comment by bobdenotter** [comment] 2017-07-24 06:12
I'm really of two minds. You know I'd prefer to make the good solution, but you also know my heart aches at the thought of having to postpone the release again. We've all worked so hard on it, and I really want to have it out before i'm gone for two weeks. :-/

**Comment by GawainLynch** [comment] 2017-07-24 06:19
No, this is not about a "good solution" that is going to take hundreds of hours worth of work. Simple fact, as I pointed out in Slack just now. Tomorrow is not feasible for 3.3.0, and releasing early has hurt us every single time. So there is a :-1: vote on release from me without 6845 merged and tested, another RC and 3 days "in the wild" of said RC.

I fail to see, based on history, that being unreasonable.

**Comment by GawainLynch** [comment] 2017-07-24 10:12
Workaround in #6850

**Closed by GawainLynch** 2017-07-24 10:12 UTC
