### ISSUE TITLE
[RFC] Unexpected behaviour: Tab 'relations' visible but should not

### ISSUE THREAD

**Issue by peterboorsma** [bolt/bolt#6499] opened 2017-03-20 20:08 UTC
When you add a relation field to a contenttype and relations are set in the database, a "relations" tab appears in the editor (screenshot).

If one removes the relation field from contenttypes.yml, the 'relations' tab is still visible in the editor. 
IMHO the 'relations' tab should not be visible when a relation field is removed from contenttypes.yml

```
typen:
    name: Typen
    singular_name: type
    fields:
        title:
            type: text
            class: large
            label: Titel
            required: true
            group: Tekst
        slug:
            type: slug
            uses: title
            group: Tekst
        body:
            type: html
            height: 300px
            label: Uitgebreide tekst
            group: Tekst
    relations:
        verblijfopties:
            multiple: true
            label: Selecteer de verblijfoptie(s) waar dit type bij hoort
```

I did some testing:
When I removed the relations manually in the "bolt_relations" table, the tab dissapeared (obviously).

Bolt 3.2.9

**Comment by GawainLynch** [comment] 2017-07-16 18:39
@peterboorsma just going though issues for clean up, and this one (to me) doesn't make sense. The relations are shown by design when a record _has_ relations. A ContentType doesn't need to define relations to have another ContentType's records related to it … RelationCeption incoming! :rofl: 

I'm going to close this, but please don't hesitate to reopen and throw a virtual fish at me if I have totally missed your point though … It's been known to happen :sweat_smile:

**Closed by GawainLynch** 2017-07-16 18:39 UTC
