### ISSUE TITLE
composer require "bolt/bolt" "~2.0" does not work

### ISSUE THREAD

**Issue by brianseitel** [bolt/bolt#2403] opened 2015-01-04 22:08 UTC
It looks like one of the composer dependencies is out of date. I'm using the latest, greatest version of composer.

```
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - bolt/bolt v2.0.2 requires composer/composer 1.0.*@dev -> no matching package found.
    - bolt/bolt v2.0.1 requires composer/composer 1.0.*@dev -> no matching package found.
    - bolt/bolt v2.0.0 requires composer/composer 1.0.*@dev -> no matching package found.
    - Installation request for bolt/bolt ~2.0 -> satisfiable by bolt/bolt[v2.0.0, v2.0.1, v2.0.2].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

**Comment by GawainLynch** [comment] 2015-01-05 00:22
I've tried on Composer (PHAR) versions `095dc6129550de93cd98170c8e6c6ccd4558e983` & `e172cd81a146666d844d2b7b37b5feccb89e2b61` and can reproduce this.  

Any more clues you might have would be useful.

**Comment by brianseitel** [comment] 2015-01-05 04:52
What other clues do you need? I'm following the instructions from the (Install Bolt With Composer)[https://docs.bolt.cm/installation-composer] page with a fresh installation of composer, Mac OS X Yosemite.

**Comment by rossriley** [comment] 2015-01-05 04:53
This will be a minimum stability problem I guess. Since there is no stable version of composer the only way this will work is if the minimum stability in the root project is set to dev.

The alternative is to explicitly require the @dev version: /composer 1.0.*@dev also in the root package, as soon as this goes down a level of require from the root package it will not include correctly.

**Comment by GawainLynch** [comment] 2015-02-13 19:19
Presuming [fixed by this](https://github.com/bolt/composer-install/pull/1).

**Closed by GawainLynch** 2015-02-13 19:19 UTC
