### ISSUE TITLE
[BUG] select value not persited 

### ISSUE THREAD

**Issue by jemont** [bolt/bolt#5849] opened 2016-10-01 21:52 UTC
select values are not persisted anymore. used to work in Bolt 3.0.12
contenttype:

...
course_id:
            type: select
            values: cursos/title
            group: data
...

i can select an option, but the value is not saved in mysql in Bolt 3.1.1
I used to select by title and the id of that contenttype entry was saved.
I checked in Firefox and Chrome 
no error messages, and the rest of the changes gets saved in the database.

**Comment by bobdenotter** [comment] 2016-10-02 08:15
Are you using underscores in your contenttypes? If so, this is a duplicate of #5601

**Comment by jemont** [comment] 2016-10-02 12:30
yes i had an underscore in there. sorry for that.
strange #5601 is related to Bolt 3.0.11 on Bolt 3.0.12 it was working for me

**Comment by GawainLynch** [comment] 2016-10-02 12:35
Yeah … it is something we've been chasing in circles to work around, due to legacy BC requirements.

We have a series of fixes implemented, as we'll iterate them until 3.3 where I am working on replacing the configuration loader.

I am going to close this one to keep the signal ratio high, but please feel free to subscribe to #5601 for updates on our progress.

**Closed by GawainLynch** 2016-10-02 12:35 UTC
Labels: Duplicate
