### ISSUE TITLE
Error in taxonomy listing

### ISSUE THREAD

**Issue by HonzaMikula** [bolt/bolt#3803] opened 2015-07-14 22:31 UTC
I use categories taxonomy in articles, but now it stop working listing of particular taxonomy. I get this error.
```
Controller "Bolt\Controller\Frontend::taxonomy()" requires that you provide a value for the 
"$request" argument (because there is no default value or because there is a non optional 
argument after this one).
```
It has something to do with routing I guess, but I have no idea, what to do. Because I didn't change routing for taxonomy listings. It's default.

Does anybody know what is the issue? Thanks.

**Comment by HonzaMikula** [comment] 2015-07-14 22:32
http://www.honzamikula.cz/categories/skolni-odmlouvani

**Comment by GawainLynch** [comment] 2015-07-15 03:24
Bug confirmed… We'll look into this right away.

**Comment by GawainLynch** [comment] 2015-07-15 03:25
What version of Bolt are you running? I just got this on master (which is under heavy development) but 2.2.4 works.

**Comment by HonzaMikula** [comment] 2015-07-15 09:20
I checkout to release branch 2.2 and it's occur me there too.

**Comment by GawainLynch** [comment] 2015-07-15 13:04
I am scratching my head here as I think the cause would be different between master and release/2.2 as the whole controller/routing layer has been refactored in master.

Did anything change recently in your `contenttypes.yml`, `taxonomy.yml` or `routing.yml`?

**Comment by HonzaMikula** [comment] 2015-07-15 20:31
Okay, I install the version 2.2 again and it's work there. Sorry for bothering a thanks.

**Comment by GawainLynch** [comment] 2015-07-16 15:03
No bother at all mate, at least we now know that there is something specific to be fixed in master before the next release… So if anything, thank you! :+1:

**Closed** 2015-10-04 11:48 UTC
Labels: Blocking release, Bug, Regression
