### ISSUE TITLE
"ScriptHandler::installAssets" takes a _long_ time on sites with a large `public/files/` folder

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#5719] opened 2016-08-30 17:27 UTC
Bumped into this the other day: A site with a large `public/files/` folder (several dozen `.jpgs` of 4 - 6 mb each) takes a long time for the `ScriptHandler::installAssets` part of the install / update procedure. 

Eventually it craps out on a random line in our EXIF library, seemingly indicating that the folder is crawled, while there's no apparent need for it. 

Needs verification, though. 
## Details
- Relevant Bolt Version: [ 3.1 ]
- Install type: [ Composer install ]

**Comment by CarsonF** [comment] 2016-08-30 17:31
I can look into this

**Comment by GawainLynch** [comment] 2016-08-30 17:42
Assigning to you then, @CarsonF if you can before "you know what" :wink:

**Comment by nbehier** [comment] 2016-08-30 17:56
@CarsonF @GawainLynch What are you planning ? You're teasing us ! Not cool ;)

**Comment by GawainLynch** [comment] 2016-08-30 17:57
Well, I am pretty sure I know why… so if @CarsonF doesn't have time this week, I'll get it next week when I am off the island. :smile:

**Comment by CarsonF** [comment] 2016-08-30 17:59
@nbehier I'm getting married this weekend 💪  👫   🎉 

I'll probably just point @GawainLynch to the problem if I find it so he can fix it lol

**Comment by GawainLynch** [comment] 2016-08-30 18:01
The problem is :koala: :koala: :koala: :koala: :koala: :koala: :koala: :koala: 

In other news, we now have drop bear emoji on Slack :laughing:

**Comment by nbehier** [comment] 2016-08-30 18:42
@CarsonF I don't want to say it too soon… but hope you'll have one of your best weekend ;-)

**Comment by GawainLynch** [comment] 2016-09-17 18:19
Nudge @CarsonF

**Comment by GawainLynch** [comment] 2017-02-24 12:46
Given he six months since this was seen, I'm retiring this… I ma pretty sure this was due to massive `app/cache/profiler/` directories from long running `debug: true` settings … we both know where the "Reopen" button is if I am wrong … not an unusual occurrence :smile

**Closed by GawainLynch** 2017-02-24 12:46 UTC
Labels: Bug verification needed
