### ISSUE TITLE
can't login to admin panel

### ISSUE THREAD

**Issue by kur1977** [bolt/bolt#4523] opened 2015-11-23 19:38 UTC
Hi. I start to using Bolt on my projects and haven't problems before. I installed it on new hosting and have login problem. When I press login button it just doing something and no login. At same time the frontend stops working at all. It no responses. It takes up to 1-2 minutes (i think php time_limit doing his work)and then frontend begin responding, but bolt  is not logging me to backend.
here is the link http://planet-x.com/finesites

**Comment by kur1977** [comment] 2015-11-23 19:47
I look in the browser settings and see that cookie of admin token and session are created. But I can't login

**Comment by GawainLynch** [comment] 2015-11-23 19:50
A couple of questions:
1. What version of Bolt are you running?
2. Do you have a proxy in between you and the server?

**Comment by kur1977** [comment] 2015-11-23 19:56
1) 2.2.13
2) I don't know. I am not using proxy. But I'm in one country and the server is in another country.

**Comment by GawainLynch** [comment] 2015-11-23 20:02
Awesome… we've made a lot of changes in master, so I wanted to make sure you were not hitting a new bug there!

What can happen if you have a proxy of some sort in the middle then IP addresses can change randomly and we use the source IP for authentication cookies.

What is worth a try, is [setting these](https://github.com/bolt/bolt/blob/release/2.2/app/config/config.yml.dist#L339-L341) to `false` and see if that makes a difference.

**Comment by kur1977** [comment] 2015-11-23 20:04
sometimes it happens as I described before and sometimes It just clerars the form fields with no messages.

I tried this before posting an issue. Have no results.

**Comment by GawainLynch** [comment] 2015-11-23 20:05
OK, next thing to check is the PHP session directory is writable by the web server and you're seeing new `*.sess` files getting written.

**Comment by kur1977** [comment] 2015-11-23 20:06
I will look at this. give me 5 minutes

**Comment by kur1977** [comment] 2015-11-23 20:12
I cant see that because of shared hosting. I have access only to website root via ftp

**Comment by kur1977** [comment] 2015-11-23 20:12
in phpinfo I see

**Comment by kur1977** [comment] 2015-11-23 20:13
open_basedir	/var/www/vhosts/shum.kz/:/tmp/
session.save_path	/var/lib/php/session

**Comment by kur1977** [comment] 2015-11-23 20:14
may be this is the problem?

**Comment by GawainLynch** [comment] 2015-11-23 20:14
Yes, the `session.save_path` is not included in the `open_basedir` so sessions won't work

**Comment by kur1977** [comment] 2015-11-23 20:25
in phpinfo I see

session.use_cookies	On	On
session.use_only_cookies	On	On
session.use_trans_sid	0	0

session.use_only_cookies	On - no session files needed

**Comment by GawainLynch** [comment] 2015-11-23 20:28
Bolt uses the session files for a lot.

Also with authentication, it doesn't assume that because you have a cookie you're supposed to have it, to prevent things like Man In The Middle attacks.

**Comment by kur1977** [comment] 2015-11-23 20:30
So, I have to ask my hosting providet to add /var/lib/php/session to open_basedir or completelly disable open_basedir?

**Comment by GawainLynch** [comment] 2015-11-23 20:31
The won't disable `open_basedir` but you can ask them to set your session directory up for you to somewhere that is accessible

**Comment by kur1977** [comment] 2015-11-23 20:32
Ok. thank you for you help. You are the best!

**Comment by GawainLynch** [comment] 2015-11-23 20:35
We try my friend, we try :grin:

**Comment by SahAssar** [comment] 2015-11-23 20:45
Closing cause fixed by the awesome @GawainLynch!

**Closed by SahAssar** 2015-11-23 20:45 UTC

**Comment by kur1977** [comment] 2015-11-24 12:10
My hosting provider make session session.save_path visible for me.
So, I see - session files are present there. But steel can't login.

**Comment by bobdenotter** [comment] 2015-11-24 13:03
- What browser are you using? 
 - Have you tried on another computer and/or another browser? 
 - Are you _sure_ javascript is enabled, and no adblockers, cookie-washers or virus-protection is interfering with your cookie settings?

**Comment by kur1977** [comment] 2015-11-24 13:10
My hosting provider jus do something and now it works. What thay do - thay don't want to say )))

**Comment by kur1977** [comment] 2015-11-24 13:11
Close please

**Comment by bobdenotter** [comment] 2015-11-24 13:28
The issue is closed already.. Glad it works, but perhaps you could ask them again what they did. It would be good to update this issue for when then next person stumbles upon this issue. :-)

**Comment by kur1977** [comment] 2015-11-28 16:44
The problem was because disabled curl_multi_exec in php.ini
They enable it and all begins to work

**Comment by SahAssar** [comment] 2015-11-28 16:46
@kur1977 Thanks for posting the solution!

**Comment by kur1977** [comment] 2015-11-28 17:16
Many hosting providers are disabled curl_multi_exec on VPS.
Do you planinig to replace it in you code by something else in the future?
