### ISSUE TITLE
Hardcoded cache path causes fatal error

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#4590] opened 2015-12-13 13:51 UTC
*Bolt v3*
I use custom cache path (`app/vars/cache`) since it's allowed.
After upgrade i had a problem with https://github.com/bolt/bolt/blob/master/src/Extensions.php#L209
```
$this->app['filesystem']->put('app://cache/.local.autoload.built', time());
```
![2015-12-13 19-50-27](https://cloud.githubusercontent.com/assets/2145313/11767283/ab066998-a1d2-11e5-8a65-f1ccd12647d3.png)
(sorry for big image :v:)

I had to chmod in `vendor/bolt/bolt/app/cache` for temporary fix.

**Comment by SahAssar** [comment] 2015-12-13 13:52
Related/duplicate of #4406?

**Comment by GawainLynch** [comment] 2015-12-13 13:53
Possibly related… but also potentially showing a break in the work that @CarsonF and I are working on… just delayed on the extension stuff.

**Comment by Boorj** [comment] 2015-12-13 13:54
Not sure. That was in script handler, so i wrote my own script handler and using that.

**Comment by CarsonF** [comment] 2015-12-14 16:05
Yes @Boorj you're right. This should be `cache://` instead of `app://cache/`. Feel free to locate other code like this. Other than `translations`, there should be no usage of the `app` path. Planning on removing it in 4.0.

**Comment by Boorj** [comment] 2015-12-21 17:37
thanks, @CarsonF , i will - sometimes i doubt - to report or not.

**Comment by GawainLynch** [comment] 2016-02-02 18:19
This code doesn't exist any longer, is this still a problem?

**Comment by Boorj** [comment] 2016-02-03 06:23
think this one is closed and not causes errors anymore(can't check now)

**Comment by GawainLynch** [comment] 2016-02-03 06:24
OK, reopen if needed. Thanks @Boorj

**Closed by GawainLynch** 2016-02-03 06:24 UTC
Labels: Blocking release, Bug
