### ISSUE TITLE
[Bug] Cannot use HTML inside Bolt V3 Extension Templates

### ISSUE THREAD

**Issue by cdowdy** [bolt/bolt#5301] opened 2016-05-11 16:53 UTC
# [Bug] Cannot use HTML inside Bolt V3 Extension Templates  

if you add HTML inside any template for an extension in the ```templates/``` directory it gets escaped and rendered as an HTML entity in the themes template

Details
-------

 - Relevant Bolt Version: [  3.0 ]
 - Install type: [ Composer install ]
 - PHP version: [ 5.6.11 ]
 - Used webserver: [ Apache 2.4.16  ]

Reproduction
------------

 1. **Bug summary**:  

If you pass any twig variable to the template and use html in the template you'll get the HTML entity rendered. 

 2. **Steps to reproduce**:  

* composer install bolt 3.0  
* create a local directory in ```extensions```  
* create a vendor name inside ```local```. ie: ```extensions/local/myName```  
* composer install extension starter extended:  
  * ```composer create-project --no-install bolt/bolt-extension-starter-extended:^3.0 < ext name >```  
  * you will probably need to run ```composer update``` in the extension directory to get ```wikimedia/composer-merge-plugin``` in order for your local extension to actually register  
* create ```extension.twig``` if it doesn't exist  
* add ```<p>``` tags and ```{{ something }} ``` to match the ```myTwigFunction``` in the Extensions main file.  
```twig  
<p>{{ something }}</p>  
```  
* call the twig function in your theme template: ie. index.twig  
```twig  
{# index.twig  in theme/base-2016/index.twig #}  
{{ my_twig_function() }}  
```  
 4. **Expected result**:  
a random number would be rendered onto the page. 
 5. **Actual result**:   
the random number is rendered but with entities.  
![bolt-extension-yada](https://cloud.githubusercontent.com/assets/5969974/15188982/6f031eae-1776-11e6-9185-ed6952ce5bd7.PNG)  

If you add "is_safe" in the register function   
```php  
 protected function registerTwigFunctions()
    {
        $options = ['is_safe' => ['html']];

        return [
            'my_twig_function' => ['myTwigFunction',  $options ]
        ];
    }  
```  

you can get the expected output if you add "|raw" filter to the function:  
```twig 
{{ my_twig_function()|raw }}  
```  

In Bolt < 3 you can have html, javascript what have you inside the template file. As of bolt 3 you cannot unless you add the raw filter.   

as a hastily added addtion. Installing bolt this way and creating a local extension you will not be able to serve any assets from the web directory or from the public/web/vendor/file.css directory. It gets appended with a query string

**Comment by GawainLynch** [comment] 2016-05-11 17:29
> Installing bolt this way and creating a local extension you will not be able to serve any assets from the web directory 

This will be fixed in time, but I would just like to note that local extensions are, and always have been, a developer hack… they are not meant to be "easy mode".

**Comment by GawainLynch** [comment] 2016-05-12 04:25
OK… Got 5 minutes to have a look, and test.

This is the same as Bolt v1 & v2, the problem is in the implementation. The example extension has been updated https://github.com/bolt/bolt-extension-starter-extended/commit/9562dff4a63e6ef4dbdbf6833fb53c6b4e1b0d54

**Closed by GawainLynch** 2016-05-12 04:25 UTC

**Comment by cdowdy** [comment] 2016-05-12 13:15
@GawainLynch thanks! I should have noticed the utf stuff was gone!

**Comment by bobdenotter** [comment] 2016-05-12 14:08
Shouldn't we make it so that `$this->renderTemplate()` returns a `\Twig_Markup` object instead of plain text?

**Comment by GawainLynch** [comment] 2016-05-12 14:26
@bobdenotter what if one doesn't need `\Twig_Markup`?

**Comment by bobdenotter** [comment] 2016-05-12 14:32
Isn't this specifically geared towards extensions, creating HTML, to be output in a template? 

Not saying you're wrong, but i'd think the opposite (needing plain text) isn't the exception. And those people could simply use `(string) $this->renderTemplate()` or `$app['render']->render()`.

**Comment by GawainLynch** [comment] 2016-05-12 14:41
My question was posed more as a general thought exercise… But something just doesn't feel quite right, can't put my finger on it…
