### ISSUE TITLE
Removing CMS permissions from user causes infinite loop

### ISSUE THREAD

**Issue by RuudBurger** [bolt/bolt#2653] opened 2015-01-31 21:38 UTC
I have 2 user-roles (`client`, `registered`) who I want to block from everything in the CMS (`/bolt/`) and I have 1 `admin` role that can edit all content.

```
global:
  about: [ everyone ] # view the 'About Bolt' page
  activitylog: [ admin ]
  clearcache: [ admin ]
  contentaction: [ admin ]
  dashboard: [ admin ]
  dbcheck: [ admin ]
  dbupdate: [ admin ]
  dbupdate_result: [ admin ]
  extensions: [  ]
  extensions:config: [  ]
  fileedit: [ admin ]
  files:config: [  ]
  files:theme: [  ]
  files:uploads: [ admin ]
  files: [ admin ]
  prefill: [  ]
  profile: [ everyone ] # edit own profile
  settings: [ admin ]
  translation: [  ]
  useraction: [ admin ] # enable/disable/delete
  useredit: [ admin ] # user settings
  users: [ admin ] # view user overview
  roles: [ admin ] # view the roles overview  
  maintenance-mode: [ everyone ] # view the frontend when in maintenance mode
  omnisearch: [ admin ]
  # The following permissions are particularly important: login and postLogin
  # determine who may see and use the login form. If you set them to anything
  # but 'anonymous', only users will be able to log in that are logged in
  # already, which is probably never what you want.
  login: [ anonymous ]
  postLogin: [ anonymous ]
  # Likewise, 'logout' needs to be granted to 'everyone', otherwise people
  # cannot log out anymore.
  logout: [ everyone ]

contenttype-all:
  edit: [ admin ]
  create: [ admin ]
  publish: [ admin ]
  depublish: [ admin ]
  delete: [ admin ]
  change-ownership: [ admin ]

contenttype-default:
  edit: [ admin ]
  create: [ admin ]
  change-ownership: [ admin ]
  view: [ admin ]
  frontend: [ admin ]
```

This seems to cause an infinite loop in the cms part after login with either the `client` or the `registered` user
How can I make the CMS part inaccessable for the 2 users but still let them redirect properly after login (to the last page they where on for example)?

**Comment by bobdenotter** [comment] 2015-02-07 11:26
Dumb question.. Why would people need to log in, while they're not allowed to do _anything_?

**Comment by RuudBurger** [comment] 2015-02-07 11:35
They are allowed to do stuff, just not in the bolt-cms part. It would be stupid to build another login system outside of Bolt, with role based permissions etc.

**Comment by bobdenotter** [comment] 2015-02-11 20:30
First of all, let me say that I'm not trying to b annoying here.. But I _am_ curious how you'd use this. I like to understand how people use our little project. :-)

**Comment by RuudBurger** [comment] 2015-02-11 20:37
I have an auction site. 
1. Where there is an admin that can edit all the content. 
2. And "auctioneers" that can put up auctions (which the admin needs to validate first). 
3. Then there are "bidders" that can fill in a price and their info. 

I don't mind the admin having the default bolt interface, but both the auctioneers and the bidders will have their custom front-end (after login). They don't "manage content" the same way the admin does it in the CMS. They need to get a list of their own stuff (what they put up and what they bid on). 
All this stuff will be custom forms and listing, but still needs permissions validation / form checking etc.

**Comment by CarsonF** [comment] 2015-02-21 18:33
The problem is we don't check for permissions to `dashboard` before redirect them there after login. Then the get there and get stuck in a loop because they don't have permission.

**Comment by bobdenotter** [comment] 2015-02-22 11:50
Is this fixed in #2867 ?

**Comment by CarsonF** [comment] 2015-02-22 16:21
No its not....I hope to get a PR in today.

**Comment by bobdenotter** [comment] 2015-02-25 07:49
This is fixed by @CarsonF.

**Comment by bobdenotter** [comment] 2015-02-26 18:38
(╯°□°）╯︵ ┻━┻

**Closed** 2015-02-27 06:41 UTC
Labels: Blocking release, bug
