### ISSUE TITLE
[BUG] (local) extension assets are not synced to public folder

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/bolt#5103] opened 2016-03-30 11:18 UTC
I installed Bolt with the `create-project` command and created a local extension with the normal starter-extension. 

After renaming all namespaces and files and executing `app/nut extensions:setup`, the extension was shown in the backend and seems to be loaded correctly. At least a `dump('foo');` worked fine.

The starter extension contains a CSS and a JS file, which are registered inside the extension.
```
protected function registerAssets()
    {
        // Add some web assets from the web/ directory
        return [
            new Stylesheet('extension.css'),
            new JavaScript('extension.js'),
        ];
    }
```

But they won't be synced to the `public/extensions` folder.

Details
-------

 - Relevant Bolt Version: 3.0.0 beta 1
 - Install type: Composer install
 - PHP version: 7.0
 - Used webserver: php dev server

**Comment by SahAssar** [comment] 2016-03-30 13:47
Duplicate of #4047, closing.

**Closed by SahAssar** 2016-03-30 13:47 UTC
