### ISSUE TITLE
BUG: CFSR token

### ISSUE THREAD

**Issue by mattiaslundback** [bolt/bolt#5246] opened 2016-04-27 11:37 UTC
Getting errors when posting new entries

Details
-------

 - Relevant Bolt Version: [ 3.0 beta 3 ]
 - Install type: [ Zip/tarball install ]
 - PHP version: [ 5.6]
 - Used webserver: [ Apache ]

Reproduction
------------

When I post a new entry, I often get an error related to wrong CSFR-token. This happens on several different computers. I noticed this problem exist on Bolt 2.18, but this is Bolt 3.0 beta 3 so I guess its a new bug.

It happens from time to time. Have tried to provoke the error again to get the error-log, but of course when you want it to happen it doesn't :-) Thought I still report it. I will get back here with more info when I encounter the error the next time.

**Comment by GawainLynch** [comment] 2016-04-27 12:54
This will happen if there is write problems to the session directory… In v3 we've moved that to `app/cache/.session/` so should be less of a problem.

**Comment by mattiaslundback** [comment] 2016-04-28 09:02
Ah, I will check the permissions on the server also then. It usually works alright, but sometimes fails. But not that often.

**Comment by GawainLynch** [comment] 2016-04-28 09:10
Seems to be legitimate and related to #5250

**Comment by GawainLynch** [comment] 2016-04-28 10:04
Not related to #5250 after all :disappointed:

**Comment by bobdenotter** [comment] 2016-05-12 20:37
Pretty sure this is fixed in the meantime. I can't reproduce anymore.

**Comment by SahAssar** [comment] 2016-05-12 21:09
I can't reproduce either... I'm going to close this, if it can be reproduced on the proper 3.0 release please reopen!

**Closed by SahAssar** 2016-05-12 21:09 UTC
Labels: Bug verification needed
