### ISSUE TITLE
support for internal links on the menu

### ISSUE THREAD

**Issue by serweb-labs** [bolt/bolt#2358] opened 2014-12-24 10:48 UTC
I refer to the anchors and internal links eg #about.
By putting in menu.yml  ```path: "page/home/#cart"
```, when rendering the menu is not taken into account if the item is in the same page, the behavior is to take to a new page.

I think it could be implemented in the macro menu (_sub_menu.twig
) Sample template Bolt 2.

It is missing when creating pages of many kinds "one page" sections, but some sections have their separate page.

Thanks :D

**Comment by bobdenotter** [comment] 2015-01-03 11:15
Isn't this a duplicate of one of the other menu-related issues? #771. The issue here is that `page/home` is _not_ a link or URL. It just refers to a single record.

**Comment by serweb-labs** [comment] 2015-01-03 13:52
I am addressing the wrong way, it seems that really was sleepy when writing the snippet, because the error is there is a bar more before the hash symbol.

Really, I wish the main menu function well throughout the site even if it contains links to sections on the same page,  bad solution, but it works.
```path: "page/home#cart" ```

Sorry to waste your time.

**Closed** 2015-01-03 13:53 UTC
Labels: feature
