### ISSUE TITLE
[Bug] Unable to update imagelist captions after update from 2.2.17 to 2.2.20 

### ISSUE THREAD

**Issue by saltpeanuts** [bolt/bolt#5269] opened 2016-04-30 17:37 UTC
After updating Bolt from 2.2.17 to 2.2.20 I can no longer edit imagelist captions. Having the same problem locally with wamp (php 5.5.12) and with shared Linux hosting (Apache 2.4.18 - php 5.5.33)

**Steps to Reproduce:**

- Have a content type with an imagelist field
- Download bolt latest 2.2.20 zip from Bolt.cm
- Update Bolt from 2.2.17 to 2.2.20
- Edit record to change image caption
- Save record 

**Expected Result:**

On saving, the caption should be updated.

**Actual Result:**

Caption reverts to its previous value.

**Comment by SahAssar** [comment] 2016-04-30 19:27
Have you done a hard reload to make sure that you have the new JS files? Cause this looks a lot like a variation of #5159...

**Comment by saltpeanuts** [comment] 2016-04-30 19:58
I cleared the cache and checked the database after updating, is there something else I should be doing?

I mentioned the problem to Bob on Slack a couple of days ago and he requested I open an issue here.

**Comment by saltpeanuts** [comment] 2016-04-30 20:28
Hard reload seems to fix in Chrome but not Firefox 45.0.2 normal or safe mode. No js errors in console.

**Comment by saltpeanuts** [comment] 2016-04-30 21:08
Just tried a fresh install of Firefox 46 on a different machine and getting the same problem.

**Comment by GawainLynch** [comment] 2016-04-30 21:13
Unable to reproduce here… do you have any extensions installed?

**Comment by saltpeanuts** [comment] 2016-04-30 21:16
Yes, but tried in safe mode and on different machine with fresh install of Firefox, same problem.

**Comment by GawainLynch** [comment] 2016-04-30 21:19
My bad… I was thinking/meaning Bolt extensions … but good call on the browser ones.

**Comment by saltpeanuts** [comment] 2016-05-01 00:02
Ah, ok. Had the same issue on two sites, one using Bolt Forms, the other with no extensions.

**Comment by nbehier** [comment] 2016-05-01 09:46
Get the same problem on my side. When I look ajax call content (`xxx?returnto=ajax`), json form data do not get the updated `title` value, so the issue seems to be on JS side.

**Comment by jlainvolve** [comment] 2016-05-10 16:59
I have this issue in FireFox and in Safari, but it does not seem to affect IE (11) or Chrome.

**Comment by SahAssar** [comment] 2016-05-11 07:04
Bug confirmed, I'll hopefully have a fix later today

**Comment by SahAssar** [comment] 2016-05-11 07:33
Okay, just recompiling the JS seems to fix this for me which is odd since there does not seem to have been any commits to the source files between the last compilation and v2.2.20... Could anyone else try that too to make sure that I'm not just in "pre-coffee" mode?

**Comment by GawainLynch** [comment] 2016-05-11 07:35
Erm… #5295 ?

**Comment by SahAssar** [comment] 2016-05-11 07:57
@GawainLynch I meant between the compiled files that went into 2.2.20 and the release of 2.2.20. In other words, checking out v2.2.20 and recompiling (so the source files still don't have #5295 in them) seemed to fix it.

**Comment by SahAssar** [comment] 2016-05-11 08:08
Wait, nevermind, we recompiled the JS files on the 20:th and 2.2.20 was released on the 19:th. So while the #5159 fix for this issue is is in the source files in 2.2.20 it is not actually in the compiled ones.

So perhaps we should do a 2.2.20pl1 or 2.2.21 to get this fix out there... @bobdenotter ?

**Comment by SahAssar** [comment] 2016-05-11 17:03
Alright, This was actually fixed in #5159, but the code never made it into the minified/compiled files. We are going to put together a 2.2.21 release very soon, but we will try to get a fix for #5170 into that release too.

Since this issue is fixed (although only shipped in the source files) I'm going to close it, and if anyone has the same issue in 2.2.21 when it is released feel free to give me a good ribbing about it :smile:

**Closed by SahAssar** 2016-05-11 17:03 UTC
Labels: 2.2 LTS issue, Bug
