### ISSUE TITLE
[BUG] Video field does not work (sometimes) when used w/markdown (+ repeater?) field

### ISSUE THREAD

**Issue by dantleech** [bolt/bolt#5470] opened 2016-06-21 21:51 UTC
When I add a video field on a contenttype with a markdown field the "refresh" button does not work and the video metadata is not retrieved. If I remove the markdown type it works as expected.

**edit**: This does work with only a markdown and video field, will try and narrow the problem down.

Cannot reproduce this at the moment, the full contenttype is:

``` yaml
footype:
    name: homepages
    singular_name: Homepage
    fields:
        # main
        title:
            label: Titre
            type: text
            class: large
            group: Foobar
            default: Some default
        subtitle:
            label: Sous-titre
            type: text
            group: Foobar
            default: Some default

        # présentation
        presentation_title:
            label: Titre
            type: text
            class: large
            group: Présentation
            default: Qui Sommes Nous?
        presentation_subtitle:
            label: Sous-titre
            default: Foo
            type: text
            class: large
            group: Présentation
            default: Présentation

        # actualities
        actualities_title:
            label: Titre
            type: text
            class: large
            group: Actualités
            default: Actualités
        actualities_subtitle:
            label: Sous-titre
            default: Foo
            type: text
            class: large
            group: Actualités
            default: Présentation

        # prez-de-chez-vous
        chezvous_title:
            label: Titre
            type: text
            class: large
            group: Règions
            default: Près de chez vous!

        soutenir_title:
            label: Titre
            type: text
            class: large
            group: Soutenir
            default: Près de chez vous!
        soutenir_subtitle:
            label: Sous-titre
            default: Foo
            type: text
            group: Soutenir
            default: Ensemble soutenons la recherche
        soutenir_items:
            label: Links
            type: repeater
            group: Soutenir
            limit: 3
            fields:
                title:
                    label: Titre
                    type: text
                    default: Devenir Adhérant
                image:
                    label: Image
                    type: image
                    extensions: [ gif, jpg, png ]
                content:
                    label: Contenu
                    type: textarea
                link:
                    label: Lien
                    type: text

        # misc
        youtube_title:
            label: Chaine Youtube
            type: video
            group: Youtube
```

Will have to investigate again later

**Comment by GawainLynch** [comment] 2016-06-21 21:52
You are my new favourite person, because you are so honest … love it :+1:

**Comment by dantleech** [comment] 2016-06-21 21:53
:) don't know why I end up hitting the enter key prematurely when writing bolt issues :P

**Comment by SahAssar** [comment] 2016-06-21 21:55
hehe, getting those emails certainly keeps me alert, so I don't mind :smile:

**Comment by rarila** [comment] 2016-06-22 02:50
Any JS errors?

**Comment by dantleech** [comment] 2016-06-22 08:09
TypeError: b is undefined bolt.js:9:29387

Is there a way to use the non-minified JS?

**Comment by GawainLynch** [comment] 2016-06-22 08:26
You can [recompile the JS with sourcemaps turned on](https://github.com/bolt/bolt/blob/release/3.0/app/src/README.md) and that will give you accurate details

**Comment by SahAssar** [comment] 2016-07-25 22:39
@dantleech I can't reproduce, are you still seeing this in the latest bolt version?

**Comment by dantleech** [comment] 2016-07-25 22:45
@seanhussey will check

**Comment by dantleech** [comment] 2016-07-25 22:46
@SahAssar will check

**Comment by SahAssar** [comment] 2016-11-08 17:47
Can't reproduce anymore, closing, if still present in the latest bolt please reopen!

**Closed by SahAssar** 2016-11-08 17:47 UTC
Labels: Repeater
