### ISSUE TITLE
[BUG] login page shows database update warning

### ISSUE THREAD

**Issue by jadwigo** [bolt/bolt#4899] opened 2016-02-24 14:15 UTC
If there are pending database updates they are displayed on the login screen.

![image](https://cloud.githubusercontent.com/assets/1488214/13287762/e7e6c44c-db08-11e5-9032-a3ffca48d99f.png)

That message should not be there.

Also, there's some redundancy in the "You have been logged out" and "Please log on" messages.

Details
-------

 - Relevant Bolt Version: 3.0
 - Install type: Composer install
 - PHP version: 5.6
 - Used webserver: Nginx
 - For UX/UI issues: all

**Comment by GawainLynch** [comment] 2016-02-24 14:16
Redundant redundancy is becoming redundantly redundant!

**Comment by jadwigo** [comment] 2016-02-24 14:48
Many abundantly clear and descriptive explanations later we still have much information telling us the same thing :)

**Comment by bobdenotter** [comment] 2016-02-24 19:27
Thinking about this, I think the proper solution would be to only allow _specific_ flash messages on the logon screen. 

I can fix this, and will add the fix to #4881, because it influences the same bit of code.

**Comment by EJanuszewski** [comment] 2016-02-24 21:24
The database message also stays popped up after updating it(on the database update page), I might open a separate issue for this.

**Comment by bobdenotter** [comment] 2016-02-25 09:02
Fixed by #4881.

**Comment by jadwigo** [comment] 2016-03-01 16:57
The following screen pops up _after_ you ran the database update.

![image](https://cloud.githubusercontent.com/assets/1488214/13434609/c52b0080-dfd6-11e5-8b87-d5d473ec8251.png)

So if you need a database update and you go to the update page the notice is hidden and the update button is shown. After you click on the button to update the database the upgrade notice is shown again as well as the 'up to date' notice.

**Comment by bobdenotter** [comment] 2016-03-01 19:37
@jadwigo The original issue (showing it on the dashboard) is fixed. The one you're seeing now is a duplicate of #4912

**Closed by bobdenotter** 2016-03-01 19:37 UTC
Labels: Blocking release, Bug
