### ISSUE TITLE
Storage Event functions return null on POST_DELETE

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/bolt#4248] opened 2015-10-09 11:48 UTC
Hey,

When I listen on `POST_DELETE` I get `null` on `getId() ` and `getContentType()` but a little piece of data from `getContent()`.

Here is what I get:

```
{
  "id": null,
  "contenttype": null,
  "record": {
    "id": "2",
    "slug": "bla",
    "datecreated": "2015-10-09 11:36:55",
    "datechanged": "2015-10-09 11:38:28",
    "datepublish": "2015-10-09 11:36:52",
    "datedepublish": null,
    "templatefields": "[]",
    "username": "",
    "ownerid": "1",
    "status": "draft",
    "title": "bla",
    "image": "",
    "teaser": "",
    "body": "",
    "template": ""
  }
}
```

My code:

```
$this->app['dispatcher']->addListener(\Bolt\Events\StorageEvents::POST_DELETE, array($this, 'onPostDelete'));
```

```
public function onPostDelete(StorageEvent $event)
    {
        if (!is_null($this->pusher)) {
            $data = [
                'id' => $event->getId(),
                'contenttype' => $event->getContentType(),
                'record' => $event->getContent(),
            ];

            $this->pusher->trigger('records', 'deleted', $data);

        }
    }
```

Bug or just wrong on the docs?
https://docs.bolt.cm/extensions/essentials#adding-storage-events

**Comment by GawainLynch** [comment] 2015-10-09 11:50
On stable or master?

**Comment by PhillippOhlandt** [comment] 2015-10-09 11:52
On v2.2.13.
Same on `PRE_DELETE` event.

**Comment by GawainLynch** [comment] 2015-10-09 12:00
I checked the [docblock in the event class](https://github.com/bolt/bolt/blob/release/2.2/src/Events/StorageEvent.php#L24-L37) and I had marked ID as being available.

However, you'll see in [`deleteContent`](https://github.com/bolt/bolt/blob/release/2.2/src/Storage.php#L420) that is fetching an array not an object… #3442 makes more sense now.

**Comment by PhillippOhlandt** [comment] 2015-10-09 12:12
Hmm, but then [this line](https://github.com/bolt/bolt/blob/master/src/Events/StorageEvent.php#L68) is wrong. It should access it as array.

**Comment by GawainLynch** [comment] 2015-10-09 12:17
Actually, I would argue that the change in #3442, and [this line](https://github.com/bolt/bolt/blob/release/2.2/src/Storage.php#L420) are wrong and we should be fetching the record object.

@bobdenotter can you remember if there was a valid reason it was done this way in `Storage::deleteContent()`

**Comment by PhillippOhlandt** [comment] 2015-10-09 12:19
Ah yes, you are right. Any chance to fetch the contenttype of the deleted record?

**Comment by GawainLynch** [comment] 2015-10-09 12:26
Well `findContent()` just does a database look up, so an un-hydrated `getContent()` makes sense at that point… potentially :grin:

**Comment by SahAssar** [comment] 2015-10-15 09:57
Please take note that there is also a discussion about the events open in the forums: https://discuss.bolt.cm/d/9-dispatchers-listeners-continuation-of-1914-4246

**Comment by SahAssar** [comment] 2016-03-01 22:11
Closing since it's a duplicate of #4269, please reopen if I'm wrong :)

**Closed by SahAssar** 2016-03-01 22:11 UTC
Labels: Unfinished functionality
