### ISSUE TITLE
Search is broken for many records

### ISSUE THREAD

**Issue by xiaohutai** [bolt/bolt#2850] opened 2015-02-17 17:13 UTC
Tested in Bolt 1.6.13 and Bolt 2.0.6, so it's been here quite a while. If you add lots of dummy records (e.g. 100 entries and 100 pages, using SQLite), and use the search function, you'll get an error. The search function is quite an old implementation, so we might want to re-write the search functionality anyway. If anyone with experience has good ideas?

![error](https://cloud.githubusercontent.com/assets/4630335/6233032/6682354c-b6d0-11e4-81da-b1a8c8695b07.png)

**Comment by GawainLynch** [comment] 2015-02-17 17:34
Duplicate of #2409 and being looked at as part of the upcoming refactor.

**Comment by bobdenotter** [comment] 2015-02-17 19:19
I disagree that this is a duplicate. It's a different bug.

**Comment by GawainLynch** [comment] 2015-02-17 19:24
Logged in versus not when I was testing it here.

**Comment by xiaohutai** [comment] 2015-02-17 19:24
@bobdenotter I think it is the same. Too many results -> error.

It's a good opportunity to re-write (the search part of) the Storage class..

**Comment by bobdenotter** [comment] 2015-02-17 19:29
No, it really isn't! :-)

The former is about the user's perception: Searching for "De Kift" yields different results than he expects.. Namely for results containing only "De" or "Kift". The error that appears afterwards is definitely an error, but is NOT what peter's issue was about.

**Comment by GawainLynch** [comment] 2015-02-17 20:50
Ah, OK. Yes reading it hard.

What I did (and I am guessing the same is true for @xiaohutai) was to click on the links that @peterboorsma included in that issue, got the errors (as that site now has more content) and made the assumption that the errors were the problem.

Either way, can we also move this to 2.2 as there is quite a bit of work involved in fixing this?

**Comment by jkazimir** [comment] 2015-02-18 03:51
Gave a quick look, and although a refactor sounds like a great plan for that bit of code, it may be possible to at least have this bug patched for 2.1.

The key to a short term fix seems to be here: https://github.com/bolt/bolt/blob/master/src/Storage.php#L653-L668

The quick fix would be to prevent duplicates in appending on to `$filterWhere`, or even a good ol' `array_unique()` on the finished array.

I suppose if so motivated, similar columns could be grouped into an `IN`, but that can probably wait for a refactor. ;)

**Closed** 2015-02-20 09:28 UTC
Labels: Blocking release

**Comment by peterboorsma** [comment] 2015-02-20 12:25
Sorry, I don't get this thread. Will it be solved in 2.1?

**Comment by GawainLynch** [comment] 2015-02-20 12:28
> Sorry, I don't get this thread. Will it be solved in 2.1?

Yes, @xiaohutai committed the fix 3 hours ago

**Comment by peterboorsma** [comment] 2015-02-20 12:29
Ah, thanks Gawain :)
