### ISSUE TITLE
[BUG] HTML field in repeater

### ISSUE THREAD

**Issue by dantleech** [bolt/bolt#5469] opened 2016-06-21 21:35 UTC
When using the HTML field type in a repeater the html editor is shown twice and the fields do not update.

In order to reproduce this you must add at least two "sections" and save the content.

![boltbug](https://cloud.githubusercontent.com/assets/530801/16247039/e023fad2-37ff-11e6-959a-536f37af2791.png)

with configuration:

```yaml
        soutenir_items:
            label: Links
            type: repeater
            group: Soutenir
            limit: 3
            fields:
                title:
                    label: Titre
                    type: text
                    default: Devenir Adhérant
                content:
                    label: Contenu
                    type: html
                image:
                    label: Image
                    type: image
                    extensions: [ gif, jpg, png ]
                link:
                    label: Lien
                    type: text
```

**Comment by dantleech** [comment] 2016-06-21 21:39
Works with the markdown type.

**Comment by saltpeanuts** [comment] 2016-06-22 13:10
I think this is essentially the same issue as #5427

**Comment by SahAssar** [comment] 2016-07-25 22:26
@saltpeanuts You're right, thanks! :) Closing this as it is a duplicate of #5427

**Closed by SahAssar** 2016-07-25 22:26 UTC
