### ISSUE TITLE
Bug: Reordering images in an ImageList

### ISSUE THREAD

**Issue by tomntech** [bolt/bolt#3473] opened 2015-05-02 11:22 UTC
Using the default page template in 2.1.8 I have added an ImageList field. When I have uploaded n number of images I want to reorder them. This functionality appears to be supported through drag and drop, however, when I drag and drop an image the page moves around too much to make the functionality useful.

This problem occurs on OSX, Chrome.

**Comment by Aralon** [comment] 2015-05-03 09:50
Also experiencing these problems, when I try to drag & drop an image, the page keeps scrolling down. Is that what you mean?
This does seem to be a chrome problem, because sorting in FF works fine.
I am on Windows, chrome btw

**Comment by tomntech** [comment] 2015-05-03 17:34
This is the same issue yes. I have just tried it on Safari and I get the same results. I will give FF a try at a later date.

**Comment by bobdenotter** [comment] 2015-05-05 12:31
Confirmed.. Perhaps @rarila knows what causes this, otherwise we'll have to dig in..

**Comment by rarila** [comment] 2015-05-05 18:50
@bobdenotter I'll put that one on top of my JS refactorings todo list. Either I find some problems while putting the code into the mixin or it even just is solved by the refactoring itself.

**Comment by bobdenotter** [comment] 2015-05-06 06:01
Took the liberty of assigning it to you, @rarila ;-)

**Comment by rarila** [comment] 2015-05-06 06:38
There's the link to that "YOU!" meme? ;-)

**Comment by rarila** [comment] 2015-05-24 15:49
That is probably a JQuery UI bug

**Comment by rarila** [comment] 2015-05-24 17:42
Ok, confirmed. Didn't found a 100% fitting bug report but it seems to be quite old and still not solved. So I have no hope.

The problem is solved – I bet you would never have searched for the cause in this place – if the remove the line ``overflow-y: auto;`` [here](https://github.com/bolt/bolt/blob/master/app/src/sass/modules/_bolt.scss#L9).

Question is, is that line here for a reason? I'm open for input!

**Comment by bobdenotter** [comment] 2015-05-24 17:49
I'm willing to bet `overflow-y: auto;` is there for some IE8 quirk. I'd say let's "fix" it by removing this line.

**Closed** 2015-05-25 13:49 UTC
Labels: Browser, Bug, Javascript

**Comment by Largo** [comment] 2015-06-05 08:42
Thanks for fixing it and keep up being awesome! Had the same problem. I'd recommend merging this into a release quickly. It wasn't in 2.2 ._.
(There's another bug btw. ctrl-v always trigers the imagefield, trying to upload my text)

**Comment by rarila** [comment] 2015-06-09 13:19
@Largo Could you please open an new issue for the other bug?
