### ISSUE TITLE
Filemanager inserts "%5C" (backslash) in filepath when more then 1 level deep on Windows machines

### ISSUE THREAD

**Issue by westerworld** [bolt/bolt#2537] opened 2015-01-23 21:15 UTC
Problem on Windows localhost:
Filemanager inserts backslash as "%5C" in filepath as separator when more then 1 level deep.
So I am not able to upload to subfolders of files/ and the thumbs have a wrong href/url.
The same happens when editing e.g. a page and I want to insert from the stack.
The thumb gets a 404 but after saving the page I can click-enlarge the correct image.
And see it in all it's glory.

href-examples:
files/
http://dev.bolt.nl/thumbs/1000x1000r/agriculture-cereals-field-621.jpg

files/filessub1/
http://dev.bolt.nl/thumbs/1000x1000r/filessub1%5C20140906_223017.jpg

Apache access log: 127.0.0.1 - - [23/Jan/2015:21:47:42 +0100] "GET /thumbs/54x40c/filessub1%5C20140906_223017.jpg HTTP/1.1" 404 1236

I am able to create and traverse these subfolders through Filemanager though.

Research:
I installed Bolt205 on my Windows 7 localhost using XAMPP which I use for development of several PhP websites and applications.
I use name based virtual hosting and never had problems with that.
After having the Filemanager problem I FTP'ed the whole Bolt205 site to a Linux based system at my hosting provider.
No problems at all with multi-level sub-directories.
I then FTP'ed the whole site back to my other machine with a Windows XP XAMPP installation.
Problem re-occured there.

So, I conclude it has to do with how Windows reports the filestructure to the Filemanager.
Especially when creating href's for thumbs at any sub-level of files/.
I do have extension=php_fileinfo.dll enabled in my php.ini.

Can anyone point me in the right direction and how to debug maybe?
I did notice a Windows subdirectory of vendor/bolt/pathogen/src but not sure how to proceed.

Greetings,
Harm Wester

Specs:
Bolt205
Windows 7 and Windows XP
ApacheFriends XAMPP Version 1.8.3
  + Apache 2.4.4
  + MySQL 5.5.32 (Community Server)
  + PHP 5.5.3 (VC11 X86 32bit thread safe) + PEAR

**Comment by GawainLynch** [comment] 2015-01-23 21:24
Do you have any ideas, @rixbeck ?

**Comment by rixbeck** [comment] 2015-01-25 10:24
I'm going to try to reproduce therefore I need your patience a bit. At first hand I suspect something string based path construct against pathogen somewhere. Coming back as soon as I catch.

**Comment by rixbeck** [comment] 2015-01-29 17:07
Sorry @westerworld, still can't solve with this because was unable to tune up my windows VM 1,5 days long. I hope at weekend could check it what happens.

**Comment by westerworld** [comment] 2015-01-29 21:19
Ok @rixbeck I understand.
Do you need any more info from me right now?

**Comment by rixbeck** [comment] 2015-01-30 09:41
Not actually. First I got to reproduce then will see. Thanks.

**Comment by westerworld** [comment] 2015-02-02 15:19
@GawainLynch @rixbeck 
I did some additional thinking over the weekend.
This is my conclusion or hunch.
I may be wrong but I still think it's worth sharing because I really do think that a lot of potential Bolt-interested developers would like to have it running on XAMPP locally.
 
Pathogen is, or can be made aware on which OS it is running, UNIX or WINDOWS.
That is important when you want to run e.g. VIM or some other native program on such a machine.

But, in the case of Bolt, Pathogen should not take into account on which OS it is running because we want to treat each path (absolute or relative) in UNIX style since we are accessing "everything" through a webserver.

Therefore, in the case of Bolt, I think Pathogen should always return UNIX-style paths with forward-slashes regardless of the OS it thinks it's running on.

Does this make sense?
If so, can the solution be found in changing src/Library.php or will that not be "deep" enough?

I tried to add (line 102): $filename = str_replace("%5C", "/", $filename);
in the public static function safeFilename($filename)
but that did not seem to be enough when creating new subfolders.

**Comment by tobias2k** [comment] 2015-02-02 15:26
It's actually one level of abstraction further than this.

File paths should always be treated according to the semantics of the
underlying OS, so using '\' on Windows would be correct.

URLs, or more specifically, the path components of HTTP URLs, however,
should always follow the semantics of HTTP URLs, and those mandate
forward slashes.

The problem is not that either end does the wrong thing; the problem is
that we're not mapping between the two properly, and this doesn't
surface more often because most of the time both domains work roughly
the same, especially when your server runs some flavor of Unix.

On Mon, Feb 02, 2015 at 07:19:38AM -0800, Harm Wester wrote:
> @GawainLynch @rixbeck 
> I did some additional thinking over the weekend.
> This is my conclusion or hunch.
> I may be wrong but I still think it's worth sharing because I really do think that a lot of potential Bolt-interested developers would like to have it running on XAMPP locally.
>  
> Pathogen is, or can be made aware on which OS it is running, UNIX or WINDOWS.
> That is important when you want to run e.g. VIM or some other native program on such a machine.
> 
> But, in the case of Bolt, Pathogen should not take into account on which OS it is running because we want to treat each path (absolute or relative) in UNIX style since we are accessing "everything" through a webserver.
> 
> Therefore, in the case of Bolt, I think Pathogen should always return UNIX-style paths with forward-slashes regardless of the OS it thinks it's running on.
> 
> Does this make sense?
> If so, can the solution be found in changing src/Library.php or will that not be "deep" enough?
> 
> I tried to add (line 102): $filename = str_replace("%5C", "/", $filename);
> in the public static function safeFilename($filename)
> but that did not seem to be enough when creating new subfolders.
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/bolt/bolt/issues/2537#issuecomment-72474237

-- 
Tobias Dammers - tobias@twokings.nl - 070-3457628 - www.twokings.nl
Maandag t/m donderdag van 9.00 tot 17.30
Voor dringende vragen, mail naar support@twokings.nl

**Comment by GDmac** [comment] 2015-02-14 11:41
i added \Dumper:dump($files) in backend::files L1658 and 
the filesystem returns ``subdir1\koala.jpg`` (i.e. backslash)
Following tobias here "path components of HTTP URLs ... should use forward slashes"
The filesystem returns system paths.

**Comment by GDmac** [comment] 2015-02-14 12:29
I'm just leaving this breadcrumbs here, 
in the backend::files method the ``$url`` is fetched, which traces back to the filesystem [publicUrl plugin](https://github.com/bolt/bolt/blob/master/src/Filesystem/Plugin/PublicUrl.php#L17), and there the ``$prefix`` is simply concatenated with ``$path`` (which on Win is backslash-delimited)

Might be as simple as ``str_replace('\', '/', $path)`` if there is never a backslash in filenames anyway.

**Comment by westerworld** [comment] 2015-02-15 16:24
Bolt 206
Ok, I do not know how to contribute officially, so here it goes.
I added 1 line of comment and 1 line of code to: 
src/Filesystem/BrowsePulgin.php @ public function handle()
@line 39
            //Added the next line:
            $entry['path'] = str_replace("\\","/",$entry['path']);

And the problem seems solved.
Hope this helps.

The first few lines of the function now read:

    public function handle($path, Application $app)
    {
        $files = array();
        $folders = array();
        $list = $this->filesystem->listContents($path);

        $ignored = array(".", "..", ".DS_Store", ".gitignore", ".htaccess");

        foreach ($list as $entry) {

            if (in_array($entry['basename'], $ignored)) {
                continue;
            }

            //Added the next line:
            $entry['path'] = str_replace("\\","/",$entry['path']);
etcetera..

Greetings,
Harm

**Comment by westerworld** [comment] 2015-02-15 20:26
Sorry
In the code snippet is the correct statement.
An escaped backslash replaced by one forward slash.

**Comment by bobdenotter** [comment] 2015-02-15 20:40
Hi Harm, 

I took the liberty of formatting your comment, so the code snippets display better. We'll check out your solution. Thanks for looking into this! ^_^

**Comment by GDmac** [comment] 2015-02-16 10:01
IMO the issue goes a bit deeper, and should best be addressed in 
the /src/filesystem/publicUrl plugin (Bolt FlySystem plugin). That should return an url, not a path.
See comment above

**Closed** 2015-02-16 19:03 UTC
Labels: Blocking release, bug
