### ISSUE TITLE
[2.2.5+] Bolt generates empty translator cache when installed with menueditor

### ISSUE THREAD

**Issue by SahAssar** [bolt/bolt#3948] opened 2015-08-10 14:02 UTC
### Description
When bolt is installed in conjunction with menueditor (and presumably any extension using app['translator']) it generates an empty translation cache. Not even the fallback locale is included in the cache.

#### Details

This only happens with other locales than en_GB (tried en_GB, sv_SE and nl_NL).
This does not happen if the extension is installed via /bolt/extend.

Clearing the cache via app/nut does not fix the issue.
Clearing the cache via the backend route /bolt/clearcache seems to fix the issue until one changes the locale, then it reappears again.

The issue is in release/2.2 and versions 2.2.8, 2.2.7, 2.2.6 and 2.2.5.

2.2.4 and down does not have the issue.

Master does not seem compatible with the menueditor.

Perhaps https://github.com/bolt/bolt/pull/3753 is to blame? The timeline fits.

What the empty cache looks like (in case of sv_SE):

    <?php
     
    use Symfony\Component\Translation\MessageCatalogue;
     
    $catalogue = new MessageCatalogue('sv_SE', array (
    ));
     
    $catalogueSv = new MessageCatalogue('sv', array (
    ));
    $catalogue->addFallbackCatalogue($catalogueSv);
     
    $catalogueEn_GB = new MessageCatalogue('en_GB', array (
    ));
    $catalogueSv->addFallbackCatalogue($catalogueEn_GB);
     
     
    return $catalogue;

### To recreate:

    git clone git://github.com/bolt/bolt.git "brokencache"
    cd "brokencache"
    git checkout v2.2.8
    composer install --no-dev
    php app/nut extensions:install bacboslab/menueditor 2.1.4
    php app/nut config:set locale "sv_SE"
    
Then go to the login screen and you will see translation keys instead of the proper translation (or the english fallback).

### Workaround:

If you install with some sort of script you can use cURL to clear the cache automatically. Example where $1 is your domain:

    curl -b /tmp/cookie -c /tmp/cookie --data "username=YOURUSERNAME&password=YOURPASSWORD&action=login" http://$1/bolt/login

    curl -b /tmp/cookie -c /tmp/cookie http://$1/bolt/clearcache

**Comment by GawainLynch** [comment] 2015-08-10 14:05
I am guessing you're right, that #3753 (a backport #3671) is causing something funky here.

**Comment by GawainLynch** [comment] 2015-08-10 15:50
This is caused by MenuEditor as it makes the initial call to the translations too early… I have submitted a PR to move that to a middleware handler and that resolves the issue in my testing.

**Comment by GawainLynch** [comment] 2015-08-13 15:41
Fixed in #3953

**Closed by GawainLynch** 2015-08-13 15:41 UTC
