### ISSUE TITLE
BUG: Installing extensions - V2.2.4

### ISSUE THREAD

**Issue by tomntech** [bolt/bolt#3798] opened 2015-07-13 17:33 UTC
When trying to install a new extension I receive a 500 (Internal Server Error) - lib.min.js:26 and Uncaught SyntaxError: Unexpected token < - extend:1 in the developer console.

This is repeatable on a production server and a local environment. 

It appears, if left for a small period of time, an entry gets put into the extensions list above. Clicking "Install All Packages" allows the install to complete successfully.

**Comment by SahAssar** [comment] 2015-09-29 19:45
@tomntech: Does this still happen for you as of v2.2.11?

If so, could you check the network tab of your devtools and see if the issue is that bolt inserts HTML snippets into the JSON response?

**Comment by SahAssar** [comment] 2015-10-01 19:44
Going to close this, please reopen if this still happens in current versions of 2.2!

**Closed by SahAssar** 2015-10-01 19:44 UTC
Labels: Bug
