### ISSUE TITLE
Custom listing templates don't include app path

### ISSUE THREAD

**Issue by RuudBurger** [bolt/bolt#2631] opened 2015-01-30 13:19 UTC
Looking at the example at https://github.com/bolt/bolt/blob/master/app/view/twig/custom/listing/pages.twig.dist#L3 I tried adding my own template for listing of backend content types in `/app/view/custom/listing/{contenttype}.twig`

This however doesn't work as the path `/app/` isn't included in the twig include path.
The only `addPath` that is called for twig I can find here: https://github.com/bolt/bolt/blob/master/src/Application.php#L408 which on a composer-install is the path to `/vendor/bolt/bolt/app/view`.

If I do the following after `$app->initialize()`, everything works like expected (and like https://github.com/bolt/bolt/blob/master/app/view/twig/custom/listing/pages.twig.dist#L3 says):

```php
$configuration->setPath("my_app_path", "app");
$app->extend(
	'twig.loader.filesystem',
	function(\Twig_Loader_Filesystem $filesystem, $app) {
		$filesystem->addPath($app['resources']->getPath('my_app_path') . '/view');
		return $filesystem;
	}
);
```

**Comment by CarsonF** [comment] 2015-01-30 15:35
Are you trying to change the way the backend renders? Because that's not officially supported. 

I think you are missing a folder there in that path though. 
It should be `/app/view/twig/` which is added here: https://github.com/bolt/bolt/blob/master/src/Config.php#L689

**Comment by RuudBurger** [comment] 2015-01-30 15:51
Yeah I'm trying to change the view in the backend. Is this something still in progress? As the functions and folders are there, but pointing to an empty folder https://github.com/bolt/bolt/tree/master/app/view/twig/custom/listing inside vendor (something I'm not touching as it isn't in my version control).

https://github.com/bolt/bolt/blob/master/src/Config.php#L689 is pointing to the theme/themenamed/view/twig/. Adding custom/listing/{contenttype}.twig does nothing.

**Comment by CarsonF** [comment] 2015-01-30 15:58
How did you install Bolt? Composer or distribution or git?

PS: I love CouchPotato :+1:

**Comment by RuudBurger** [comment] 2015-01-30 16:03
Using composer. So the folder structure is like below. With the fix in the index.php on my initial post. It uses the `bids.twig` just fine, but it feels like I'm not doing it the correct way ;)
![screen shot 2015-01-30 at 17 01 29](https://cloud.githubusercontent.com/assets/38136/5978652/a7cc991c-a8a1-11e4-82e1-a3ec2390d606.png)

And thanks! ;)

**Comment by CarsonF** [comment] 2015-01-30 16:14
There are no twig paths in the core that you'll be able to use for backend templates, so you'll have to add that path yourself. You'll see different paths are added based on whether the request is frontend or backend. I have plans to change this but for 2.0 or 2.1. 

I'm iffy on template selection though based on content types. Feel free to jump on IRC, we can talk about it more. The guys will probably have more info for you. freenode #boltcms

**Comment by RuudBurger** [comment] 2015-01-30 16:24
Yeah I was on irc, which got me to this answer.
I was expecting it to be an option in contenttypes config to select the columns shown in the backend. I think that would be a lot cleaner.

The contenttype doesn't have a title or body, so the "title / excerpt" column show `(untitled)`

**Comment by CarsonF** [comment] 2015-01-30 16:38
I agree. @bobdenotter what do you think about this?

**Comment by rarila** [comment] 2015-01-30 17:48
As @CarsonF said, it's
``/app/view/twig/custom/listing/<contenttypeslug>.twig``
not
``/app/view/custom/listing/{contenttype}.twig``

(Sorry, if I missed something, I just rushed over ths thread)

**Comment by CarsonF** [comment] 2015-01-30 17:49
@rarila He installed as a composer dependency though, so he cannot modify `/app/view/twig/`. Hence why I said he needs to add his own folder

**Comment by rarila** [comment] 2015-01-30 17:58
Ok, I never wanted it this way (#1769), but at that time I well behaved and did what Bob wants ;-)

**Comment by CarsonF** [comment] 2015-01-30 18:00
The other half of the problem is only half of the templates are loaded with each request (backend/frontend).

I want to add them all after namespacing them

**Comment by rarila** [comment] 2015-01-30 18:05
As for the idea of just selecting the columns… I don't like it. This way it's much more flexible as you can format and layout as needed, something you probably want to do when you need this feature.

The only problem with it is the location, someting I always said.

Perhaps I'll find some time…

**Comment by CarsonF** [comment] 2015-01-30 18:06
I wasn't suggesting removing the custom template feature, just adding custom columns as a shortcut.

**Comment by bobdenotter** [comment] 2015-02-11 16:04
Ok, so is this actionable? ;-)

**Comment by rarila** [comment] 2015-02-11 16:09
@bobdenotter probably not yet. I feel frozen :snowflake: at the moment ;-)

**Comment by CarsonF** [comment] 2015-02-11 16:10
I think this should be addressed in 2.2 with the twig namespace changes

**Comment by CarsonF** [comment] 2015-02-11 16:11
Well adding the folder path that is. Not sure about the column stuff

**Comment by GawainLynch** [comment] 2015-07-28 08:17
Closing as part of a general issue clean up.

**Closed by GawainLynch** 2015-07-28 08:17 UTC

**Comment by DavidOliver** [comment] 2017-06-08 16:38
I'm trying to hide the entry ID column and am finding that `/app/view/twig/custom/listing/slides.twig` isn't being picked up. I installed [using the command line](https://docs.bolt.cm/3.2/installation/install-command-line). I couldn't get the PHP in the issue description above to work in `/public/index.php`. Is this not possible because of my having used Composer?

I also think an option to show and hide specific fields for each content type would be very useful.

As a quick and dirty way around this, is there a way to inject CSS into the admin? I'm thinking I can hide the relevant ID `td` and `th` elements throughout the admin area.

Thanks.

**Comment by bobdenotter** [comment] 2017-06-08 16:40
Or channel your inner Elsa, and let it go. ;-)

Why do you want to hide the ID?

**Comment by DavidOliver** [comment] 2017-06-08 16:43
Unfortunately it's not me I am aiming to satisfy. :) The client has requested it as it's slightly confusing when the entries are ordered via a different numerical field. Plus the ID is often not relevant to listings.

I'm just trying the approach of creating a local-only custom/hack branch in which I edit the main listing layout file, but obviously that's not ideal. :)

**Comment by bobdenotter** [comment] 2017-06-08 16:46
You can create an extension, that does nothing but add a snippet or asset to the backend, and use some styles with `!important`. It's not too hard, but to me it still sound like a bunch of effort for a client's silly whim. ;-) 

https://docs.bolt.cm/3.2/extensions/basics/web-assets

**Comment by DavidOliver** [comment] 2017-06-08 16:48
Thanks for the pointer - I'll have a go at that after confirming I can write the CSS required.

It may be a relatively minor thing, but I can empathise with the desire to minimise the amount of information and remove elements which are irrelevant to the content editing of those responsible. Another CMS I used (Symphony CMS) had a 'Display in listings table' checkbox for each field, and it was nice to be able to keep things simple for the content editors/client.

**Comment by GawainLynch** [comment] 2017-06-08 17:21
> Just to confirm, is it because I used Composer to install that custom blocks in the /app/view/twig directory can't be used?

No, it is because currently we don't really support customising the backend yet, and never actually (officially) have … it is in a **huge amount* of flux at the moment getting ready for v4, where we will provide more options for customisation. We just can't do what we need to do with the backend changes _and_ support BC with the person-power at our hands.

At present, @bobdenotter's suggestion is honestly the best option … not ideal, but better than us adding 1 - 2 years of linear development time to that achieve in v3, versus providing an awesome solution for people early in the new year :smile:

**Comment by DavidOliver** [comment] 2017-06-08 17:24
Okay - many thanks for the info. I've gone with the local 'hack' branch approach for now, which I think should be okay as long as I remember to merge on each update and deploy from the hack branch. :)

**Comment by GawainLynch** [comment] 2017-06-08 17:27
Zero stress … It has been on my personal _"I want it, now!"_ list for years, just a long road to get there :smile:
