### ISSUE TITLE
Really slow Doctrine queries on Bolt backend

### ISSUE THREAD

**Issue by babaggeii** [bolt/bolt#2493] opened 2015-01-18 14:06 UTC
I just uploaded to a remote server and am getting strange behaviour with Doctrine.

Doctrine is making lots of reuqests to `information_schema.tables` and takes around 2 seconds for each one, making page requests to the backend around 25-30s. The other queries seem to be happening quickly. What's going on here and how can I stop it?

Output from debugger: 

    SELECT count(*) FROM information_schema.tables WHERE (table_schema = 'cl50-merc' OR table_catalog = 'cl50-merc') AND table_name = 'bolt_news'; 
    
    Parameters: [] 
    Time: 1896.29 ms

I should note that it doesn't take this long to make the requests on my local server. This is Bolt 2.0

**Comment by bobdenotter** [comment] 2015-01-18 14:36
This is a duplicate of #2471. Update to 2.0.3, and it'll be fixed.

**Closed by bobdenotter** 2015-01-18 14:36 UTC
