### ISSUE TITLE
Maximum function nesting level of '100' reached

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/bolt#4175] opened 2015-10-01 09:42 UTC
Hey,

I installed v2.2.11 on my new Macbook (php 5.6). Started the php dev server, created the first admin account and got the following error on the dashboard after login:

```
Whoops \ Exception \ ErrorException (E_ERROR)
Maximum function nesting level of '100' reached, aborting!
```

The error was thrown in `/vendor/twig/twig/lib/Twig/Compiler.php` on line `153`

**Comment by PhillippOhlandt** [comment] 2015-10-01 10:03
Ok, same error with v2.2.9
https://infinit.io/_/c2i8rU7

**Comment by SahAssar** [comment] 2015-10-01 10:24
`xdebug.max_nesting_level = 1000` in your php.ini will fix it.

Unfortunately this isn't something we can "fix" permanently.  Please see https://github.com/symfony/symfony/issues/7112 and what fabpot said there:

> So, I'm closing this issue as this is related to the too low value of the xdebug nesting level (unfortunately, the default value of 100 is really too small).

I'm going to close this, feel free to reopen if you get the same error after increasing `max_nesting_level`.

**Closed by SahAssar** 2015-10-01 10:24 UTC

**Comment by bobdenotter** [comment] 2015-10-01 10:43
Alternatively: Disable xdebug altogether in `php.ini`, if you don't use it.

**Comment by PhillippOhlandt** [comment] 2015-10-01 10:51
I changed it to 1000. Did that also on my last laptop but thought Bolt should also work with the default value.

**Comment by GawainLynch** [comment] 2015-10-01 11:13
Thing is, it isn't Bolt to blame, rather the complex nature of Twig template compilation, and xdebug having sane default that are by design not intended for all situations.

We most certainly should not set xdebug parameters in Bolt itself... It is the responsibility of the site owner... and should never be enabled in a production environment.

**Comment by adrianguenter** [comment] 2015-11-01 22:42
I know this is closed, so I'll open a new issue depending upon the answer I get here, but: Is there some standard place we could check if Xdebug is loaded, and if so bump `max_nesting_level` up with `ini_set` or emit a warning, if it's too low? This just bit me too.

**Comment by SahAssar** [comment] 2015-11-01 23:02
In my mind this is something that should be in the php config and the php config only, and overriding it from the app seems hacky and "wrong", a warning would be nice though... But perhaps somebody wiser like could weigh in on this?

**Comment by adrianguenter** [comment] 2015-11-01 23:04
No, I agree, in principle. A warning definitely seems more appropriate.
