### ISSUE TITLE
[BUG?] Doctrine DB listener invokes controller on exception

### ISSUE THREAD

**Issue by dantleech** [bolt/bolt#6074] opened 2016-11-23 11:11 UTC
The DoctrineListener invokes the controller when an error is encountered.

When an error is encountered in the console mode then the following error is produced:

```
RuntimeException: Exception controller being used outside of request cycle.
```

I encounter this during bootstrapping for functional tests, but imagine this would also happen in a CLI context (?).

Is it possible to disable this listener?

**Comment by GawainLynch** [comment] 2016-11-23 11:13
So we still have some request cycle mess to clean up :frowning_face: 

Do you have a reproducible scenario I can use to test? Should be pretty easy to fix if I know how you're triggering it.

**Comment by dantleech** [comment] 2016-11-23 11:19
You can just change your DB password and run:

```
./app/nut database:update                                                                                                            master ✭ ✱ ◼

                                                             
  [RuntimeException]                                         
  Exception controller being used outside of request cycle.  
                                                             
```

**Comment by GawainLynch** [comment] 2016-11-23 11:22
Well, just don't change your DB password :stuck_out_tongue_winking_eye: 

I'll get right on it!

**Comment by dantleech** [comment] 2016-11-23 11:25
No hurry! Cheers :)

**Comment by GawainLynch** [comment] 2016-11-23 11:48
@dantleech what version of Bolt? I am getting the correct exceptions on 3.2.x-dev
```
[gawain@legolas 3.2 (release/3.2)]$ ./app/nut database:update 
                                                
  [Bolt\Exception\BootException]                                                                                                  
  An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'bolt_testing'@'localhost' (using password: YES)  
                                                                                                                                  
  [Doctrine\DBAL\Exception\ConnectionException]                                                                                   
  An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'bolt_testing'@'localhost' (using password: YES)  
                                                                                                  
  [Doctrine\DBAL\Driver\PDOException]                                                             
  SQLSTATE[HY000] [1045] Access denied for user 'bolt_testing'@'localhost' (using password: YES)  
                                                                                                  
  [PDOException]                                                                                  
  SQLSTATE[HY000] [1045] Access denied for user 'bolt_testing'@'localhost' (using password: YES)  

database:update

[gawain@legolas 3.2 (release/3.2)]$ 
```

**Comment by dantleech** [comment] 2016-11-23 12:03
Was 3.2.2 tag, but just tried on dev-master and same result.

Changed the password in `config.yml` and ran `./app/nut database:update`

**Comment by GawainLynch** [comment] 2016-11-23 12:08
Are you using an extension by chance on that?

…I am scratching my head, but if the controller is invoked, it _should be_ inside request cycle already (obviously in your case it isn't).

**Comment by dantleech** [comment] 2016-11-23 12:12
Hmm, indeed I cannot reproduce on vanilla bolt. Must be something on my
end. Will need to investigate ...

**Comment by SahAssar** [comment] 2017-01-26 22:49
Since this hasn't been re-proed on "vanilla bolt" and we have had a few releases in the meantime I'm closing this, feel free to reopen if it's still an issue! :)

**Closed by SahAssar** 2017-01-26 22:49 UTC
Labels: Bug verification needed
