### ISSUE TITLE
Issue 'Save and go to overview' is still there in 2.0.6 RC2

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#2735] opened 2015-02-06 13:49 UTC
I just installed 2.0.6 RC2 and I noticed that the issue with saving entries is still there. This prevents us from going live with our website.

When I want to save an entry and immediately go to the overview of entries, Bolt stays in the edit window. When I use this option again, Bolt brings me to the overview page. I always have to do this twice to make it work. This does happen with both buttons (right top corner and left bottom) and also in different browsers.

**Comment by rarila** [comment] 2015-02-06 14:11
Can't reproduce with latest master and Firefox/Chrome/Win7 here. Anything to be found in browsers console output?

**Comment by gwbonline** [comment] 2015-02-06 14:32
What IE says is the following:

DOM7011: Zowel terug als vooruit in cache opslaan is door de code op deze pagina uitgeschakeld. Zie http://go.microsoft.com/fwlink/?LinkID=291337 voor meer informatie
Bestand: 27
HTML1300: Er heeft navigatie plaatsgevonden.
Bestand: 27
DOM7011: Zowel terug als vooruit in cache opslaan is door de code op deze pagina uitgeschakeld. Zie http://go.microsoft.com/fwlink/?LinkID=291337 voor meer informatie
Bestand: 27
HTML1512: Niet-overeenkomende eindtag.
Bestand: 27, regel: 1108, kolom: 37
HTML1509: Niet-overeenkomende eindtag.
Bestand: 27, regel: 1109, kolom: 37
HTML1509: Niet-overeenkomende eindtag.
Bestand: 27, regel: 1116, kolom: 53
HTML1512: Niet-overeenkomende eindtag.
Bestand: 27, regel: 1172, kolom: 17
HTML1509: Niet-overeenkomende eindtag.
Bestand: 27, regel: 1173, kolom: 13

Firefox says nothing, except for some css codes that have nothing to do with this.

**Comment by bobdenotter** [comment] 2015-02-06 14:33
This was mentioned to me before by @gwbonline, but I haven't been able to reproduce this either. Can you try to explain more clearly what's happening on your end?

**Comment by gwbonline** [comment] 2015-02-06 14:37
When I edit an entry and want to save it by using one of the orange buttons (top right corner or bottom left corner) this works fine. Both buttons have an extra option: save and go back to overview. This function doesn't work the first time. Bolt saves the entry and goes back to the edit window. When I use this function the second time, Bot does take me back to the overview page. The browser console of Firefox has no js errors, only some css messages. IE says what I posted above.

**Comment by bobdenotter** [comment] 2015-02-06 15:04
I am still pulling blanks here.. This is what I think you're doing, right? 

http://g.recordit.co/XnWJ8l1q6r.gif

**Comment by gwbonline** [comment] 2015-02-06 17:26
Yes, that is exactly what I mean. But in my case Bolt doesn't go to the 
overview. It stays in the edit window. I have to save the entry twice 
before I can get to the overview.

**Comment by bobdenotter** [comment] 2015-02-07 09:24
On my computer at home it works as it should, as well.. Could you e-mail me the details of the site? I'd like to take a look, to see if it's something in the specific website that's triggering it.

**Comment by gwbonline** [comment] 2015-02-11 11:54
I hope this is a Bolt issue so it can be solved in a (near) future release as well. People I gave access to Bolt think their entry isn't saved (only the save info below the button changes). There is no doubt if a entry is saved when Bolt goes directly to the overview page.

**Comment by GawainLynch** [comment] 2015-02-11 12:05
We'll do what we can.  Is there any way you can give @bobdenotter access to an affected site so he can further diagnose this?

**Comment by gwbonline** [comment] 2015-02-11 13:31
Yes, he already did that.

**Comment by bobdenotter** [comment] 2015-02-11 16:01
I have confirmed that it's acting "wonky" on @gwbonline's site. I have not yet been able to pinpoint if it's an issue with the server itself.. Leaving this open, so i can investigate more. :-)

**Comment by GawainLynch** [comment] 2015-05-17 06:59
@bobdenotter did you ever get to the bottom or this, or do either of you still notice a problem?

**Comment by gwbonline** [comment] 2015-05-17 07:36
The problem is still there. Maybe 2.2 beta solves it, but I haven't installed it yet. I'll try this later today or tomorrow.

**Comment by gwbonline** [comment] 2015-05-18 07:46
No... beta 2.2 hasn't solved this issue. This is strange, because other installs don't have problems related to saving an entry and go to the overview page. Could it be something server side?

**Comment by GawainLynch** [comment] 2015-05-18 14:41
Almost certainly is server side… I can't put my finger on what though.

**Comment by GawainLynch** [comment] 2015-05-18 14:42
Are you able to set up a totally basic install on that server that reproduces the problem?

**Comment by gwbonline** [comment] 2015-05-19 06:51
Yes, we had a second install (for testing) without extensions. Out of the box, saving and go to the overview page was always a problem. I will contact the hoster. Maybe it's some configuration. Can you point me to something, because I don't know what could possibly cause this issue.

**Comment by GawainLynch** [comment] 2015-05-19 06:53
My thought is something to do with PHP session saving, e.g. `session.save_path` in `php.ini`

**Comment by gwbonline** [comment] 2015-05-19 08:26
The default setting for this in our php.ini is:

    session.save_path = /var/lib/php/session

**Comment by GawainLynch** [comment] 2015-05-19 08:28
OK, and the fact you can login is good enough too… Honestly without access to logs and a console it is nothing short of the proverbial crap shoot…

**Comment by gwbonline** [comment] 2015-05-19 08:34
In the error log there are these three lines:

[Tue May 19 10:33:18 2015] [warn] [client 195.241.145.3] mod_fcgid: stderr: PHP Warning: is_dir(): open_basedir restriction in effect. File(/var/lib/php/session) is not within the allowed path(s): (/var/www/vhosts/radiospannenburg.nl/:/tmp/) in /var/www/vhosts/radiospannenburg.nl/httpdocs/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php on line 51, referer: http://www.radiospannenburg.nl/bolt/overview/berichten

[Tue May 19 10:33:18 2015] [warn] [client 195.241.145.3] mod_fcgid: stderr: PHP Warning: mkdir(): open_basedir restriction in effect. File(/var/lib/php/session) is not within the allowed path(s): (/var/www/vhosts/radiospannenburg.nl/:/tmp/) in /var/www/vhosts/radiospannenburg.nl/httpdocs/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php on line 52, referer: http://www.radiospannenburg.nl/bolt/overview/berichten

[Tue May 19 10:33:18 2015] [warn] [client 195.241.145.3] mod_fcgid: stderr: PHP Warning: ini_set(): open_basedir restriction in effect. File(/var/lib/php/session) is not within the allowed path(s): (/var/www/vhosts/radiospannenburg.nl/:/tmp/) in /var/www/vhosts/radiospannenburg.nl/httpdocs/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Session/Storage/Handler/NativeFileSessionHandler.php on line 55, referer: http://www.radiospannenburg.nl/bolt/overview/berichten

**Comment by GawainLynch** [comment] 2015-05-19 08:35
Ha! OK then, I was spot on! 

So `open_basedir` use is fine, but they need to set a path to write session data to.

**Comment by gwbonline** [comment] 2015-05-19 12:21
Path is set, no more errors in the error log... But the problem is still there. I emptied the cache and everything.

**Comment by gwbonline** [comment] 2015-05-21 06:42
Can I give you access to our server and Plesk?

**Comment by GawainLynch** [comment] 2015-05-21 06:47
Oh, that would be awesome. I am probably out of action for the next 24 hours as I am just arriving home later today and will need sleep, after that I can have a good look.

**Comment by gwbonline** [comment] 2015-05-21 06:57
That is ok. Have a nice sleep. I will send the needed info via email.

**Comment by gwbonline** [comment] 2015-05-25 10:11
@GawainLynch Did you have a good sleep? I was wondering how I can send you the login data...

**Comment by GawainLynch** [comment] 2015-05-25 10:23
I did, thank you :grin: 

You can email me at `gawain.lynch @ gmail.com`

**Comment by GawainLynch** [comment] 2015-07-28 08:15
Closing as part of a general issue clean up.

**Closed by GawainLynch** 2015-07-28 08:15 UTC
Labels: Question
