### ISSUE TITLE
[BUG] Backend not save field when it named with "_"

### ISSUE THREAD

**Issue by joshuan** [bolt/bolt#5713] opened 2016-08-27 19:45 UTC
Example, my contenttype.yml:
```
as:
    singular_slug: a
    fields:
        title:
            type: text

bs:
    singular_slug: b
    fields:
        act_id:
            type: select
            values: as
        actid:
            type: select
            values: as
```

When i click "Save" in /bolt/editcontent/bs, bolt don't save act_id (set to NULL or default value), but normal save actid.

Details
-------
 - Relevant Bolt Version: 3.1
 - Install type: GitHub checkout
 - PHP version: 5.6
 - Used web server: Apache 2.4

**Comment by GawainLynch** [comment] 2016-08-28 06:53
Duplicate of #5601 … 

We're in the process of working though the problems to get it fixed, I'm going to close this as we're have 5601 as the tracking issue.

**Closed by GawainLynch** 2016-08-28 06:53 UTC
Labels: Duplicate

**Comment by gonoszcsiga** [comment] 2016-09-04 16:30
Hi, i think this is not a duplicate of #5601, try this:
Create an image field with foo_bar_baz name in any content type and try to save. You get this error:
```Integrity constraint violation: 1048 Column 'foo_bar_baz' cannot be null```

I debug this and found the bug in the MagicAttributeTrait.php: https://github.com/bolt/bolt/blob/release/3.1/src/Storage/Entity/MagicAttributeTrait.php#L52
Too many conditions, but not enough! :) Missing if underscored or camelized found __in__ fields array, __but__ it is not object property.

This is my dirty quick fix for this:
```php
    public function __call($method, $arguments)
    {
        $var = lcfirst(substr($method, 3));
        $underscored = $this->underscore($var);
        $camelized = $this->camelize($var);

        if (strncasecmp($method, 'get', 3) == 0) {
            if ($this->has($var) && property_exists($this, $var)) {
                return $this->$var;
            } elseif ($this->has($camelized) && property_exists($this, $camelized)) {
                return $this->$camelized;
            } elseif ($this->has($underscored) && property_exists($this, $underscored)) {
                return $this->$underscored;
            } elseif ($this->has($var)) {
                return $this->_fields[$var];
            } elseif ($this->has($camelized)) {
                return $this->_fields[$camelized];
            } elseif ($this->has($underscored)) {
                return $this->_fields[$underscored];
            }
        }

        if (strncasecmp($method, 'serialize', 9) == 0) {
            $method = 'get' . substr($method, 9);

            return $this->$method();
        }

        if (strncasecmp($method, 'set', 3) == 0) {
            if ($this->has($var) && property_exists($this, $var)) {
                $this->$var = $arguments[0];
            } elseif ($this->has($underscored) && property_exists($this, $underscored)) {
                $this->$underscored = $arguments[0];
            } else {
                $this->_fields[$var] = $arguments[0];
            }
        }
    }
```

My Bolt version is: 3.1.0

**Comment by GawainLynch** [comment] 2016-09-05 06:17
> Hi, i think this is not a duplicate of #5601

Yeah, it is… the problem is just deeper than it looks. We're mutating in a few places, and do not have a clearly defined strategy that is applied to the mutations (leaving aside they should only ever happen in once place).

One of the reasons it hasn't been "hacked" to fix right now is that every time we try, it just cascades and breaks something else, so we're in the process of centralising configuration loading, normalisation & validation.

**Comment by gonoszcsiga** [comment] 2016-09-05 07:45
@GawainLynch duplicate or not, it's critical, because the content saving is broken in these case.

**Comment by GawainLynch** [comment] 2016-09-05 07:49
It isn't considered critical as it can safely be worked around … and the problem has existed in one form since Bolt 1.2.1 (released 13 September 2013).

**Comment by gonoszcsiga** [comment] 2016-09-05 08:09
@GawainLynch not exactly, try this in Bolt 3.0 then try in Bolt 3.1:
>Create an image field with foo_bar_baz name in any content type and try to save.

In Bolt 3.0 work properly, but failed in Bolt 3.1.

**Comment by GawainLynch** [comment] 2016-09-05 08:12
> In Bolt 3.0 work properly, but failed in Bolt 3.1.

To repeat my point … there is a deeper issue when one normalisation point is updated, it affects other and this problem has been bouncing around for over 2 years. 

Sorry, but it is as simple as that.

**Comment by GawainLynch** [comment] 2016-09-05 08:14
Also, you will probably find that the offending commit was introduced around 3.0.10 or 3.0.11 … that part of the code wasn't updated in the 3.1 branch. So the assertion isn't valid either way.
