### ISSUE TITLE
[BUG][UI] When deleting one or N records in the listing, all records disappear

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/bolt#5468] opened 2016-06-21 18:52 UTC
I think this gif shows it really good:

![](http://g.recordit.co/YaSaZQ1cXG.gif)

It's just an UI issue, the not selected record is still there after a reload.

Details
-------

 - Relevant Bolt Version: 3.0.7
 - Install type: composer
 - PHP version: 7.0
 - Used webserver: nginx
 - For UX/UI issues: chrome, latest stable

**Comment by GawainLynch** [comment] 2016-06-21 18:53
Yeah, and I think recent (/me looks at z-index PRs) as I was doing this on a 3.0.4 site last week and it worked.

**Comment by rarila** [comment] 2016-06-29 10:33
Hmm, can't reproduce (Chrome, Apache, 3.0.8), works as expected …
Any errors in the console?

**Comment by PhillippOhlandt** [comment] 2016-06-29 10:59
@rarila just tested it again on 3.0.7, no errors in the console.

**Comment by rarila** [comment] 2016-06-29 11:42
Ok, I don’t think 3.0.7/3.0.8 makes a difference.

Next step, could you please check if:

- a XHR request is sent to ``/async/content/action`` with formdata ``bolt_csrf_token``, ``contenttype`` and something looking like ``actions[pages][9][delete]``

- a response with status code ``200`` and a html fragment like ``<table class=" dashboardlisting listing">…</table>`` as data is returned

**Comment by bobdenotter** [comment] 2016-08-02 19:06
*BUMP*

Is this still an issue, @PhillippOhlandt ? I can't reproduce it on 3.0.11.

**Comment by PhillippOhlandt** [comment] 2016-08-02 19:37
@bobdenotter, @rarila, can't reproduce on 3.0.10 anymore. seems to be fine now :)

**Comment by SahAssar** [comment] 2016-08-02 19:39
actually, It's still an issue, and one of the ones that #5610 will fix once cleaned up enough to go in.

**Comment by SahAssar** [comment] 2016-08-02 19:41
The problem was/is that ajaxy requests don't show unpublished records, while non-ajaxy backend requests did. So, you'd only see this issue with unpublished records.

**Comment by PhillippOhlandt** [comment] 2016-08-02 20:04
Oh yes, @SahAssar is right. Still a bug with two unpublished records. Should this be reopened?

**Comment by SahAssar** [comment] 2016-08-02 20:15
Reopening and adding to #5610

**Comment by bobdenotter** [comment] 2016-08-03 14:18
Fixed by #5610

**Closed by bobdenotter** 2016-08-03 14:18 UTC
Labels: Bug verification needed
