### ISSUE TITLE
error  when installing  from composer

### ISSUE THREAD

**Issue by poznet** [bolt/bolt#3805] opened 2015-07-15 07:18 UTC
When i  install  boltfrom composer.  version  2.3.1   
After  instalation  and  creating  user ,  when  i try to log in  on  backend  i get
"Twig_Error_Syntax
HELP
The function "render" does not exist in "dashboard/_aside.twig" at line 25"

Problem don't  exists  when  installed from http://bolt.cm/distribution/bolt-latest.tar.gz  (the  easiest way section in  documentation )

**Comment by GawainLynch** [comment] 2015-07-15 07:23
This is due to you pulling in Silex 1.3 which has some breaking changes from a deprecated library that was removed.

Bolt versions from 2.2.1 onwards address the library issue, so I am guessing "2.3.1" is a mistype as 2.2.4 is the latest Bolt version.

**Comment by Intendit** [comment] 2015-07-15 07:23
Duplicate of #3727?

**Closed** 2015-07-15 07:23 UTC
