### ISSUE TITLE
Weird stuff with bolt_session cookies.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#3425] opened 2015-04-21 19:24 UTC
A short while ago, I had an issue where Bolt would _always_ set a `bolt_session` session cookie. Also on pages in the frontend, and also when you're not logged on. 

I did not want this, because setting a cookie on "static" pages in the frontend will prevent Varnish or Cloudflare from doing their jobs: Every page requests/visitor gets their own cookie.

See here: #3309 / https://github.com/bolt/bolt/pull/3309/files

This code _should_ prevent the `bolt_session` cookie from being set, but _only_ in the frontend. Note:

- "Not setting a cookie" by removing the header that is about to set it, is _not_ the same as _removing_ a previously set cookie. 
- This shouldn't interfere with _other_ cookies being set.
- If you're _not_ logged in, you _don't_ need a `bolt_session` cookie by default. 
- Setting it happens during initialisation of `Application.php`, in `initSession()`. (line 80)

For me, for the project i needed it to be gone, it works as it should. But, there's been more than one report of people seeing stupid shit happening, for it to be a coincidence. We should fix this. Somehow.

**Comment by GawainLynch** [comment] 2015-04-21 19:26
![cookies](https://cloud.githubusercontent.com/assets/1427081/7260783/a0a6c9a2-e864-11e4-98d4-74f5cc40a968.jpg)

**Comment by GawainLynch** [comment] 2015-04-21 19:31
Related to #3413

**Comment by Pinpickle** [comment] 2015-04-24 18:43
I had a good read through this recent discussion and it led me to the conclusion that using `$app['session']` is not good for extensions and sessions in the front end, correct?

I was wondering if there are any docs on how an extension might have its own sessions for simple things such as form flashes. I looked through the Symfony docs and through your code for clientlogin, @GawainLynch, but I couldn't work it out. I think this would be a common usecase, and without docs warning against it, people will probably go immediately to `$app['session']`.

**Comment by GawainLynch** [comment] 2015-04-24 19:00
Well, frontend sessions/cookies were broken for a short while and fixed in #3427. As it stands for the moment, default behaviour will be OK to use `$app['session']` but you'd be right that it's questionable to rely on it.  What is implemented in ClientLogin is simply a workaround for the behaviour introduced, but is no longer needed.

@CarsonF and I are looking at this for the Bolt responses in general in 2.3… watch this space :wink:

**Comment by Pinpickle** [comment] 2015-04-24 19:02
Sounds like 2.3 is going to make extensions very happy in lots of ways! I will eagerly watch all of the spaces.

**Comment by GawainLynch** [comment] 2015-04-24 19:12
We're going to try… 2.2 has largely been about getting our testing infrastructure in-line so we can make these changes with a bit more insight.

**Comment by rossriley** [comment] 2015-04-24 21:07
and if it all goes wrong there's a :koala: lined up as the fall-guy.

**Comment by bobdenotter** [comment] 2015-04-25 07:17
While this is certainly something we need to look into, this is currently not a showstopper anymore, right? We reverted the broken behaviour, and by default it works as before: You get a `bolt_session` cookie, unless explicitly disabled in your `config.yml`.

**Comment by GawainLynch** [comment] 2015-04-25 07:28
That is my assumption. As I understand it the introduced bug was itself the broader problem, and with that reverted we're good.

Failing that :koala: :gun:

**Comment by bobdenotter** [comment] 2015-05-05 12:40
Ok, with the setting for this, this is no longer "blocking release", but it's still something that ought to be fixed one way or another.

**Comment by GawainLynch** [comment] 2015-05-17 00:19
This is now fixed in our upcoming controller refactoring branch.

For those that are curious, the problem is that accessing `$app['session']` functions (e.g. `getFlashBag()` and friends) starts the Symfony/PHP session, which in turn sets the `bolt_session` cookie.

**Closed by GawainLynch** 2015-05-17 00:19 UTC
Labels: Regression

**Comment by bobdenotter** [comment] 2015-05-25 07:31
Fixed by #3564
