### ISSUE TITLE
[RFC] custom formatting of listing item

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#4816] opened 2016-02-08 05:24 UTC
##### Issue
Sometimes i need to customize the way, how my list looks like. Maybe it's interesting to have an ability to setup, how bolt formats each row in listing? Now it looks like heavy usage of `title` field and some other random fields. We can add a new property, that defines, how will Bolt format this string.

##### Probably it could look like:
```yml
persons:
    singular_name: Person
    editcontent_listing_format: 'item.last_name|default('Pleast set the last name')'
    fields: 
        …
```
we can use another property name

##### additionally
There are different types of listings. Should we allow user to customize them all?

**Comment by Boorj** [comment] 2016-02-08 07:10
I have a gallery, where each item has some properties, but no title. It looks this way:
![2016-02-08 13-08-14](https://cloud.githubusercontent.com/assets/2145313/12879962/fb0109da-ce64-11e5-93a7-eaa885045ac0.png)

By the way, **the second issue is:** listing string is escaped somewhere in *.twigs.

I can make this part of code by my own, only need opinion of the community.

**Comment by bobdenotter** [comment] 2016-02-08 07:57
This is already possible. Take a look at this for an example: 

https://github.com/bolt/bolt/blob/release/2.2/app/view/twig/custom/listing/pages.twig.dist

The second issue (the escaping), we will fix.

**Comment by Boorj** [comment] 2016-02-08 08:20
Can it be done for exact entity in `contenttypes.yml`?

**Comment by Boorj** [comment] 2016-02-08 08:21
and, by the way, does calculation of excerpt length concern about extra formatting symbols ?

**Comment by bobdenotter** [comment] 2016-02-08 08:53
> Can it be done for exact entity in contenttypes.yml? The idea was to make it simply editable, as format: in relations.

Yes. 

> and, by the way, does calculation of excerpt length concern about extra formatting symbols ?

No, by design. Your layout should really, really not depend on something being the exact guesstimated length.

**Comment by GawainLynch** [comment] 2016-02-08 11:34
Fixed in #4818

**Closed by GawainLynch** 2016-02-08 11:34 UTC

**Comment by Boorj** [comment] 2016-03-12 05:40
> No, by design. Your layout should really, really not depend on something being the exact guesstimated length. 
There are some html tags which are calculated as symbols here
https://github.com/Boorj/bolt/blob/master/app/view/twig/_base/_listing.twig#L165
```twig
{{ content.excerpt(excerptlength - title|length) }}
```
Maybe we should strip tags at first?

**Comment by Boorj** [comment] 2016-03-12 05:52
And @bobdenotter , how can I customize listings directly from `contenttypes.yml` ? not with this magic:

![2016-03-12 11-45-01](https://cloud.githubusercontent.com/assets/2145313/13721171/dfee9c50-e847-11e5-8bc1-b770d8b48457.png)

![2016-03-12 11-44-07](https://cloud.githubusercontent.com/assets/2145313/13721167/bfd669c0-e847-11e5-9f5f-08455c559920.png)

Actually, i can make a moduly by myself and make a PR. But you told above, that we can make it in easier way.

I remember that in Sonata Admin Bundle for Symfony2 there was an ability to setup entities both for [Form](https://sonata-project.org/bundles/admin/2-3/doc/getting_started/the_form_view.html) and for [Listing](https://sonata-project.org/bundles/admin/2-3/doc/getting_started/the_list_view.html):
![2016-03-12 11-50-24](https://cloud.githubusercontent.com/assets/2145313/13721191/a232dfec-e848-11e5-95ea-e855f3ce7bad.png)

But bolt is much simpler, so.. maybe we can setup listing with several text lines (in `contenttypes`) and **both** with `\custom\*`?

**Comment by Boorj** [comment] 2016-03-12 06:48
The guy here also suggested to setup listing view by string : https://stackoverflow.com/questions/29479755/contenttypes-in-bolt-cms-how-to-change-field-used-for-listing-in-backend/29522892#29522892 :)

**Comment by Boorj** [comment] 2018-03-28 10:37
@bobdenotter btw, can we now setup listing fields in backend? ( this answer on SOF doesn't enlighten me https://stackoverflow.com/a/29522892 )
