### ISSUE TITLE
Select Field - Using multiple ContentTypes doesn't store contenttype/id

### ISSUE THREAD

**Issue by Jabolek** [bolt/bolt#7339] opened 2018-02-14 13:24 UTC
When trying to add select field (both _single_ and _multiple_ don't work) as below the stored keys should be in form of _contenttype/id_. ( according to [this](https://docs.bolt.cm/3.4/fields/select#populating-the-values-from-multiple-contenttypes) ) Instead, only id's are saved. The issue is really similar to the https://github.com/bolt/bolt/issues/7303 issue, the difference in select field not being inside repeater field.

 

Details
-------

 - Relevant Bolt Version: 3.4.7
 - Install type: Composer install
 - PHP version: 7.2
 - Used web server: Nginx

Reproduction
------------

Define field like below in one of your content types (assuming you have _firstcontenttype_ and _secondcontenttype_ )

```
featured_resources:
    label: "Featured Resources"
    type: select
    values: (firstcontenttype,secondcontenttype)/title
    multiple: true
```
Next, add some entries to the select box and try to dump the value

```
{% dump(record.featured_resources) %}
```

### Expected result

```
array:2 [▼
  0 => "firstcontenttype/2"
  1 => "secondcontenttype/1"
]
```

### Dump result

```
array:2 [▼
  0 => "2"
  1 => "1"
]
```

**Comment by rossriley** [comment] 2018-02-14 13:31
I believe this is a duplicate of #7303 if anyone else wants to test the proposed solution in that ticket I'll turn it into a proper PR.

**Comment by cndforster** [comment] 2018-02-19 12:53
Are there any news about this issue yet? I just stumbled over this problem in my Bolt 3.4.7 installation.

**Comment by bobdenotter** [comment] 2018-02-19 13:16
@cndforster Ross proposed a solution in the linked issue. It would help us greatly if you could test that, and provide feedback.

**Comment by cndforster** [comment] 2018-02-20 12:02
@bobdenotter 
I tested it and it seems to work as it should.
Multiple contenttypes are stored as ["contenttype/id"] and a single contenttype as ["id"] in the database. Also the Selectfield in the bolt backend shows all relevant contenttypes now.
So from my side: it works!

**Comment by rossriley** [comment] 2018-02-20 13:14
@cndforster thanks for that, I'll get a PR in today hopefully.

**Closed** 2018-02-21 19:05 UTC
